NCEPLIBS-bufr: dxinit.f File Reference
dxinit.f File Reference
Initialize the internal arrays which contain the DX BUFR table.
Functions/Subroutines
subroutine dxinit (LUN, IOI)
This subroutine initializes the internal arrays (in module moda_tababd) holding the DX BUFR table.
Detailed Description
Initialize the internal arrays which contain the DX BUFR table.
Author
Woollen
Date
1994-01-06
Definition in file dxinit.f.
Function/Subroutine Documentation
dxinit()
subroutine dxinit (LUN, IOI)
This subroutine initializes the internal arrays (in module moda_tababd) holding the DX BUFR table.
It then initializes the table with apriori Table B and D entries (optional).
Parameters
[in] LUN - integer: I/O stream index into internal memory arrays.
[in] IOI - integer: switch:
0 do not initialize the table with apriori Table B and D entries.
else initialize the table with apriori Table B and D entries.
Author
Woollen
Date
1994-01-06
Definition at line 17 of file dxinit.f.
References moda_tababd::idnb, moda_tababd::idnd, ifxy(), moda_tababd::mtab, moda_tababd::ntba, moda_tababd::ntbb, moda_tababd::ntbd, pktdd(), moda_tababd::taba, moda_tababd::tabb, and moda_tababd::tabd.
Referenced by cpbfdx(), openbf(), rdbfdx(), rdmemm(), rdusdx(), readerme(), and reads3().