NCEPLIBS-bufr: getlens.f File Reference
getlens.f File Reference
Read the section lengths of a BUFR message.
Functions/Subroutines
recursive subroutine getlens (MBAY, LL, LEN0, LEN1, LEN2, LEN3, LEN4, LEN5)
This subroutine reads the lengths of all of the individual sections of a given BUFR message, up to a specified point in the message.
Detailed Description
Read the section lengths of a BUFR message.
Author
J. Ator
Date
2005-11-29
Definition in file getlens.f.
Function/Subroutine Documentation
getlens()
recursive subroutine getlens (dimension(*) MBAY, LL, LEN0, LEN1, LEN2, LEN3, LEN4, LEN5)
This subroutine reads the lengths of all of the individual sections of a given BUFR message, up to a specified point in the message.
This subroutine will work on any BUFR message encoded using BUFR edition 2, 3, or 4
Parameters
[in] MBAY – integer(*): BUFR message
[in] LL – integer: Number of last section for which the length is to be read. In other words, setting LL = N means to read and return the lengths of Sections 0 through N (i.e. LEN0, LEN1,...,LENN). Any section lengths that are not specified to be read are returned with a default placeholder value of -1.
[out] LEN0 – integer: Length (in bytes) of Section 0
[out] LEN1 – integer: Length (in bytes) of Section 1
[out] LEN2 – integer: Length (in bytes) of Section 2
[out] LEN3 – integer: Length (in bytes) of Section 3
[out] LEN4 – integer: Length (in bytes) of Section 4
[out] LEN5 – integer: Length (in bytes) of Section 5
Remarks
The start of the BUFR message (i.e. the string 'BUFR') must be aligned on the first 4 bytes of MBAY.
Author
J. Ator
Date
2005-11-29
Definition at line 34 of file getlens.f.
References modv_im8b::im8b, iupb(), iupbs01(), x48(), and x84().
Referenced by atrcpt(), cktaba(), cnved4(), copysb(), iupbs3(), msgwrt(), stbfdx(), stndrd(), upds3(), wrdxtb(), and writlc().