NCEPLIBS-bufr: inctab.f File Reference
inctab.f File Reference
Get the next available positional index for writing into the internal jump/link table.
Functions/Subroutines
subroutine inctab (ATAG, ATYP, NODE)
This subroutine returns the next available positional index for writing into the internal jump/link table in module tables, and it also uses that index to store atag and atyp within, respectively, the internal jump/link table arrays tag(*) and typ(*).
Detailed Description
Get the next available positional index for writing into the internal jump/link table.
Author
Woollen
Date
1994-01-06
Definition in file inctab.f.
Function/Subroutine Documentation
inctab()
subroutine inctab (character*(*) ATAG, character*(*) ATYP, NODE)
This subroutine returns the next available positional index for writing into the internal jump/link table in module tables, and it also uses that index to store atag and atyp within, respectively, the internal jump/link table arrays tag(*) and typ(*).
If there is no more room for additional entries within the internal jump/link table, then an appropriate call is made to subroutine bort().
Parameters
[in] ATAG - character*(*): mnemonic name.
[in] ATYP - character*(*): mnemonic type.
[in] NODE - integer: next available positional index for writing into the internal jump/link table.
Author
Woollen
Date
1994-01-06
Definition at line 20 of file inctab.f.
References bort(), moda_tables::maxtab, moda_tables::ntab, moda_tables::tag, and moda_tables::typ.
Referenced by tabent(), and tabsub().