NCEPLIBS-bufr: invwin.f File Reference
invwin.f File Reference
Search for a specified node within a specified portion of the current data subset.
Functions/Subroutines
function invwin (NODE, LUN, INV1, INV2)
This function looks for a specified node within the portion of the current subset buffer bounded by the indices inv1 and inv2.
Detailed Description
Search for a specified node within a specified portion of the current data subset.
Author
Woollen
Date
1994-01-06
Definition in file invwin.f.
Function/Subroutine Documentation
invwin()
function invwin (NODE, LUN, INV1, INV2)
This function looks for a specified node within the portion of the current subset buffer bounded by the indices inv1 and inv2.
It is similar to library function invtag(), except that invtag() searches based on the mnemonic corresponding to the node.
Parameters
[in] NODE - integer: jump/link table index to look for
[in] LUN - integer: file ID
[in] INV1 - integer: starting index of the portion of the subset buffer in which to look
[in] INV2 - integer: ending index of the portion of the subset buffer in which to look
Returns
- integer: location index of node within specified portion of subset buffer
0 not found
Author
Woollen
Date
1994-01-06
Definition at line 21 of file invwin.f.
References errwrt(), and moda_usrint::inv.
Referenced by drstpl(), getwin(), nevn(), trybump(), ufbget(), ufbrw(), and ufbseq().