NCEPLIBS-bufr: iupbs3.f File Reference
iupbs3.f File Reference
Read a data value from Section 3 of a BUFR message.
Functions/Subroutines
recursive function iupbs3 (MBAY, S3MNEM)
This function returns a specified value from within Section 3 of a BUFR message.
Detailed Description
Read a data value from Section 3 of a BUFR message.
Author
J. Ator
Date
2009-03-23
Definition in file iupbs3.f.
Function/Subroutine Documentation
iupbs3()
recursive function iupbs3 (dimension(*) MBAY, character*(*) S3MNEM)
This function returns a specified value from within Section 3 of a BUFR message.
Remarks
The start of the BUFR message (i.e. the string 'BUFR') must be aligned on the first 4 bytes of MBAY.
Parameters
[in] MBAY - integer(*): BUFR message
[in] S3MNEM - character*(*): Value to be read from Section 3 of MBAY
'NSUB' = Number of data subsets
'IOBS' = Flag indicating whether the message contains observed data:
0 = No
1 = Yes
'ICMP' = Flag indicating whether the message contains compressed data:
0 = No
1 = Yes
Returns
iupbs3 - integer: Value corresponding to S3MNEM
-1 = S3MNEM was invalid
Author
J. Ator
Date
2009-03-23
Definition at line 29 of file iupbs3.f.
References getlens(), modv_im8b::im8b, iupb(), and wrdlen().
Referenced by cktaba(), cpdxmm(), dumpbf(), mesgbc(), rdbfdx(), readerme(), stndrd(), and writlc().