NCEPLIBS-bufr: makestab.f File Reference
makestab.f File Reference
Build the internal jump/link table.
Functions/Subroutines
subroutine makestab
This subroutine constructs the internal jump/link table within module tables, using all of the internal BUFR table array information from module moda_tababd for all of the internal I/O streams that are currently defined to the library in module moda_stbfr.
Detailed Description
Build the internal jump/link table.
Author
J. Woollen
Date
1994-01-06
Definition in file makestab.f.
Function/Subroutine Documentation
makestab()
subroutine makestab
This subroutine constructs the internal jump/link table within module tables, using all of the internal BUFR table array information from module moda_tababd for all of the internal I/O streams that are currently defined to the library in module moda_stbfr.
The entire jump/link table will always be completely reconstructed from scratch, even if some of the information within the internal BUFR table arrays already existed there at the time of the previous call to this subroutine, because there may have been other events that have taken place since the previous call to this subroutine and which haven't yet been reflected within the internal jump/link table. For example, an I/O stream may have recently been unlinked from the library via an internal call to subroutine closbf(), or the DX BUFR tables associated with an I/O stream may have changed.
Author
J. Woollen
Date
1994-01-06
Definition at line 23 of file makestab.f.
References modv_bmiss::bmiss, bort(), chekstab(), closmg(), cpbfdx(), errwrt(), moda_tables::ibt, icmpdx(), moda_usrint::inv, moda_stbfr::iolun, moda_stbfr::iomsg, moda_tables::irf, moda_tables::isc, moda_tables::iseq, ishrdx(), moda_tables::itp, moda_tables::jmpb, moda_tables::jseq, moda_tables::jump, moda_tables::knt, moda_tables::knti, moda_tables::link, moda_lushr::lus, modv_maxjl::maxjl, moda_tababd::mtab, modv_nfiles::nfiles, moda_nrv203::nnrv, moda_tables::ntab, moda_bitmaps::ntamc, moda_tababd::ntba, moda_usrint::nval, strcln(), moda_tababd::taba, tabsub(), moda_tables::tag, moda_tables::typ, moda_tables::vali, wrdxtb(), and moda_xtab::xtab.
Referenced by rdbfdx(), rdmemm(), rdusdx(), readdx(), readerme(), and reads3().