NCEPLIBS-bufr: maxout.f File Reference
maxout.f File Reference
Define a customized maximum length for output BUFR messages.
Functions/Subroutines
recursive subroutine maxout (MAXO)
This subroutine allows the user to define the maximum length of a BUFR message that can be written to an output file by the BUFRLIB software.
Detailed Description
Define a customized maximum length for output BUFR messages.
Authors
J. Woollen, J. Ator
Date
2002-05-14
Definition in file maxout.f.
Function/Subroutine Documentation
maxout()
recursive subroutine maxout (MAXO)
This subroutine allows the user to define the maximum length of a BUFR message that can be written to an output file by the BUFRLIB software.
This subroutine can be called from within an application program at any time after the initial call to subroutine openbf(), and the specified value MAXO will then be used for all future BUFR messages written by the software to all output files for the remainder of the program, unless another call is made to this same subroutine to reset the value of MAXO again. Otherwise, if this subroutine is never called, a default maximum message length is used for all output files, as set via an initial internal call to subroutine bfrini().
Parameters
[in] MAXO – integer: New maximum length (in bytes) for all BUFR messages written to all output files
0 = Set MAXO to the maximum value allowed by the BUFRLIB software
Authors
J. Woollen, J. Ator
Date
2002-05-14
Definition at line 26 of file maxout.f.
References errwrt(), modv_im8b::im8b, moda_bitbuf::maxbyt, modv_mxmsgl::mxmsgl, and x84().
Referenced by bufr_c2f_interface::maxout_c(), and split_by_subset().