NCEPLIBS-bufr: moda_comprx Module Reference
moda_comprx Module Reference
This module contains arrays and variable declarations for the storage of data values needed when writing compressed data subsets to a BUFR message for output.
Variables
character *(:), dimension(:), allocatable cstr
Character data value, if corresponding ityp value is set to 3.
logical flush
Flush flag.
integer, dimension(:), allocatable ityp
Type of each data value:
integer, dimension(:), allocatable iwid
Bit width of underlying data descriptor as defined within Table B for each data value.
integer, dimension(:), allocatable kbit
Number of bits needed to hold the increments for this data value within each data subset of the message.
integer kbyt
Number of bytes required to store Sections 0, 1, 2, and 3 of message.
integer(8), dimension(:), allocatable kmax
Maximum of each data value across all data subsets in message.
integer(8), dimension(:), allocatable kmin
Minimum of each data value across all data subsets in message.
logical, dimension(:), allocatable kmis
"Missing" values flag.
integer lunc
I/O stream index into internal arrays for output file.
integer nrow
Number of data values for each data subset in message.
logical writ1
Write-out flag.
Detailed Description
This module contains arrays and variable declarations for the storage of data values needed when writing compressed data subsets to a BUFR message for output.
This module can only be used to store the information for one compressed BUFR message at any given time.
Author
J. Woollen
Date
2002-05-14
Variable Documentation
cstr
character*(:), dimension(:), allocatable moda_comprx::cstr
Character data value, if corresponding ityp value is set to 3.
Definition at line 189 of file modules_arrs.F90.
Referenced by ardllocf(), and wrcmps().
flush
logical moda_comprx::flush
Flush flag.
Set to .true. if a subroutine call was made to force the writing of the message to the corresponding output file, even if there may still be room in the message for additional data subsets. Otherwise set to .false.
Definition at line 165 of file modules_arrs.F90.
Referenced by wrcmps().
ityp
integer, dimension(:), allocatable moda_comprx::ityp
Type of each data value:
1 Delayed descriptor replication factor.
2 Other non-character data.
3 Character data.
Definition at line 184 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and wrcmps().
iwid
integer, dimension(:), allocatable moda_comprx::iwid
Bit width of underlying data descriptor as defined within Table B for each data value.
Definition at line 187 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and wrcmps().
kbit
integer, dimension(:), allocatable moda_comprx::kbit
Number of bits needed to hold the increments for this data value within each data subset of the message.
Definition at line 179 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and wrcmps().
kbyt
integer moda_comprx::kbyt
Number of bytes required to store Sections 0, 1, 2, and 3 of message.
Definition at line 160 of file modules_arrs.F90.
Referenced by wrcmps().
kmax
integer(8), dimension(:), allocatable moda_comprx::kmax
Maximum of each data value across all data subsets in message.
Definition at line 172 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and wrcmps().
kmin
integer(8), dimension(:), allocatable moda_comprx::kmin
Minimum of each data value across all data subsets in message.
Definition at line 170 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and wrcmps().
kmis
logical, dimension(:), allocatable moda_comprx::kmis
"Missing" values flag.
Set to .true. if at least one occurrence of this data value is "missing" within any data subset of the message. Otherwise set to .false.
Definition at line 176 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and wrcmps().
lunc
integer moda_comprx::lunc
I/O stream index into internal arrays for output file.
Definition at line 158 of file modules_arrs.F90.
Referenced by wrcmps().
nrow
integer moda_comprx::nrow
Number of data values for each data subset in message.
Definition at line 156 of file modules_arrs.F90.
Referenced by wrcmps().
writ1
logical moda_comprx::writ1
Write-out flag.
Set to .true. if the message needs to be written to the corresponding output file. Otherwise set to .false.
Definition at line 168 of file modules_arrs.F90.
Referenced by wrcmps().