NCEPLIBS-bufr: moda_lushr Module Reference
moda_lushr Module Reference
This module contains a declaration for an array used by subroutine makestab() to keep track of which logical units share DX BUFR table information.
Variables
integer, dimension(:), allocatable lus
Tracking index for each I/O internal stream index.
Detailed Description
This module contains a declaration for an array used by subroutine makestab() to keep track of which logical units share DX BUFR table information.
Author
J. Woollen
Date
1994-01-06
Variable Documentation
lus
integer, dimension(:), allocatable moda_lushr::lus
Tracking index for each I/O internal stream index.
Set to a value of zero if the corresponding logical unit does not share DX BUFR table information with any other logical unit. Otherwise set to a non-zero value within subroutine makestab().
Definition at line 286 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), makestab(), and openbf().