NCEPLIBS-bufr: moda_ivttmp Module Reference
moda_ivttmp Module Reference
This module contains arrays which provide working space in several subprograms (usrtpl() and ufbcup()) which manipulate the contents of the internal subset buffers where the contents of an evolving BUFR message are sccumulated and stored under user control prior to being written out.
Variables
integer, dimension(:), allocatable itmp
inv array elements for new sections of a growing subset buffer.
character *10, dimension(:), allocatable ttmp
tag array elements for new sections of a growing subset buffer.
real *8, dimension(:), allocatable vtmp
val array elements for new sections of a growing subset buffer.
Detailed Description
This module contains arrays which provide working space in several subprograms (usrtpl() and ufbcup()) which manipulate the contents of the internal subset buffers where the contents of an evolving BUFR message are sccumulated and stored under user control prior to being written out.
Author
J. Woollen
Date
1994-01-06
Variable Documentation
itmp
integer, dimension(:), allocatable moda_ivttmp::itmp
inv array elements for new sections of a growing subset buffer.
Definition at line 271 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), ufbcup(), and usrtpl().
ttmp
character*10, dimension(:), allocatable moda_ivttmp::ttmp
tag array elements for new sections of a growing subset buffer.
Definition at line 269 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and ufbcup().
vtmp
real*8, dimension(:), allocatable moda_ivttmp::vtmp
val array elements for new sections of a growing subset buffer.
Definition at line 273 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and usrtpl().