NCEPLIBS-bufr: moda_msgcwd Module Reference
moda_msgcwd Module Reference
This module contains declarations for arrays used to store information about the current BUFR message that is in the process of being read from or written to the logical unit associated with each internal I/O stream index.
Variables
integer, dimension(:), allocatable idate
Section 1 date-time of message.
integer, dimension(:), allocatable inode
Table A mnemonic for type of BUFR message.
integer, dimension(:), allocatable msub
Total number of data subsets in message.
integer, dimension(:), allocatable nmsg
Current message pointer within logical unit.
integer, dimension(:), allocatable nsub
Current subset pointer within message.
Detailed Description
This module contains declarations for arrays used to store information about the current BUFR message that is in the process of being read from or written to the logical unit associated with each internal I/O stream index.
Author
J. Woollen
Date
1994-01-06
Variable Documentation
idate
integer, dimension(:), allocatable moda_msgcwd::idate
Section 1 date-time of message.
Definition at line 325 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), copymg(), cpymem(), msgini(), openbf(), openmb(), openmg(), readmg(), readns(), rewnbf(), and wrcmps().
inode
integer, dimension(:), allocatable moda_msgcwd::inode
Table A mnemonic for type of BUFR message.
Definition at line 323 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), copymg(), copysb(), cpbfdx(), cpymem(), bufr_c2f_interface::get_inode_c(), gettagpr(), gettagre(), getvalnb(), igetrfel(), iok2cpy(), lstjpb(), msgini(), nemspecs(), openbf(), openmb(), openmg(), parutg(), rcstpl(), readmg(), readns(), rewnbf(), setvalnb(), strbtm(), string(), ufbcpy(), ufbcup(), ufbdmp(), ufbevn(), ufbin3(), ufbint(), ufbovr(), ufbrep(), ufbseq(), ufbstp(), ufdump(), usrtpl(), and wrcmps().
msub
integer, dimension(:), allocatable moda_msgcwd::msub
Total number of data subsets in message.
Definition at line 321 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), copymg(), copysb(), cpymem(), ifbget(), nmsub(), openbf(), rdcmps(), rdmems(), readsb(), rewnbf(), ufbget(), ufbinx(), ufbmms(), ufbrms(), ufbtab(), and ufbtam().
nmsg
integer, dimension(:), allocatable moda_msgcwd::nmsg
Current message pointer within logical unit.
Definition at line 317 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), closmg(), copymg(), cpymem(), msgini(), openbf(), rdmemm(), rewnbf(), ufbcnt(), ufbpos(), ufbtab(), and ufbtam().
nsub
integer, dimension(:), allocatable moda_msgcwd::nsub
Current subset pointer within message.
Definition at line 319 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), closmg(), copymg(), copysb(), cpymem(), cpyupd(), ifbget(), msgini(), msgupd(), openbf(), rdcmps(), rdmems(), readsb(), rewnbf(), ufbcnt(), ufbget(), ufbinx(), ufbpos(), ufbtab(), ufbtam(), ufdump(), wrcmps(), and writlc().