NCEPLIBS-bufr: numtbd.f File Reference
numtbd.f File Reference
Search for a Table B or Table D descriptor within the internal DX BUFR tables.
Functions/Subroutines
subroutine numtbd (LUN, IDN, NEMO, TAB, IRET)
Search for a Table B or Table D descriptor within the internal DX BUFR tables.
Detailed Description
Search for a Table B or Table D descriptor within the internal DX BUFR tables.
Author
J. Woollen
Date
2002-05-14
Definition in file numtbd.f.
Function/Subroutine Documentation
numtbd()
subroutine numtbd (LUN, IDN, character*(*) NEMO, character*1 TAB, IRET)
Search for a Table B or Table D descriptor within the internal DX BUFR tables.
Parameters
[in] LUN - integer: File ID.
[in] IDN - integer: Bit-wise representation of FXY value for Table B or Table D descriptor.
[out] NEMO - character*(*): Mnemonic associated with IDN.
[out] TAB - character: Type associated with IDN:
'B' = Table B descriptor
'D' = Table D descriptor
[out] IRET - integer:
Positional index of IDN within internal Table B, if TAB = 'B'
Positional index of IDN within internal Table D, if TAB = 'D'
0, otherwise
Author
J. Woollen
Date
2002-05-14
Definition at line 23 of file numtbd.f.
References moda_tababd::idnb, moda_tababd::idnd, ifxy(), moda_tababd::ntbb, moda_tababd::ntbd, moda_tababd::tabb, and moda_tababd::tabd.
Referenced by getcfmng(), numtab(), bufr_c2f_interface::numtbd_c(), and ufdump().