NCEPLIBS-bufr: strcpt.f File Reference
strcpt.f File Reference
Specify a tank receipt time to be included in Section 1 when writing BUFR messages.
Functions/Subroutines
recursive subroutine strcpt (CF, IYR, IMO, IDY, IHR, IMI)
This subroutine is used to specify a tank receipt time to be included within Section 1 of all BUFR messages output by future calls to message-writing subroutines and subset-writing subroutines.
Detailed Description
Specify a tank receipt time to be included in Section 1 when writing BUFR messages.
Author
J. Ator
Date
2009-03-23
Definition in file strcpt.f.
Function/Subroutine Documentation
strcpt()
recursive subroutine strcpt (character*1 CF, IYR, IMO, IDY, IHR, IMI)
This subroutine is used to specify a tank receipt time to be included within Section 1 of all BUFR messages output by future calls to message-writing subroutines and subset-writing subroutines.
This subroutine can be called at any time after the first call to subroutine openbf(), and the specified value for CF will remain in effect for all future calls to message-writing subroutines and subset-writing subroutines, for all Fortran logical units that are open for output within the application program, unless a subsequent call is made to this subroutine to reset the value of CF again. If this subroutine is never called, a default value of 'N' is used for CF, as set within subroutine bfrini().
Whenever this subroutine is called with CF = 'N', the values in IYR, IMO, IDY, IHR, and IMI are ignored.
Remarks
Tank receipt time is an NCEP extension to Section 1 of the official WMO BUFR regulations. However, it's encoded by the BUFRLIB software in such a way that its inclusion within an output BUFR message is still fully compliant with the regulations.
Parameters
[in] CF - character*1: Flag indicating whether future BUFR output messages should include the tank receipt time defined by IYR, IMO, IDY, IHR, and IMI:
'N' = No (the default)
'Y' = Yes
[in] IYR - integer: Tank receipt year.
[in] IMO - integer: Tank receipt month.
[in] IDY - integer: Tank receipt day.
[in] IHR - integer: Tank receipt hour.
[in] IMI - integer: Tank receipt minute.
Author
J. Ator
Date
2009-03-23
Definition at line 44 of file strcpt.f.
References bort(), capit(), modv_im8b::im8b, and x84().