NCEPLIBS-bufr: ufbcup.f File Reference
ufbcup.f File Reference
Copy unique elements of a data subset.
Functions/Subroutines
recursive subroutine ufbcup (LUBIN, LUBOT)
Copy unique elements of a data subset.
Detailed Description
Copy unique elements of a data subset.
Author
Woollen
Date
1994-01-06
Definition in file ufbcup.f.
Function/Subroutine Documentation
ufbcup()
recursive subroutine ufbcup (LUBIN, LUBOT)
Copy unique elements of a data subset.
This subroutine makes one copy of each unique element in an input subset buffer into the identical mnemonic slot in the output subset buffer.
Before this subroutine is called:
The input file must be opened for input with openbf().
a message must be read, as with readmg().
a subset of data loaded into memory, as with readsb().
the output file must be opened for output with openbf().
a message must be created in the output file, as with openmg().
After this subroutine is called, writsb() must be called on the output file to write the subset to file.
Parameters
[in] LUBIN - integer: fortran logical unit number for input BUFR file.
[in] LUBOT - integer: fortran logical unit number for output BUFR file.
Author
Woollen
Date
1994-01-06
Definition at line 28 of file ufbcup.f.
References bort(), modv_im8b::im8b, moda_msgcwd::inode, moda_usrint::inv, moda_ivttmp::itmp, moda_tables::itp, moda_usrint::nval, status(), moda_tables::tag, moda_ivttmp::ttmp, moda_usrint::val, and x84().