NCEPLIBS-bufr: ufbcnt.f File Reference
ufbcnt.f File Reference
Get the current message number and data subset number within a BUFR file.
Functions/Subroutines
recursive subroutine ufbcnt (LUNIT, KMSG, KSUB)
Get the current message number and data subset number within a BUFR file.
Detailed Description
Get the current message number and data subset number within a BUFR file.
Author
J. Woollen
Date
1994-01-06
Definition in file ufbcnt.f.
Function/Subroutine Documentation
ufbcnt()
recursive subroutine ufbcnt (LUNIT, KMSG, KSUB)
Get the current message number and data subset number within a BUFR file.
This subroutine returns the current location of the file pointer within a BUFR file, in terms of a message number counting from the beginning of the file, and a data subset number counting from the beginning of that message.
Remarks
Logical unit LUNIT should have already been opened via a previous call to subroutine openbf(). If LUNIT was opened for input operations, then KMSG is incremented with each call to any of the message-reading subroutines, and KSUB is incremented with each call to any of the subset-reading subroutines for that message. Otherwise, if LUNIT was opened for output operations, then KMSG is incremented with each call to any of the message-writing subroutines, and KSUB is incremented with each call to any of the subset-writing subroutines for that message.
The value returned for KMSG does not include any messages which contain DX BUFR tables information.
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file.
[out] KMSG - integer: Ordinal number of current message, counting from the beginning of the BUFR file, but not counting any messages which contain DX BUFR tables information.
[out] KSUB - integer: Ordinal number of current data subset within (KMSG)th message, counting from the beginning of the message.
Author
J. Woollen
Date
1994-01-06
Definition at line 40 of file ufbcnt.f.
References bort(), modv_im8b::im8b, moda_msgcwd::nmsg, moda_msgcwd::nsub, status(), x48(), and x84().
Referenced by cmpbqm(), readbp(), and ufbpos().