NCEPLIBS-bufr: ufbrw.f File Reference
ufbrw.f File Reference
Read/write one or more data values from/to a data subset.
Functions/Subroutines
subroutine ufbrw (LUN, USR, I1, I2, IO, IRET)
This subroutine writes or reads specified values to or from the current BUFR data subset within internal arrays, with the direction of the data transfer determined by the context of IO.
Detailed Description
Read/write one or more data values from/to a data subset.
Author
J. Woollen
Date
1994-01-06
Definition in file ufbrw.f.
Function/Subroutine Documentation
ufbrw()
subroutine ufbrw (LUN, real*8, dimension(i1,i2) USR, I1, I2, IO, IRET)
This subroutine writes or reads specified values to or from the current BUFR data subset within internal arrays, with the direction of the data transfer determined by the context of IO.
The data values correspond to internal arrays representing parsed strings of mnemonics which are part of a delayed-replication sequence, or for which there is no replication at all.
This subroutine should never be directly called by an application program; instead, an application program should directly call ufbint() which will internally call this subroutine.
Parameters
[in] LUN - integer: I/O stream index into internal memory arrays.
[in,out] USR - real*8(*,*): Data values
[in] I1 - integer: length of first dimension of USR.
[in] I2 - integer: length of second dimension of USR.
[in] IO - integer: status indicator for BUFR file associated with LUN:
0 input file
1 output file
[out] IRET - integer: number of "levels" of data values read from or written to data subset
-1 none of the mnemonics in the string passed to ufbint() were found in the data subset template
Author
J. Woollen
Date
1994-01-06
Definition at line 31 of file ufbrw.f.
References modv_bmiss::bmiss, conwin(), drstpl(), errwrt(), getwin(), ibfms(), moda_usrint::inv, invwin(), lstjpb(), newwin(), nxtwin(), moda_tables::tag, and moda_usrint::val.
Referenced by trybump(), and ufbint().