NCEPLIBS-bufr: icmpdx.f File Reference
icmpdx.f File Reference
Check whether two BUFR files have the same DX BUFR table information.
Functions/Subroutines
INTEGER function icmpdx (LUD, LUN)
This function determines whether the full set of associated DX BUFR Table information is identical between two Fortran logical units.
Detailed Description
Check whether two BUFR files have the same DX BUFR table information.
Definition in file icmpdx.f.
Function/Subroutine Documentation
INTEGER function icmpdx (LUD, LUN)
This function determines whether the full set of associated DX BUFR Table information is identical between two Fortran logical units.
Note that two different logical units can have identical DX BUFR Table information associated with them even if they aren't actually sharing the same DX BUFR table.
Author
J. Ator
Date
2009-06-18
Parameters
[in] LUD – integer: Internal I/O stream index associated with first BUFR file
[in] LUN – integer: Internal I/O stream index associated with second BUFR file
Returns
icmpdx – integer: Flag indicating whether the BUFR file associated with LUD and the BUFR file associated with LUN have the same DX BUFR table information
0 = No
1 = Yes
Program history log:
Date Programmer Comments
2009-06-18 J. Ator Original author
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 33 of file icmpdx.f.
References ishrdx().
Referenced by iok2cpy(), and makestab().