NCEPLIBS-bufr: msgfull.f File Reference
msgfull.f File Reference
Check whether a data subset will fit within a BUFR message.
Functions/Subroutines
LOGICAL function msgfull (MSIZ, ITOADD, MXSIZ)
This function determines whether the current data subset in the internal arrays will fit within the current BUFR message in the internal arrays, based on the prescribed maximum size of a BUFR message and the allowance of some extra "wiggle room" that may be needed later when writing out the message.
Detailed Description
Check whether a data subset will fit within a BUFR message.
Definition in file msgfull.f.
Function/Subroutine Documentation
LOGICAL function msgfull (MSIZ, ITOADD, MXSIZ)
This function determines whether the current data subset in the internal arrays will fit within the current BUFR message in the internal arrays, based on the prescribed maximum size of a BUFR message and the allowance of some extra "wiggle room" that may be needed later when writing out the message.
Author
J. Ator
Date
2009-03-23
Parameters
[in] MSIZ – integer: Size (in bytes) of current BUFR message
[in] ITOADD – integer: Size (in bytes) of current data subset
[in] MXSIZ – integer: Maximum size of a BUFR message
Returns
MSGFULL – logical: Flag indicating whether the current data subset will fit within the current BUFR message
Program history log:
Date Programmer Comments
2009-03-23 J. Ator Original author
Definition at line 25 of file msgfull.f.
Referenced by cpyupd(), msgupd(), wrcmps(), and wrdxtb().