NCEPLIBS-bufr: nemtbb.f File Reference
nemtbb.f File Reference
Get information about a Table B descriptor.
Functions/Subroutines
subroutine nemtbb (LUN, ITAB, UNIT, ISCL, IREF, IBIT)
This subroutine returns information about a Table B descriptor from the internal DX BUFR tables.
Detailed Description
Get information about a Table B descriptor.
Definition in file nemtbb.f.
Function/Subroutine Documentation
subroutine nemtbb (LUN, ITAB, character*24 UNIT, ISCL, IREF, IBIT)
This subroutine returns information about a Table B descriptor from the internal DX BUFR tables.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUN – integer: Internal I/O stream index associated with DX BUFR tables
[in] ITAB – integer: Positional index of descriptor within internal Table B
[out] UNIT – character*24: Units of descriptor
[out] ISCL – integer: Scale factor of descriptor
[out] IREF – integer: Reference value of descriptor
[out] IBIT – integer: Bit width of descriptor
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1995-06-28 J. Woollen Increased the size of internal BUFR table arrays in order to handle bigger files
1998-07-08 J. Woollen Replaced call to Cray library routine "ABORT" with call to new internal routine bort()
1999-11-18 J. Woollen Changed call to function "val$" to valx()
2003-11-04 J. Ator Added documentation
2003-11-04 S. Bender Added remarks/bufrlib routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added documentation; outputs more complete diagnostic info when routine terminates abnormally
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 31 of file nemtbb.f.
References bort(), ifxy(), and valx().
Referenced by chekstab(), restd(), and tabent().