NCEPLIBS-bufr: wrdxtb.f File Reference
wrdxtb.f File Reference
Functions/Subroutines
subroutine wrdxtb (LUNDX, LUNOT)
THIS SUBROUTINE WRITES BUFR TABLE (DICTIONARY) MESSAGES ASSOCIATED WITH THE BUFR FILE IN LUNDX TO THE BUFR FILE IN LUNOT.
Detailed Description
Author
J
Date
2009-03-23
Definition in file wrdxtb.f.
Function/Subroutine Documentation
subroutine wrdxtb (LUNDX, LUNOT)
THIS SUBROUTINE WRITES BUFR TABLE (DICTIONARY) MESSAGES ASSOCIATED WITH THE BUFR FILE IN LUNDX TO THE BUFR FILE IN LUNOT.
BOTH UNITS MUST BE OPENED VIA PREVIOUS CALLS TO BUFR ARCHIVE LIBRARY SUBROUTINE OPENBF, AND IN PARTICULAR LUNOT MUST HAVE BEEN OPENED FOR OUTPUT. THE TABLE MESSAGES ARE GENERATED FROM ARRAYS IN INTERNAL MEMORY (MODULE TABABD). LUNDX CAN BE THE SAME AS LUNOT IF IT IS DESIRED TO APPEND TO LUNOT WITH BUFR MESSAGES GENERATED FROM ITS OWN INTERNAL TABLES.
PROGRAM HISTORY LOG: 2009-03-23 J. ATOR – ORIGINAL AUTHOR, USING LOGIC FROM WRITDX 2012-04-06 J. ATOR – PREVENT STORING OF MORE THAN 255 TABLE A, TABLE B OR TABLE D DESCRIPTORS IN ANY SINGLE DX MESSAGE 2014-11-14 J. ATOR – REPLACE IPKM CALLS WITH PKB CALLS 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL WRDXTB (LUNDX,LUNOT) INPUT ARGUMENT LIST: LUNDX - INTEGER: FORTRAN LOGICAL UNIT NUMBER ASSOCIATED WITH DX (DICTIONARY) TABLES TO BE WRITTEN OUT; CAN BE SAME AS LUNOT LUNOT - INTEGER: FORTRAN LOGICAL UNIT NUMBER FOR BUFR FILE TO BE APPENDED WITH TABLES ASSOCIATED WITH LUNDX
REMARKS: THIS ROUTINE CALLS: ADN30 BORT CPBFDX DXMINI GETLENS IUPB IUPM MSGFULL MSGWRT PKB PKC STATUS THIS ROUTINE IS CALLED BY: MAKESTAB WRITDX Also called by application programs.
Definition at line 36 of file wrdxtb.f.
References adn30(), bort(), cpbfdx(), dxmini(), getlens(), iupb(), iupm(), msgfull(), msgwrt(), pkb(), pkc(), and status().
Referenced by makestab(), and writdx().