//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.19 at 09:44:16 AM EST 
//


package TableD22.jabx;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the TableD22.jabx package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: TableD22.jabx
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dataroot }
     * 
     */
    public Dataroot createDataroot() {
        return new Dataroot();
    }

    /**
     * Create an instance of {@link BUFR2201TableDEn }
     * 
     */
    public BUFR2201TableDEn createBUFR2201TableDEn() {
        return new BUFR2201TableDEn();
    }

}
