NCEPLIBS-bufr: apxdx.F90 File Reference
apxdx.F90 File Reference
Append a specified DX BUFR table to a specified BUFR file.
Functions/Subroutines
program apxdx
Generate BUFR messages corresponding to a given DX BUFR table and append them to a given BUFR file.
Detailed Description
Append a specified DX BUFR table to a specified BUFR file.
Author
J. Ator
Date
2009-07-01
Definition in file apxdx.F90.
Function/Subroutine Documentation
apxdx()
program apxdx
Generate BUFR messages corresponding to a given DX BUFR table and append them to a given BUFR file.
This program is primarily intended for use when implementing DX BUFR table changes to one or more BUFR tankfiles in the NCEP observational database, but it has other potential uses as well.
Usage: apxdx BUFRfile DXtable
Upon successful output, the original BUFRfile will have BUFR messages appended to it corresponding to the given DXtable.
Returns
0 for success, error message otherwise
Remarks
The original BUFRfile must contain embedded DX BUFR table messages corresponding to any existing BUFR messages in the file
Fortran logical unit numbers 10, 11, and 12 are reserved for use within this program
Author
J. Ator
Date
2009-07-01
Definition at line 22 of file apxdx.F90.
References closbf(), openbf(), and wrdxtb().