NCEPLIBS-bufr: binv.F90 File Reference
binv.F90 File Reference
Produce an inventory of subsets in a bufr file.
Functions/Subroutines
program binv
Usage: binv <bufrfile> will print bufrfile inventory by message type.
Detailed Description
Produce an inventory of subsets in a bufr file.
Author
J Woollen
Date
1994
Definition in file binv.F90.
Function/Subroutine Documentation
binv()
program binv
Usage: binv <bufrfile> will print bufrfile inventory by message type.
Returns
0 for success, error message otherwise.
Author
J Woollen
Date
1994
Definition at line 11 of file binv.F90.
References bort(), ireadmg(), iupvs01(), nmsub(), and openbf().