NCEPLIBS-bufr: borts.F90 File Reference
borts.F90 File Reference
Log one or more error messages and abort application program.
Functions/Subroutines
subroutine bort (str)
Log an error message, then abort the application program.
subroutine bort2 (str1, str2)
Log two error messages, then abort the application program.
Detailed Description
Log one or more error messages and abort application program.
Author
J. Ator
Date
2009-04-21
Definition in file borts.F90.
Function/Subroutine Documentation
bort()
subroutine bort (character*(*), intent(in) str)
Log an error message, then abort the application program.
This subroutine is similar to subroutine bort2(), except that bort2() logs two error messages instead of one.
Parameters
str - Error message
Author
J. Woollen
Date
1998-07-08
Definition at line 14 of file borts.F90.
References errwrt().
Referenced by adn30(), arallocf(), atrcpt(), binv(), bufr_c2f_interface::bort_c(), bvers(), chekstab(), cktaba(), closmg(), cmpbqm(), cmpmsg(), cmsgini(), cnved4(), codflg(), copybf(), copymg(), copysb(), cpdxmm(), cpymem(), cpyupd(), datebf(), datelen(), dumpbf(), dxdump(), dxmini(), getcfmng(), gettbh(), getwin(), idn30(), ifbget(), igetntbi(), igetrfel(), igetsc(), igettdi(), inctab(), invmrg(), ipkm(), isize(), iupm(), iupvs01(), jstnum(), lcmgdf(), lstjpb(), makestab(), minimg(), msgini(), msgwrt(), nemtba(), nemtbax(), nemtbb(), nemtbd(), nenubd(), nevn(), newwin(), nmsub(), nvnwin(), nxtwin(), openbf(), openmb(), openmg(), pad(), padmsg(), parutg(), pkb(), pkb8(), pkbs1(), pkvs01(), posapx(), rcstpl(), rdbfdx(), rdcmps(), rdmemm(), rdmems(), rdmgsb(), rdmtbb(), rdmtbd(), rdmtbf(), readdx(), readerme(), readlc(), readmg(), readns(), reads3(), readsb(), rewnbf(), rtrcpt(), sinv(), sntbbe(), sntbde(), split_by_subset(), status(), stbfdx(), stdmsg(), stndrd(), stntbia(), strbtm(), strcpt(), tabent(), tabsub(), ufbcnt(), ufbcpy(), ufbcup(), ufbdmp(), ufbevn(), ufbget(), ufbin3(), ufbint(), ufbinx(), ufbmem(), ufbmex(), ufbmms(), ufbmns(), ufbovr(), ufbpos(), ufbqcd(), ufbqcp(), ufbrep(), ufbrms(), ufbseq(), ufbstp(), ufbtab(), ufbtam(), ufdump(), upb8(), upds3(), upftbv(), uptdd(), usrtpl(), wrcmps(), wrdxtb(), writdx(), writlc(), writsa(), writsb(), and wtstat().
bort2()
subroutine bort2 (character*(*), intent(in) str1, character*(*), intent(in) str2)
Log two error messages, then abort the application program.
This subroutine is similar to subroutine bort(), except that bort() logs one error message instead of two.
Parameters
str1 - First error message
str2 - Second error message
Author
D. Keyser
Date
2003-11-04
Definition at line 38 of file borts.F90.
References errwrt().
Referenced by elemdx(), getntbe(), ireadmt(), mtfnam(), parstr(), parusr(), parutg(), rdusdx(), seqsdx(), sntbbe(), sntbde(), sntbfe(), string(), ufbint(), ufbovr(), ufbrep(), and ufbstp().