NCEPLIBS-bufr: cmpbqm.F90 File Reference
cmpbqm.F90 File Reference
Print inventory of observations from prepbufr file by variable, report type and quality mark.
Functions/Subroutines
program cmpbqm
Usage: cmpbqm <prepbufrfile> will print prep inventory by variable, report type, and qc mark.
Detailed Description
Print inventory of observations from prepbufr file by variable, report type and quality mark.
Author
J Woollen
Date
1997
Definition in file cmpbqm.F90.
Function/Subroutine Documentation
cmpbqm()
program cmpbqm
Usage: cmpbqm <prepbufrfile> will print prep inventory by variable, report type, and qc mark.
Returns
0 for success, error message otherwise.
Author
J Woollen
Date
1997
Definition at line 11 of file cmpbqm.F90.
References bort(), openbf(), readmg(), readsb(), ufbcnt(), and ufbint().