NCEPLIBS-bufr: cmsgini.f File Reference
cmsgini.f File Reference
Functions/Subroutines
subroutine cmsgini (LUN, MESG, SUBSET, IDATE, NSUB, NBYT)
THIS SUBROUTINE INITIALIZES A NEW BUFR MESSAGE FOR OUTPUT IN COMPRESSED BUFR.
Detailed Description
Author
WOOLLEN
Date
2002-05-14
Definition in file cmsgini.f.
Function/Subroutine Documentation
cmsgini()
subroutine cmsgini (LUN, dimension(*) MESG, character*8 SUBSET, IDATE, NSUB, NBYT)
THIS SUBROUTINE INITIALIZES A NEW BUFR MESSAGE FOR OUTPUT IN COMPRESSED BUFR.
THE ACTUAL LENGTH OF SECTION 4 (CONTAINING COMPRESSED DATA) IS ALREADY KNOWN.
PROGRAM HISTORY LOG: 2002-05-14 J. WOOLLEN – ORIGINAL AUTHOR 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY; LEN3 INITIALIZED AS ZERO (BEFORE WAS UNDEFINED WHEN FIRST REFERENCED) 2004-08-18 J. ATOR – ADDED COMMON /MSGSTD/ AND OTHER LOGIC TO ALLOW OPTION OF CREATING A SECTION 3 THAT IS FULLY WMO-STANDARD; IMPROVED DOCUMENTATION; MAXIMUM MESSAGE LENGTH INCREASED FROM 20,000 TO 50,000 BYTES 2005-11-29 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 12 2009-05-07 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 13; REMOVED STANDARDIZATION LOGIC FOR SECTION 3 2019-05-21 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 29 2021-05-14 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 36
USAGE: CALL CMSGINI (LUN, MESG, SUBSET, IDATE, NSUB, NBYT) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS SUBSET - CHARACTER*8: TABLE A MNEMONIC FOR TYPE OF BUFR MESSAGE BEING WRITTEN IDATE - INTEGER: DATE-TIME STORED WITHIN SECTION 1 OF BUFR MESSAGE BEING WRITTEN, IN FORMAT OF EITHER YYMMDDHH OR YYYYMMDDHH, DEPENDING ON DATELEN() VALUE NSUB - INTEGER: NUMBER OF SUBSETS, STORED IN SECTION 3 OF BUFR MESSAGE BEING WRITTEN NBYT - INTEGER: ACTUAL LENGTH (IN BYTES) OF "COMPRESSED DATA PORTION" OF SECTION 4 (I.E. ALL OF SECTION 4 EXCEPT FOR THE FIRST FOUR BYTES)
OUTPUT ARGUMENT LIST: MESG - INTEGER: *-WORD PACKED BINARY ARRAY CONTAINING BUFR MESSAGE NBYT - INTEGER: ACTUAL LENGTH OF BUFR MESSAGE (IN BYTES) UP TO THE POINT IN SECTION 4 WHERE COMPRESSED DATA ARE TO BE WRITTEN
REMARKS: THIS ROUTINE CALLS: BORT I4DY NEMTAB NEMTBA PKB PKC THIS ROUTINE IS CALLED BY: WRCMPS Normally not called by any application programs.
Definition at line 57 of file cmsgini.f.
References bort(), i4dy(), nemtab(), nemtba(), pkb(), and pkc().
Referenced by wrcmps().