NCEPLIBS-bufr: codflg.f File Reference
codflg.f File Reference
Specify inclusion of code and flag tables when reading master BUFR tables.
Functions/Subroutines
subroutine codflg (CF)
This subroutine is used to specify whether or not code and flag table information should be included during all future reads of master BUFR tables.
Detailed Description
Specify inclusion of code and flag tables when reading master BUFR tables.
Definition in file codflg.f.
Function/Subroutine Documentation
subroutine codflg (character*1 CF)
This subroutine is used to specify whether or not code and flag table information should be included during all future reads of master BUFR tables.
Author
J. Ator
Date
2017-10-13
Parameters
[in] CF - character*1: Flag indicating whether or not to include code and flag table information during all future reads of master BUFR tables
'N' = No (the default)
'Y' = Yes
See Master BUFR Tables for more information about master BUFR tables. In particlar, note that Table B and Table D files are always read whenever master BUFR tables are being used, but the reading of Code/Flag table files is optional and should only be included if the user intends to make one or more future calls to subroutine getcfmng(); otherwise, the reading of Code/Flag table files will result in the unnecessary use of memory and other system resources.
If Code/Flag tables are to be read and used, they must reside in the same directory as the master Table B and Table D files on the local filesystem, as specified within a separate call to subroutine mtinfo().
This subroutine can be called at any time after the first call to subroutine openbf(), and the specified value for CF will remain in effect for all future reads of master BUFR tables, unless a subsequent call is made to this subroutine to reset the value of CF again. If this subroutine is never called, a default value of 'N' is used for CF, as set within subroutine bfrini().
Program history log:
2017-10-13 J. Ator – Original author
Definition at line 43 of file codflg.f.
References bort(), and capit().
Referenced by fdebufr().