NCEPLIBS-bufr: cpbfdx.f File Reference
cpbfdx.f File Reference
Copy DX BUFR table information within internal memory.
Functions/Subroutines
subroutine cpbfdx (LUD, LUN)
This subroutine copies all of the DX BUFR table information from one unit to another within internal memory.
Detailed Description
Copy DX BUFR table information within internal memory.
Author
Woollen
Date
1994-01-06
Definition in file cpbfdx.f.
Function/Subroutine Documentation
cpbfdx()
subroutine cpbfdx (LUD, LUN)
This subroutine copies all of the DX BUFR table information from one unit to another within internal memory.
Parameters
[in] LUD - integer: I/O stream index into internal memory arrays for input unit.
[in] LUN - integer: I/O stream index into internal memory arrays for output unit.
Author
Woollen
Date
1994-01-06
Definition at line 16 of file cpbfdx.f.
References dxinit(), moda_tababd::idna, moda_tababd::idnb, moda_tababd::idnd, moda_msgcwd::inode, moda_tababd::mtab, moda_tababd::ntba, moda_tababd::ntbb, moda_tababd::ntbd, moda_tababd::taba, moda_tababd::tabb, and moda_tababd::tabd.
Referenced by makestab(), readdx(), and wrdxtb().