NCEPLIBS-bufr: cpdxmm.f File Reference
cpdxmm.f File Reference
Read embedded DX BUFR table into internal arrays.
Functions/Subroutines
subroutine cpdxmm (LUNIT)
This subroutine reads an entire DX BUFR table from a specified file into internal arrays.
Detailed Description
Read embedded DX BUFR table into internal arrays.
Definition in file cpdxmm.f.
Function/Subroutine Documentation
cpdxmm()
subroutine cpdxmm (LUNIT)
This subroutine reads an entire DX BUFR table from a specified file into internal arrays.
Author
J. Ator
Date
2009-03-23
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
Program history log:
Date Programmer Comments
2009-03-23 J. Ator Original author
2012-09-15 J. Woollen Modified for C/I/O/BUFR interface; replace Fortran BACKSPACE with C backbufr()
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 20 of file cpdxmm.f.
References backbufr(), bort(), errwrt(), moda_msgmem::icdxts, idxmsg(), moda_msgmem::ifdxts, moda_msgmem::ipdxm, moda_msgmem::ipmsgs, iupbs3(), moda_msgmem::ldxm, moda_msgmem::mdx, moda_msgmem::msgp, modv_mxdxts::mxdxts, moda_msgmem::ndxm, moda_msgmem::ndxts, nmwrd(), rdmsgw(), and status().
Referenced by ufbmem().