NCEPLIBS-bufr: dxdump.f File Reference
dxdump.f File Reference
Print the contents of a DX BUFR table.
Functions/Subroutines
subroutine dxdump (LUNIT, LDXOT)
This subroutine prints a copy of the DX BUFR table associated with a specified Fortran logical unit.
Detailed Description
Print the contents of a DX BUFR table.
Definition in file dxdump.f.
Function/Subroutine Documentation
dxdump()
subroutine dxdump (LUNIT, LDXOT)
This subroutine prints a copy of the DX BUFR table associated with a specified Fortran logical unit.
This subroutine is especially useful for learning the structure of existing BUFR files which contain DX BUFR table information embedded as BUFR messages within those files. The DX BUFR table is printed using the same ASCII format described in the documentation for DX BUFR Tables, so the output file is suitable for use as Fortran logical unit LUNDX in subsequent calls to subroutine openbf() for reading or writing additional BUFR files with the same structure.
Author
J. Ator
Date
2004-08-18
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
[in] LDXOT – integer: Fortran logical unit number for print output
Logical unit LUNIT must be open for either input or output operations via a previous call to subroutine openbf(). Logical unit LDXOT must already be associated with a filename on the local system, typically via a Fortran "OPEN" statement.
Remarks
This subroutine only prints the DX BUFR table that is currently in scope for logical unit LUNIT. Therefore, if logical unit LUNIT contains multiple embedded DX BUFR tables, then multiple calls to this subroutine must be made to print out all of the tables, once while each table is in scope for a data subset defined within that particular table.
Program history log:
Date Programmer Comments
2004-08-18 J. Ator Original author
2007-01-19 J. Ator Corrected output for reference values longer than 8 digits
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 45 of file dxdump.f.
References bort(), nemtbd(), moda_tababd::ntba, moda_tababd::ntbb, moda_tababd::ntbd, status(), strsuc(), moda_tababd::taba, moda_tababd::tabb, and moda_tababd::tabd.
Referenced by fdebufr().