NCEPLIBS-bufr: elemdx.f File Reference
elemdx.f File Reference
Functions/Subroutines
subroutine elemdx (CARD, LUN)
THIS SUBROUTINE DECODES THE SCALE FACTOR, REFERENCE VALUE, BIT WIDTH AND UNITS (I.E., THE "ELEMENTS") FROM A TABLE B MNEMONIC DEFINITION CARD THAT WAS PREVIOUSLY READ FROM A USER-SUPPLIED BUFR DICTIONARY TABLE FILE IN CHARACTER FORMAT BY BUFR ARCHIVE LIBRARY SUBROUTINE RDUSDX.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file elemdx.f.
Function/Subroutine Documentation
elemdx()
subroutine elemdx (character*80 CARD, LUN)
THIS SUBROUTINE DECODES THE SCALE FACTOR, REFERENCE VALUE, BIT WIDTH AND UNITS (I.E., THE "ELEMENTS") FROM A TABLE B MNEMONIC DEFINITION CARD THAT WAS PREVIOUSLY READ FROM A USER-SUPPLIED BUFR DICTIONARY TABLE FILE IN CHARACTER FORMAT BY BUFR ARCHIVE LIBRARY SUBROUTINE RDUSDX.
THESE DECODED VALUES ARE THEN ADDED TO THE ALREADY-EXISTING ENTRY FOR THAT MNEMONIC WITHIN THE INTERNAL BUFR TABLE B ARRAY TABB(*,LUN) IN MODULE TABABD.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1995-06-28 J. WOOLLEN – INCREASED THE SIZE OF INTERNAL BUFR TABLE ARRAYS IN ORDER TO HANDLE BIGGER FILES 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION; OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY; CHANGED CALL FROM BORT TO BORT2 2007-01-19 J. ATOR – ADDED EXTRA ARGUMENT FOR CALL TO JSTCHR 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
2021-09-30 J. Ator – Replace jstchr with Fortran intrinsic adjustl
USAGE: CALL ELEMDX (CARD, LUN) INPUT ARGUMENT LIST: CARD - CHARACTER*80: MNEMONIC DEFINITION CARD THAT WAS READ FROM A USER-SUPPLIED BUFR DICTIONARY TABLE LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
REMARKS: THIS ROUTINE CALLS: BORT2 CAPIT JSTNUM NEMTAB THIS ROUTINE IS CALLED BY: RDUSDX STSEQ Normally not called by any application programs.
Definition at line 47 of file elemdx.f.
References bort2(), capit(), jstnum(), nemtab(), and moda_tababd::tabb.
Referenced by rdusdx().