NCEPLIBS-bufr: errwrt.f File Reference
errwrt.f File Reference
Specify location for logging of error and diagnostic messages.
Functions/Subroutines
subroutine errwrt (STR)
This subroutine allows the user to specify a custom location for the logging of error and diagnostic messages generated by the BUFRLIB software.
Detailed Description
Specify location for logging of error and diagnostic messages.
Definition in file errwrt.f.
Function/Subroutine Documentation
subroutine errwrt (character*(*) STR)
This subroutine allows the user to specify a custom location for the logging of error and diagnostic messages generated by the BUFRLIB software.
By default, all such messages are printed to standard output. However, if a user would like to direct such messages elsewhere, this can be done by providing an inline version of this subroutine, using the same calling sequence shown below, in order to override the default version of this subroutine contained within the BUFRLIB distribution package. The user does not need to explicitly call this subroutine from within the application code, since the BUFRLIB software automatically issues an internal call to errwrt when needed. Instead, the user simply needs to define his or her own version of this subroutine with the same name and calling sequence and include it within the compilation, and then the input string STR can be logged or handled in any way of the user's choosing.
Author
J. Ator
Date
2009-04-21
Parameters
[in] STR - character*(*): Error message or other diagnostic to be printed to standard output (default) or to another location (if specified via an inline replacement version of this subroutine)
Remarks
The amount and types of diagnostic messages generated for logging can be controlled via a separate call to subroutine openbf() with IO = 'QUIET'.
Program history log:
2009-04-21 J. Ator – Original author
2012-11-15 D. Keyser – Use formatted print
Definition at line 39 of file errwrt.f.
Referenced by arallocf(), bort(), bort2(), cktaba(), closbf(), cpdxmm(), cpyupd(), datebf(), dumpbf(), hold4wlc(), igetprm(), invcon(), invtag(), invwin(), ireadmt(), isetprm(), jstnum(), makestab(), maxout(), mrginv(), msgupd(), msgwrt(), mtfnam(), nvnwin(), openbf(), openbt(), pktdd(), rcstpl(), rdbfdx(), rdmemm(), rdmems(), rdmsgw(), readdx(), readerme(), readlc(), readmg(), reads3(), strnum(), strsuc(), ufbevn(), ufbin3(), ufbint(), ufbmem(), ufbmex(), ufbovr(), ufbrep(), ufbrms(), ufbrw(), ufbseq(), ufbstp(), ufbtab(), ufbtam(), usrtpl(), valx(), wrdlen(), and writlc().