NCEPLIBS-bufr: errwrt.F90 File Reference
errwrt.F90 File Reference
Specify location for logging of error and diagnostic messages.
Functions/Subroutines
subroutine errwrt (str)
Specify a custom location for the logging of error and diagnostic messages generated by the NCEPLIBS-bufr software.
Detailed Description
Specify location for logging of error and diagnostic messages.
Author
J. Ator
Date
2009-04-21
Definition in file errwrt.F90.
Function/Subroutine Documentation
errwrt()
subroutine errwrt (character*(*), intent(in) str)
Specify a custom location for the logging of error and diagnostic messages generated by the NCEPLIBS-bufr software.
By default, all such messages are printed to standard output. However, if a user would like to direct such messages elsewhere, this can be done by providing an inline version of this subroutine, using the same calling sequence shown below, in order to override the default version of this subroutine contained within the NCEPLIBS-bufr distribution package. The user does not need to explicitly call this subroutine from within the application code, since the NCEPLIBS-bufr software automatically issues an internal call to errwrt when needed. Instead, the user simply needs to define his or her own version of this subroutine with the same name and calling sequence and include it within the compilation, and then the input string str can be logged or handled in any way of the user's choosing.
Parameters
str - Error message or other diagnostic to be printed to standard output (default) or to another location (if specified via an inline replacement version of this subroutine)
Remarks
The amount and types of diagnostic messages generated for logging can be controlled via a separate call to subroutine openbf() with io = 'QUIET'.
Author
J. Ator
Date
2009-04-21
Definition at line 31 of file errwrt.F90.
Referenced by arallocf(), bort(), bort2(), cktaba(), closbf(), cpdxmm(), cpyupd(), datebf(), dumpbf(), hold4wlc(), igetprm(), invcon(), invtag(), invwin(), ireadmt(), isetprm(), jstnum(), makestab(), maxout(), mrginv(), msgupd(), msgwrt(), mtfnam(), nvnwin(), openbf(), openbt(), pktdd(), rcstpl(), rdbfdx(), rdmemm(), rdmems(), rdmsgw(), readdx(), readerme(), readlc(), readmg(), reads3(), status(), ufbevn(), ufbin3(), ufbint(), ufbmem(), ufbmex(), ufbovr(), ufbrep(), ufbrms(), ufbrw(), ufbseq(), ufbstp(), ufbtab(), ufbtam(), usrtpl(), and writlc().