NCEPLIBS-bufr: exitbufr.f File Reference
exitbufr.f File Reference
Reset the BUFRLIB software for potential dynamic reallocation of memory.
Functions/Subroutines
subroutine exitbufr
This subroutine frees all dynamically-allocated memory, closes all logical units that are open within the BUFRLIB software, and resets the library to all of its default settings as though it had never been called.
Detailed Description
Reset the BUFRLIB software for potential dynamic reallocation of memory.
Definition in file exitbufr.f.
Function/Subroutine Documentation
exitbufr()
subroutine exitbufr
This subroutine frees all dynamically-allocated memory, closes all logical units that are open within the BUFRLIB software, and resets the library to all of its default settings as though it had never been called.
Author
J. Ator
Date
2015-03-02
Remarks
Calling this subroutine allows an application program to potentially resize arrays and reallocate memory all over again with a new subsequent series of calls to subroutines isetprm() and openbf(). However, if and when this subroutine is called, there is no longer any internal memory available within the BUFRLIB software, and the remainder of the library becomes essentially unusable within the application program, unless and until subroutine openbf() is called once again to dynamically allocate new array space. This may be a useful capability for application programs that are finished with using the BUFRLIB software and wish to move on to other unrelated tasks without continuing to tie up all of the allocated memory space within the library. Otherwise, and unless there's a need to change parameter sizes following the first call to subroutine openbf(), then there's no need to ever call this subroutine within an application program, since all allocated memory will automatically get freed anyway by the operating system once the application program terminates.
Program history log:
Date Programmer Comments
2015-03-02 J. Ator Original author
Definition at line 38 of file exitbufr.f.
References ardllocf(), closbf(), dlloctbf(), modv_ifopbf::ifopbf, and modv_nfiles::nfiles.
Referenced by bufr_c_interface_mod::exitbufr_c().