NCEPLIBS-bufr: gettab.F90 File Reference
gettab.F90 File Reference
Read BUFR file containing embedded DX BUFR tables, and print the tables to stdout.
Functions/Subroutines
program gettab
Read BUFR file containing embedded DX BUFR tables, and print the tables to stdout.
Detailed Description
Read BUFR file containing embedded DX BUFR tables, and print the tables to stdout.
Author
Woollen
Date
2000-01-01
Definition in file gettab.F90.
Function/Subroutine Documentation
gettab()
program gettab
Read BUFR file containing embedded DX BUFR tables, and print the tables to stdout.
Returns
0 for success, error code otherwise.
Author
Woollen
Date
2000-01-01
Definition at line 13 of file gettab.F90.
References closbf(), dxdump(), openbf(), and status().