NCEPLIBS-bufr: ibfms.f File Reference
ibfms.f File Reference
Test whether a real*8 data value is "missing".
Functions/Subroutines
INTEGER function ibfms (R8VAL)
This function provides a handy way to check whether a real*8 data value returned from a previous call to any of the other BUFRLIB values-reading subroutines contains the current placeholder value for "missing" data.
Detailed Description
Test whether a real*8 data value is "missing".
Definition in file ibfms.f.
Function/Subroutine Documentation
INTEGER function ibfms (real*8 R8VAL)
This function provides a handy way to check whether a real*8 data value returned from a previous call to any of the other BUFRLIB values-reading subroutines contains the current placeholder value for "missing" data.
Author
J. Ator
Date
2007-01-19
Parameters
[in] R8VAL - real*8: Data value to be tested
Returns
ibfms - integer:
0 = R8VAL is not "missing"
1 = R8VAL is "missing"
The current placeholder value for "missing" data is always equal to the value XMISS as specified during the most recent call to subroutine setbmiss(), or to a default value of 10E10 if setbmiss() was never called. In either case, a return value of 1 means that the corresponding value was encoded as "missing" (all bits set to 1) within the actual BUFR data subset.
Remarks
The use of an integer return code allows this function to be called in a logical context from application programs written in C as well as in Fortran.
Program history log:
2007-01-19 J. Ator – Original author
2009-03-23 J. Ator – Increased value of BDIFD for better test accuracy
2012-10-05 J. Ator – Modified to reflect the fact that the "missing" value is now configurable by users (may be something other than 10E10)
Definition at line 39 of file ibfms.f.
Referenced by invmrg(), strbtm(), ufbdmp(), ufbrw(), ufdump(), and wrtree().