NCEPLIBS-bufr: igetrfel.f File Reference
igetrfel.f File Reference
Functions/Subroutines
integer function igetrfel (N, LUN)
THIS FUNCTION CHECKS WHETHER THE INPUT ELEMENT REFERS TO A PREVIOUS ELEMENT WITHIN THE SAME SUBSET VIA AN INTERNAL BITMAP.
Detailed Description
Author
J
Date
2016-05-27
Definition in file igetrfel.f.
Function/Subroutine Documentation
igetrfel()
integer function igetrfel (N, LUN)
THIS FUNCTION CHECKS WHETHER THE INPUT ELEMENT REFERS TO A PREVIOUS ELEMENT WITHIN THE SAME SUBSET VIA AN INTERNAL BITMAP.
IF SO, THEN THE REFERENCED ELEMENT IS RETURNED. IN ADDITION, IF THE INPUT ELEMENT IS A 2-XX-255 MARKER OPERATOR, ITS SCALE FACTOR, BIT WIDTH AND REFERENCE VALUE ARE SET INTERNALLY TO MATCH THOSE OF THE REFERENCED ELEMENT.
PROGRAM HISTORY LOG: 2016-05-27 J. ATOR – ORIGINAL AUTHOR 2017-04-03 J. ATOR – ADD A DIMENSION TO ALL TCO ARRAYS SO THAT EACH SUBSET DEFINITION IN THE JUMP/LINK TABLE HAS ITS OWN SET OF TABLE C OPERATORS
USAGE: CALL IGETRFEL (N, LUN) INPUT ARGUMENT LIST: N - INTEGER: SUBSET ELEMENT LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
OUTPUT ARGUMENT LIST: IGETRFEL - INTEGER: SUBSET ELEMENT REFERENCED BY ELEMENT N WITHIN THE SAME SUBSET 0 = INPUT ELEMENT DOES NOT REFER TO A PREVIOUS ELEMENT, OR REFERENCED ELEMENT NOT FOUND
REMARKS: THIS ROUTINE CALLS: ADN30 BORT IBFMS IMRKOPR LSTJPB NEMTAB THIS ROUTINE IS CALLED BY: RCSTPL RDCMPS Normally not called by any application programs.
Definition at line 35 of file igetrfel.f.
References adn30(), bort(), moda_bitmaps::ctco, moda_tables::ibt, moda_bitmaps::ibtmse, moda_nrv203::ienrv, igetrfel(), imrkopr(), moda_nrv203::inodnrv, moda_bitmaps::inodtamc, moda_bitmaps::inodtco, moda_tables::irf, moda_tables::isc, moda_nrv203::isnrv, moda_bitmaps::istbtm, moda_bitmaps::iszbtm, moda_tables::itp, lstjpb(), moda_bitmaps::lstnod, moda_bitmaps::lstnodct, moda_bitmaps::nbtm, moda_bitmaps::nbtmse, nemtab(), moda_nrv203::nnrv, moda_nrv203::nrv, moda_bitmaps::ntamc, moda_bitmaps::ntco, moda_tables::tag, and moda_nrv203::tagnrv.
Referenced by igetrfel(), rcstpl(), and rdcmps().