NCEPLIBS-bufr: igetfxy.f File Reference
igetfxy.f File Reference
Functions/Subroutines
function igetfxy (STR, CFXY)
THIS FUNCTION LOOKS FOR AND RETURNS A VALID FXY NUMBER FROM WITHIN THE GIVEN INPUT STRING.
Detailed Description
Author
ATOR
Date
2007-01-19
Definition in file igetfxy.f.
Function/Subroutine Documentation
igetfxy()
function igetfxy (character*(*) STR, character*6 CFXY)
THIS FUNCTION LOOKS FOR AND RETURNS A VALID FXY NUMBER FROM WITHIN THE GIVEN INPUT STRING.
THE FXY NUMBER MAY BE IN FORMAT OF EITHER FXXYYY OR F-XX-YYY WITHIN THE INPUT STRING, BUT IT IS ALWAYS RETURNED IN FORMAT FXXYYY UPON OUTPUT.
PROGRAM HISTORY LOG: 2007-01-19 J. ATOR – ORIGINAL AUTHOR
2021-09-30 J. Ator – Replace jstchr with Fortran intrinsic adjustl
USAGE: IGETFXY (STR, CFXY) INPUT ARGUMENT LIST: STR - CHARACTER*(*): INPUT STRING
OUTPUT ARGUMENT LIST: CFXY - CHARACTER*6: FXY NUMBER IN FORMAT FXXYYY IGETFXY - INTEGER: RETURN CODE: 0 = normal return -1 = could not find a valid FXY number in STR
REMARKS: THIS ROUTINE CALLS: NUMBCK THIS ROUTINE IS CALLED BY: GETNTBE SNTBDE SNTBFE Normally not called by any application programs.
Definition at line 30 of file igetfxy.f.
References igetfxy(), and numbck().
Referenced by getntbe(), igetfxy(), sntbde(), and sntbfe().