NCEPLIBS-bufr: invtag.f File Reference
invtag.f File Reference
Functions/Subroutines
function invtag (NODE, LUN, INV1, INV2)
THIS FUNCTION LOOKS FOR A SPECIFIED MNEMONIC WITHIN THE PORTION OF THE CURRENT SUBSET BUFFER BOUNDED BY THE INDICES INV1 AND INV2.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file invtag.f.
Function/Subroutine Documentation
invtag()
function invtag (NODE, LUN, INV1, INV2)
THIS FUNCTION LOOKS FOR A SPECIFIED MNEMONIC WITHIN THE PORTION OF THE CURRENT SUBSET BUFFER BOUNDED BY THE INDICES INV1 AND INV2.
IT IS SIMILAR TO BUFR ARCHIVE LIBRARY FUNCTION INVWIN, EXCEPT THAT INVWIN SEARCHES BASED ON THE ACTUAL NODE WITHIN THE INTERNAL JUMP/LINK TABLE, RATHER THAN ON THE MNEMONIC CORRESPONDING TO THAT NODE.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN UNUSUAL THINGS HAPPEN 2009-03-31 J. WOOLLEN – ADDED DOCUMENTATION 2009-04-21 J. ATOR – USE ERRWRT 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: INVTAG (NODE, LUN, INV1, INV2) INPUT ARGUMENT LIST: NODE - INTEGER: JUMP/LINK TABLE INDEX OF MNEMONIC TO LOOK FOR LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS INV1 - INTEGER: STARTING INDEX OF THE PORTION OF THE SUBSET BUFFER IN WHICH TO LOOK INV2 - INTEGER: ENDING INDEX OF THE PORTION OF THE SUBSET BUFFER IN WHICH TO LOOK
OUTPUT ARGUMENT LIST: INVTAG - INTEGER: LOCATION INDEX OF NODE WITHIN SPECIFIED PORTION OF SUBSET BUFFER 0 = NOT FOUND
REMARKS: THIS ROUTINE CALLS: ERRWRT THIS ROUTINE IS CALLED BY: UFBRP UFBSEQ UFBSP Normally not called by any application programs.
Definition at line 49 of file invtag.f.
References errwrt(), invtag(), and moda_tables::tag.
Referenced by invtag(), ufbrp(), ufbseq(), and ufbsp().