NCEPLIBS-bufr: ireadsb.f File Reference
ireadsb.f File Reference
Read the next data subset from a BUFR message.
Functions/Subroutines
function ireadsb (LUNIT)
This function calls BUFRLIB subroutine readsb() and passes back its return code as the function value.
Detailed Description
Read the next data subset from a BUFR message.
Definition in file ireadsb.f.
Function/Subroutine Documentation
ireadsb()
function ireadsb (LUNIT)
This function calls BUFRLIB subroutine readsb() and passes back its return code as the function value.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
Returns
ireadsb – integer:
0 = new BUFR data subset was successfully read into internal arrays
-1 = there are no more BUFR data subsets in the BUFR message
Remarks
The use of this function allows the return code from readsb() to be used as the target variable within an iterative program loop.
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
2002-05-14 J. Woollen Changed from an entry point to increase portability to other platforms
2003-11-04 S. Bender Added remarks and routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added documentation
Definition at line 30 of file ireadsb.f.
References ireadsb(), and readsb().
Referenced by fdebufr(), ireadsb(), bufr_c_interface_mod::ireadsb_c(), and ufbtab().