NCEPLIBS-bufr: iupm.f File Reference
iupm.f File Reference
Functions/Subroutines
function iupm (CBAY, NBITS)
THIS FUNCTION UNPACKS AND RETURNS A BINARY INTEGER WORD CONTAINED WITHIN NBITS BITS OF A CHARACTER STRING CBAY, STARTING WITH THE FIRST BIT OF THE FIRST BYTE OF CBAY.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file iupm.f.
Function/Subroutine Documentation
function iupm (character*8 CBAY, NBITS)
THIS FUNCTION UNPACKS AND RETURNS A BINARY INTEGER WORD CONTAINED WITHIN NBITS BITS OF A CHARACTER STRING CBAY, STARTING WITH THE FIRST BIT OF THE FIRST BYTE OF CBAY.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 J. WOOLLEN – BIG-ENDIAN/LITTLE-ENDIAN INDEPENDENT (WAS IN DECODER VERSION) 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION; OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY
USAGE: IUPM (CBAY, NBITS) INPUT ARGUMENT LIST: CBAY - CHARACTER*8: CHARACTER STRING CONTAINING PACKED INTEGER NBITS - INTEGER: NUMBER OF BITS WITHIN CBAY TO BE UNPACKED
OUTPUT ARGUMENT LIST: IUPM - INTEGER: UNPACKED INTEGER WORD
REMARKS: THIS ROUTINE CALLS: BORT IREV THIS ROUTINE IS CALLED BY: CHRTRNA CRBMG DXMINI ICBFMS PKC PKTDD UPC UPTDD WRDLEN WRDXTB Normally not called by any application programs.
Definition at line 40 of file iupm.f.
References bort(), and irev().
Referenced by chrtrna(), crbmg(), dxmini(), icbfms(), pkc(), pktdd(), upc(), uptdd(), wrdlen(), and wrdxtb().