NCEPLIBS-bufr: lcmgdf.f File Reference
lcmgdf.f File Reference
Check for the existence of any long character strings (greater than 8 bytes) within a data subset definition.
Functions/Subroutines
integer function lcmgdf (LUNIT, SUBSET)
This function checks whether the subset definition for a given message type contains any long character strings (greater than 8 bytes).
Detailed Description
Check for the existence of any long character strings (greater than 8 bytes) within a data subset definition.
Definition in file lcmgdf.f.
Function/Subroutine Documentation
lcmgdf()
integer function lcmgdf (LUNIT, character*8 SUBSET)
This function checks whether the subset definition for a given message type contains any long character strings (greater than 8 bytes).
Author
J. Ator
Date
2009-07-09
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
[in] SUBSET – character*8: Table A mnemonic of message type to be checked
Returns
lcmgdf – integer:
0 = SUBSET does not contain any long character strings
1 = SUBSET contains at least one long character string
Remarks
LUNIT may be open for either input or output operations via a previous call to subroutine openbf(). However, in either case, SUBSET must already be defined within the BUFR tables that are associated with LUNIT, typically as DX BUFR tables information supplied via argument LUNDX when openbf() was called, or, if openbf() was called with IO = 'SEC3', then as master BUFR table information during a previous call to one of the message-reading subroutines.
Note that this function does not return mnemonic(s) associated with any long character string(s) found within SUBSET; rather, it only checks whether at least one such mnemonic exists. If any are found, the application program can process them via a separate call to subroutine readlc() (when reading BUFR data subsets) or subroutine writlc() (when writing BUFR data subsets).
Program history log:
Date Programmer Comments
2009-07-09 J. Ator Original author
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 44 of file lcmgdf.f.
References bort(), moda_tables::ibt, moda_tables::isc, lcmgdf(), nemtba(), status(), and moda_tables::typ.
Referenced by lcmgdf().