NCEPLIBS-bufr: msgini.f File Reference
msgini.f File Reference
Functions/Subroutines
subroutine msgini (LUN)
THIS SUBROUTINE INITIALIZES, WITHIN THE INTERNAL ARRAYS, A NEW BUFR MESSAGE FOR OUTPUT.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file msgini.f.
Function/Subroutine Documentation
msgini()
subroutine msgini (LUN)
THIS SUBROUTINE INITIALIZES, WITHIN THE INTERNAL ARRAYS, A NEW BUFR MESSAGE FOR OUTPUT.
ARRAYS ARE FILLED IN COMMON BLOCKS /MSGPTR/ AND MODULES MSGCWD AND BITBUF.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1996-12-11 J. WOOLLEN – MODIFIED TO ALLOW INCLUSION OF MINUTES IN WRITING THE MESSAGE DATE INTO A BUFR MESSAGE 1997-07-29 J. WOOLLEN – MODIFIED TO UPDATE THE CURRENT BUFR VERSION WRITTEN IN SECTION 0 FROM 2 TO 3 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT"; MODIFIED TO MAKE Y2K COMPLIANT 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2000-09-19 J. WOOLLEN – MAXIMUM MESSAGE LENGTH INCREASED FROM 10,000 TO 20,000 BYTES 2002-05-14 J. WOOLLEN – REMOVED ENTRY POINT MINIMG (IT BECAME A SEPARATE ROUTINE IN THE BUFRLIB TO INCREASE PORTABILITY TO OTHER PLATFORMS) 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION; OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2004-08-09 J. ATOR – MAXIMUM MESSAGE LENGTH INCREASED FROM 20,000 TO 50,000 BYTES 2005-11-29 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 12 2009-05-07 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 13 2009-08-11 J. WOOLLEN – ADD COMMON UFBCPL TO INITIALIZE LUNCPY 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS 2019-05-21 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 29 2021-05-14 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 36
USAGE: CALL MSGINI (LUN) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
REMARKS: THIS ROUTINE CALLS: BORT NEMTAB NEMTBA PKB PKC THIS ROUTINE IS CALLED BY: CPYUPD MSGUPD OPENMB OPENMG Normally not called by any application programs.
Definition at line 57 of file msgini.f.
References bort(), moda_bitbuf::mbay, moda_bitbuf::mbyt, nemtab(), nemtba(), pkb(), pkc(), and moda_tables::tag.
Referenced by cpyupd(), msgupd(), openmb(), and openmg().