NCEPLIBS-bufr: mtfnam.f File Reference
mtfnam.f File Reference
Determine filenames and check for the existence of corresponding standard and local master table files on the filesystem.
Functions/Subroutines
subroutine mtfnam (IMT, IMTV, IOGCE, IMTVL, TBLTYP, STDFIL, LOCFIL)
Based on the input arguments, this subroutine determines the names of the corresponding standard and local master table files.
Detailed Description
Determine filenames and check for the existence of corresponding standard and local master table files on the filesystem.
Author
Ator
Date
2017-10-16
Definition in file mtfnam.f.
Function/Subroutine Documentation
mtfnam()
subroutine mtfnam (IMT, IMTV, IOGCE, IMTVL, character*(*) TBLTYP, character*(*) STDFIL, character*(*) LOCFIL)
Based on the input arguments, this subroutine determines the names of the corresponding standard and local master table files.
It then confirms the existence of these files on the filesystem, using additional information obtained from the most recent call to subroutine mtinfo(), or else as defined within subroutine bfrini() if subroutine mtinfo() was never called.
Parameters
[in] IMT - integer: master table number.
[in] IMTV - integer: master table version number.
[in] IOGCE - integer: originating center.
[in] IMTVL - integer: local table version number.
[in] TBLTYP - character*(*): table type:.
'TableB' Table B
'TableD' Table D
'CodeFlag' Code and Flag Tables
[out] STDFIL - character*(*): standard master table path/filename.
[out] LOCFIL - character*(*): local master table path/filename.
Author
Ator
Date
2017-10-16
Definition at line 26 of file mtfnam.f.
References bort2(), errwrt(), isize(), and strsuc().
Referenced by ireadmt().