NCEPLIBS-bufr: mvb.f File Reference
mvb.f File Reference
Functions/Subroutines
subroutine mvb (IB1, NB1, IB2, NB2, NBM)
THIS SUBROUTINE COPIES A SPECIFIED NUMBER OF BYTES FROM ONE PACKED BINARY ARRAY TO ANOTHER.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file mvb.f.
Function/Subroutine Documentation
mvb()
subroutine mvb (dimension(*) IB1, NB1, dimension(*) IB2, NB2, NBM)
THIS SUBROUTINE COPIES A SPECIFIED NUMBER OF BYTES FROM ONE PACKED BINARY ARRAY TO ANOTHER.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1998-10-27 J. WOOLLEN – MODIFIED TO CORRECT PROBLEMS CAUSED BY IN- LINING CODE WITH FPP DIRECTIVES 2002-05-14 J. WOOLLEN – REMOVED OLD CRAY COMPILER DIRECTIVES 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2005-11-29 J. ATOR – MAXIMUM NUMBER OF BYTES TO COPY INCREASED FROM 24000 TO MXIMB 2014-10-22 J. ATOR – MERGE TWO DO LOOPS INTO ONE, AND REMOVE MXIMB PARAMETER AND DIMENSIONING OF NVAL
USAGE: CALL MVB (IB1, NB1, IB2, NB2, NBM) INPUT ARGUMENT LIST: IB1 - INTEGER: *-WORD PACKED INPUT BINARY ARRAY NB1 - INTEGER: POINTER TO FIRST BYTE IN IB1 TO COPY FROM NB2 - INTEGER: POINTER TO FIRST BYTE IN IB2 TO COPY TO NBM - INTEGER: NUMBER OF BYTES TO COPY
OUTPUT ARGUMENT LIST: IB2 - INTEGER: *-WORD PACKED OUTPUT BINARY ARRAY
REMARKS: THIS ROUTINE CALLS: PKB UPB THIS ROUTINE IS CALLED BY: ATRCPT CNVED4 CPYUPD MSGUPD STNDRD Normally not called by any application programs.
Definition at line 43 of file mvb.f.
References pkb(), and upb().
Referenced by atrcpt(), cnved4(), cpyupd(), msgupd(), and stndrd().