NCEPLIBS-bufr: moda_sc3bfr Module Reference
moda_sc3bfr Module Reference
This module contains an array declaration used to store a switch for each internal I/O stream index, indicating whether BUFR messages read from the corresponding logical unit should be decoded according to the contents of Section 3 and using master BUFR tables, rather than using DX BUFR tables.
Variables
integer, dimension(:), allocatable isc3
Section 3 switch for each internal I/O stream index:
character *8, dimension(:), allocatable tamnem
Table A mnemonic most recently read from each internal I/O stream index, if isc3 = 1 for that stream.
Detailed Description
This module contains an array declaration used to store a switch for each internal I/O stream index, indicating whether BUFR messages read from the corresponding logical unit should be decoded according to the contents of Section 3 and using master BUFR tables, rather than using DX BUFR tables.
The default value is "off", indicating that BUFR messages read from the corresponding logical unit should be decoded using DX BUFR tables, but it can be switched to a value of "on" if the corresponding logical unit is connected to the library via a call to subroutine openbf() with IO = 'SEC3', and in which case each BUFR message will be decoded according to the contents of Section 3 and using master BUFR tables.
Author
J. Ator
Date
2009-03-23
Variable Documentation
isc3
integer, dimension(:), allocatable moda_sc3bfr::isc3
Section 3 switch for each internal I/O stream index:
0 BUFR messages read from corresponding logical unit will be decoded using DX BUFR tables (default)
1 BUFR messages read from corresponding logical unit will be decoded using master BUFR tables
Definition at line 584 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), ireadmt(), openbf(), readerme(), and readmg().
tamnem
character*8, dimension(:), allocatable moda_sc3bfr::tamnem
Table A mnemonic most recently read from each internal I/O stream index, if isc3 = 1 for that stream.
Definition at line 587 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), and reads3().