NCEPLIBS-bufr: moda_ufbcpl Module Reference
moda_ufbcpl Module Reference
Declare an array used to store, for each file ID, the logical unit number corresponding to a separate file ID whenever BUFR data subsets are being copied from the latter to the former via subroutine ufbcpy().
Variables
integer, dimension(:), allocatable luncpy
Logical unit numbers used to copy long character strings between BUFR data subsets.
Detailed Description
Declare an array used to store, for each file ID, the logical unit number corresponding to a separate file ID whenever BUFR data subsets are being copied from the latter to the former via subroutine ufbcpy().
In such cases, this stored logical unit number is later accessed within subroutine wrtree() to enable the copying of long character strings (greater than 8 bytes) between the two logical units.
Author
J. Woollen
Date
2009-08-11
Variable Documentation
luncpy
integer, dimension(:), allocatable moda_ufbcpl::luncpy
Logical unit numbers used to copy long character strings between BUFR data subsets.
Definition at line 757 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), msgini(), ufbcpy(), and wrtree().