NCEPLIBS-bufr: moda_usrbit Module Reference
moda_usrbit Module Reference
This module contains array declarations for internal storage of pointers to BUFR data subset values.
Variables
integer, dimension(:), allocatable mbit
Pointer in data subset to first bit of each packed data value.
integer, dimension(:), allocatable nbit
Length (in bits) of each packed data value in data subset.
Detailed Description
This module contains array declarations for internal storage of pointers to BUFR data subset values.
They are used when unpacking an input data subset via subroutines rcstpl() and rdtree().
Author
J. Woollen
Date
1994-01-06
Variable Documentation
mbit
integer, dimension(:), allocatable moda_usrbit::mbit
Pointer in data subset to first bit of each packed data value.
Definition at line 783 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), rcstpl(), rdtree(), readlc(), and ufbget().
nbit
integer, dimension(:), allocatable moda_usrbit::nbit
Length (in bits) of each packed data value in data subset.
Definition at line 781 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), rcstpl(), rdtree(), readlc(), and ufbget().