NCEPLIBS-bufr: moda_h4wlc Module Reference
moda_h4wlc Module Reference
This module contains array and variable declarations needed to store long character strings (greater than 8 bytes) via subroutine hold4wlc().
Variables
character *120, dimension(:), allocatable chh4wlc
Long character strings.
integer, dimension(:), allocatable luh4wlc
I/O stream index into internal arrays for associated output file.
integer nh4wlc
Number of long character strings being stored.
character *14, dimension(:), allocatable sth4wlc
Table B mnemonics associated with long character strings.
Detailed Description
This module contains array and variable declarations needed to store long character strings (greater than 8 bytes) via subroutine hold4wlc().
These strings can be held for writing into an uncompressed BUFR data subset via future internal calls to subroutine writlc().
Author
J. Ator
Date
2014-02-05
Variable Documentation
chh4wlc
character*120, dimension(:), allocatable moda_h4wlc::chh4wlc
Long character strings.
Definition at line 232 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), hold4wlc(), and msgupd().
luh4wlc
integer, dimension(:), allocatable moda_h4wlc::luh4wlc
I/O stream index into internal arrays for associated output file.
Definition at line 228 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), hold4wlc(), and msgupd().
nh4wlc
integer moda_h4wlc::nh4wlc
Number of long character strings being stored.
Definition at line 226 of file modules_arrs.F90.
Referenced by bfrini(), hold4wlc(), and msgupd().
sth4wlc
character*14, dimension(:), allocatable moda_h4wlc::sth4wlc
Table B mnemonics associated with long character strings.
Definition at line 230 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), hold4wlc(), and msgupd().