NCEPLIBS-bufr: moda_mgwa Module Reference
moda_mgwa Module Reference
This module contains a declaration for an array used by various subroutines and functions to hold a temporary working copy of a BUFR message.
Variables
integer, dimension(:), allocatable mgwa
Temporary working copy of BUFR message.
Detailed Description
This module contains a declaration for an array used by various subroutines and functions to hold a temporary working copy of a BUFR message.
Author
J. Woollen
Date
1994-01-06
Variable Documentation
mgwa
integer, dimension(:), allocatable moda_mgwa::mgwa
Temporary working copy of BUFR message.
Definition at line 296 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), copybf(), cpdxmm(), datebf(), dumpbf(), mesgbc(), mesgbf(), msgwrt(), posapx(), rdbfdx(), rdmemm(), ufbmem(), ufbmex(), wrcmps(), and wrdxtb().