NCEPLIBS-bufr: moda_ival Module Reference
moda_ival Module Reference
This module contains a declaration for an array used to pack or unpack all of the values of a BUFR data subset.
Variables
integer(8), dimension(:), allocatable ival
BUFR data subset values.
Detailed Description
This module contains a declaration for an array used to pack or unpack all of the values of a BUFR data subset.
It is used when packing a data subset for output via subroutine wrtree(), or when unpacking an input data subset via subroutine rdtree().
Author
J. Woollen
Date
1994-01-06
Variable Documentation
ival
integer(8), dimension(:), allocatable moda_ival::ival
BUFR data subset values.
Definition at line 257 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), rdtree(), strtbfe(), and wrtree().