NCEPLIBS-bufr: moda_tababd Module Reference
moda_tababd Module Reference
This module contains array and variable declarations used to store DX BUFR tables internally for multiple I/O streams.
Variables
integer, dimension(:,:,:), allocatable idna
Message types (in array element 1) and subtypes (in array element 2) corresponding to taba.
integer, dimension(:,:), allocatable idnb
Bit-wise representations of the FXY values corresponding to tabb.
integer, dimension(:,:), allocatable idnd
Bit-wise representations of the FXY values corresponding to tabd.
integer, dimension(:,:), allocatable mtab
Entries within jump/link table corresponding to taba.
integer, dimension(:), allocatable ntba
Number of Table A entries for each internal I/O stream (up to a maximum of MAXTBA, whose value is stored in array element 0).
integer, dimension(:), allocatable ntbb
Number of Table B entries for each internal I/O stream (up to a maximum of MAXTBB, whose value is stored in array element 0).
integer, dimension(:), allocatable ntbd
Number of Table D entries for each internal I/O stream (up to a maximum of MAXTBD, whose value is stored in array element 0).
character *128, dimension(:,:), allocatable taba
Table A entries for each internal I/O stream.
character *128, dimension(:,:), allocatable tabb
Table B entries for each internal I/O stream.
character *600, dimension(:,:), allocatable tabd
Table D entries for each internal I/O stream.
Detailed Description
This module contains array and variable declarations used to store DX BUFR tables internally for multiple I/O streams.
Author
J. Ator
Date
2014-12-10
Variable Documentation
idna
integer, dimension(:,:,:), allocatable moda_tababd::idna
Message types (in array element 1) and subtypes (in array element 2) corresponding to taba.
Definition at line 642 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpbfdx(), icmpdx(), nemtbax(), and stntbia().
idnb
integer, dimension(:,:), allocatable moda_tababd::idnb
Bit-wise representations of the FXY values corresponding to tabb.
Definition at line 644 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpbfdx(), dxinit(), icmpdx(), nemtab(), nemtbb(), numtbd(), stbfdx(), and stntbi().
idnd
integer, dimension(:,:), allocatable moda_tababd::idnd
Bit-wise representations of the FXY values corresponding to tabd.
Definition at line 646 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpbfdx(), dxinit(), icmpdx(), nemtab(), nemtbd(), numtbd(), stbfdx(), and stntbi().
mtab
integer, dimension(:,:), allocatable moda_tababd::mtab
Entries within jump/link table corresponding to taba.
Definition at line 639 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpbfdx(), dxinit(), ishrdx(), makestab(), and nemtbax().
ntba
integer, dimension(:), allocatable moda_tababd::ntba
Number of Table A entries for each internal I/O stream (up to a maximum of MAXTBA, whose value is stored in array element 0).
Definition at line 631 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bfrini(), chekstab(), cpbfdx(), dxdump(), dxinit(), icmpdx(), igetntbi(), ishrdx(), makestab(), nemtbax(), stntbia(), and wrdxtb().
ntbb
integer, dimension(:), allocatable moda_tababd::ntbb
Number of Table B entries for each internal I/O stream (up to a maximum of MAXTBB, whose value is stored in array element 0).
Definition at line 634 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bfrini(), chekstab(), cpbfdx(), dxdump(), dxinit(), getabdb(), icmpdx(), igetntbi(), nemtab(), nemtbb(), nenubd(), numtbd(), stbfdx(), stntbi(), and wrdxtb().
ntbd
integer, dimension(:), allocatable moda_tababd::ntbd
Number of Table D entries for each internal I/O stream (up to a maximum of MAXTBD, whose value is stored in array element 0).
Definition at line 637 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bfrini(), chekstab(), cpbfdx(), dxdump(), dxinit(), getabdb(), icmpdx(), igetntbi(), nemtab(), nemtbd(), nenubd(), numtbd(), stbfdx(), stntbi(), and wrdxtb().
taba
character*128, dimension(:,:), allocatable moda_tababd::taba
Table A entries for each internal I/O stream.
Definition at line 648 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), chekstab(), cpbfdx(), dxdump(), dxinit(), icmpdx(), makestab(), nemtbax(), stbfdx(), stntbia(), and wrdxtb().
tabb
character*128, dimension(:,:), allocatable moda_tababd::tabb
Table B entries for each internal I/O stream.
Definition at line 650 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpbfdx(), dxdump(), dxinit(), elemdx(), getabdb(), getcfmng(), icmpdx(), nemdefs(), nemtab(), nemtbb(), nenubd(), numtbd(), stbfdx(), stntbi(), ufbdmp(), ufdump(), upftbv(), and wrdxtb().
tabd
character*600, dimension(:,:), allocatable moda_tababd::tabd
Table D entries for each internal I/O stream.
Definition at line 652 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpbfdx(), dxdump(), dxinit(), getabdb(), icmpdx(), nemtab(), nemtbd(), nenubd(), numtbd(), pktdd(), stbfdx(), stntbi(), uptdd(), and wrdxtb().