NCEPLIBS-bufr: moda_nulbfr Module Reference
moda_nulbfr Module Reference
This module contains an array declaration used to store a switch for each internal I/O stream index, indicating whether any BUFR messages should actually be written to the corresponding logical unit.
Variables
integer, dimension(:), allocatable null
Output switch for each internal I/O stream index:
Detailed Description
This module contains an array declaration used to store a switch for each internal I/O stream index, indicating whether any BUFR messages should actually be written to the corresponding logical unit.
The default value is "on", indicating that BUFR messages should be written to the corresponding logical unit, but it can be switched to a value of "off" if it is connected to the library via a call to subroutine openbf() with IO = 'NUL', and in which case no output will actually be written to the corresponding logical unit. This can be useful if, for example, an application program is planning to use subroutine writsa() to return output BUFR messages via a memory array and doesn't want to also have them automatically written out to a file.
Author
J. Woollen
Date
2003-11-04
Variable Documentation
null
integer, dimension(:), allocatable moda_nulbfr::null
Output switch for each internal I/O stream index:
0 BUFR messages will be written to corresponding logical unit (default)
1 no BUFR messages will be written to corresponding logical unit
Definition at line 511 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), closbf(), msgwrt(), and openbf().