NCEPLIBS-bufr: moda_bitmaps Module Reference
moda_bitmaps Module Reference
Declare arrays and variables used to store bitmaps internally within a data subset definition.
Variables
character *6, dimension(:,:), allocatable ctco
Table C operators corresponding to inodtco.
integer, dimension(:,:), allocatable ibtmse
Ordinal positions in bitmap of bits that were "set" (set to a value of 0); these ordinal positions can range in value from 1 to iszbtm for each stored bitmap.
integer, dimension(:), allocatable inodtamc
Entries within jump/link table which contain Table A mnemonics.
integer, dimension(:,:), allocatable inodtco
Entries within jump/link table which contain Table C operators.
integer, dimension(:), allocatable istbtm
Ordinal position in data subset definition corresponding to the first entry of the bitmap.
integer, dimension(:), allocatable iszbtm
Size of bitmap (total number of entries, whether "set" (set to a value of 0) or not).
logical linbtm
true if a bitmap is in the process of being read for the current data subset; false otherwise.
integer lstnod
Most recent jump/link table entry that was processed by function igetrfel() and whose corresponding value type was either numeric or CCITT IA5.
integer lstnodct
Current count of consecutive occurrences of lstnod.
integer nbtm
Number of stored bitmaps for the current data subset (up to a maximum of mxbtm).
integer, dimension(:), allocatable nbtmse
Number of "set" entries (set to a value of 0) in the bitmap.
integer ntamc
Number of Table A mnemonics in jump/link table (up to a maximum of mxtamc) which contain at least one Table C operator with an XX value of 21 or greater in their data subset definition; only Table C operators with an XX value of 21 or greater are tracked within this module, since all others are automatically processed within subroutines tabsub() and tabent().
integer, dimension(:), allocatable ntco
Number of Table C operators (with an XX value of 21 or greater) within the data subset definition of the corresponding Table A mnemonic in inodtamc.
Detailed Description
Declare arrays and variables used to store bitmaps internally within a data subset definition.
Data values within this module are stored by subprograms strbtm(), igetrfel(), makestab() and tabsub().
Author
J. Ator
Date
2016-05-27
Variable Documentation
ctco
character*6, dimension(:,:), allocatable moda_bitmaps::ctco
Table C operators corresponding to inodtco.
Definition at line 57 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), strbtm(), and tabsub().
ibtmse
integer, dimension(:,:), allocatable moda_bitmaps::ibtmse
Ordinal positions in bitmap of bits that were "set" (set to a value of 0); these ordinal positions can range in value from 1 to iszbtm for each stored bitmap.
Definition at line 71 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), and strbtm().
inodtamc
integer, dimension(:), allocatable moda_bitmaps::inodtamc
Entries within jump/link table which contain Table A mnemonics.
Definition at line 51 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), strbtm(), and tabsub().
inodtco
integer, dimension(:,:), allocatable moda_bitmaps::inodtco
Entries within jump/link table which contain Table C operators.
Definition at line 59 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), strbtm(), and tabsub().
istbtm
integer, dimension(:), allocatable moda_bitmaps::istbtm
Ordinal position in data subset definition corresponding to the first entry of the bitmap.
Definition at line 64 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), and strbtm().
iszbtm
integer, dimension(:), allocatable moda_bitmaps::iszbtm
Size of bitmap (total number of entries, whether "set" (set to a value of 0) or not).
Definition at line 67 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), and strbtm().
linbtm
logical moda_bitmaps::linbtm
true if a bitmap is in the process of being read for the current data subset; false otherwise.
Definition at line 49 of file modules_arrs.F90.
Referenced by readsb(), and strbtm().
lstnod
integer moda_bitmaps::lstnod
Most recent jump/link table entry that was processed by function igetrfel() and whose corresponding value type was either numeric or CCITT IA5.
Definition at line 44 of file modules_arrs.F90.
Referenced by igetrfel(), and readsb().
lstnodct
integer moda_bitmaps::lstnodct
Current count of consecutive occurrences of lstnod.
Definition at line 46 of file modules_arrs.F90.
Referenced by igetrfel(), and readsb().
nbtm
integer moda_bitmaps::nbtm
Number of stored bitmaps for the current data subset (up to a maximum of mxbtm).
Definition at line 33 of file modules_arrs.F90.
Referenced by igetrfel(), readsb(), and strbtm().
nbtmse
integer, dimension(:), allocatable moda_bitmaps::nbtmse
Number of "set" entries (set to a value of 0) in the bitmap.
Definition at line 61 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), and strbtm().
ntamc
integer moda_bitmaps::ntamc
Number of Table A mnemonics in jump/link table (up to a maximum of mxtamc) which contain at least one Table C operator with an XX value of 21 or greater in their data subset definition; only Table C operators with an XX value of 21 or greater are tracked within this module, since all others are automatically processed within subroutines tabsub() and tabent().
Definition at line 40 of file modules_arrs.F90.
Referenced by igetrfel(), makestab(), strbtm(), and tabsub().
ntco
integer, dimension(:), allocatable moda_bitmaps::ntco
Number of Table C operators (with an XX value of 21 or greater) within the data subset definition of the corresponding Table A mnemonic in inodtamc.
Definition at line 55 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), strbtm(), and tabsub().