NCEPLIBS-bufr: moda_rlccmn Module Reference
moda_rlccmn Module Reference
This module contains array and variable declarations needed to store information about long character strings (greater than 8 bytes) when reading them from input data subsets in compressed BUFR messages via subroutines rdcmps() and readlc().
Variables
character *10, dimension(:), allocatable crtag
Table B mnemonics associated with long character strings.
integer, dimension(:), allocatable irbit
Pointers in data subset to first bits of long character strings.
integer, dimension(:), allocatable irnch
Lengths (in bytes) of long character strings.
integer nrst
Number of long character strings in data subset.
Detailed Description
This module contains array and variable declarations needed to store information about long character strings (greater than 8 bytes) when reading them from input data subsets in compressed BUFR messages via subroutines rdcmps() and readlc().
Author
J. Woollen
Date
2009-03-23
Variable Documentation
crtag
character*10, dimension(:), allocatable moda_rlccmn::crtag
Table B mnemonics associated with long character strings.
Definition at line 545 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), rdcmps(), and readlc().
irbit
integer, dimension(:), allocatable moda_rlccmn::irbit
Pointers in data subset to first bits of long character strings.
Definition at line 543 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), rdcmps(), and readlc().
irnch
integer, dimension(:), allocatable moda_rlccmn::irnch
Lengths (in bytes) of long character strings.
Definition at line 541 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), rdcmps(), and readlc().
nrst
integer moda_rlccmn::nrst
Number of long character strings in data subset.
Definition at line 539 of file modules_arrs.F90.
Referenced by rdcmps(), and readlc().