NCEPLIBS-bufr: moda_idrdm Module Reference
moda_idrdm Module Reference
This module contains a declaration for an array used by subroutine readerme() to read in a new DX dictionary table as a consecutive set of one or more DX BUFR tables messages.
Variables
integer, dimension(:), allocatable idrdm
DX BUFR tables message count for each I/O internal stream index.
Detailed Description
This module contains a declaration for an array used by subroutine readerme() to read in a new DX dictionary table as a consecutive set of one or more DX BUFR tables messages.
Author
J. Ator
Date
2009-03-23
Variable Documentation
idrdm
integer, dimension(:), allocatable moda_idrdm::idrdm
DX BUFR tables message count for each I/O internal stream index.
Set to a value of zero unless a new DX dictionary table is in the process of being read in by subroutine readerme() for the associated logical unit, and in which case it keeps track of how many such messages have been read in so far.
Definition at line 246 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bfrini(), and readerme().