NCEPLIBS-bufr: moda_xtab Module Reference
moda_xtab Module Reference
Declare an array used to track, for each file ID, whether the DX BUFR table associated with the corresponding logical unit has changed during the life of the application program.
Variables
logical, dimension(:), allocatable xtab
Tracking index for each file ID.
Detailed Description
Declare an array used to track, for each file ID, whether the DX BUFR table associated with the corresponding logical unit has changed during the life of the application program.
This information is stored and tracked within subroutine makestab(), which checks each time it is called to see if the DX BUFR table has changed for any file ID since the last time it was called.
Author
J. Woollen
Date
2009-03-18
Variable Documentation
xtab
logical, dimension(:), allocatable moda_xtab::xtab
Tracking index for each file ID.
Set to .true. if the DX BUFR table for the corresponding logical unit has changed since the previous call to subroutine makestab(); set to .false. otherwise.
Definition at line 831 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and makestab().