NCEPLIBS-bufr: moda_stcode Module Reference
moda_stcode Module Reference
Declare an array used to store a status code for each file ID if an error or other abnormal result occurs while processing a BUFR message within the associated logical unit.
Variables
integer, dimension(:), allocatable iscodes
Abnormal status codes.
Detailed Description
Declare an array used to store a status code for each file ID if an error or other abnormal result occurs while processing a BUFR message within the associated logical unit.
The status code can be retrieved at any time by the application program via a call to subroutine igetsc().
Author
J. Ator
Date
2010-05-11
Variable Documentation
iscodes
integer, dimension(:), allocatable moda_stcode::iscodes
Abnormal status codes.
0 all is normal; no error occurred
1 replication factor overflow in subroutine usrtpl()
Definition at line 623 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetsc(), openbf(), rdcmps(), readsb(), and usrtpl().