NCEPLIBS-bufr: moda_bitbuf Module Reference
moda_bitbuf Module Reference
This module contains array and variable declarations used to store BUFR messages internally for multiple I/O streams.
Variables
integer, dimension(:), allocatable ibay
Current data subset.
integer ibit
Bit pointer within IBAY.
integer maxbyt
Maximum length of an output BUFR message.
integer, dimension(:,:), allocatable mbay
Current BUFR message for each internal I/O stream.
integer, dimension(:), allocatable mbyt
Length (in bytes) of current BUFR message for each internal I/O stream.
Detailed Description
This module contains array and variable declarations used to store BUFR messages internally for multiple I/O streams.
Author
J. Ator
Date
2014-12-10
Variable Documentation
ibay
integer, dimension(:), allocatable moda_bitbuf::ibay
Current data subset.
Definition at line 16 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), msgupd(), wrcmps(), and wrtree().
ibit
integer moda_bitbuf::ibit
Bit pointer within IBAY.
Definition at line 14 of file modules_arrs.F90.
Referenced by copysb(), msgupd(), rdcmps(), rdtree(), readsb(), restd(), rewnbf(), ufbinx(), ufbtab(), ufbtam(), wrcmps(), writlc(), and wrtree().
maxbyt
integer moda_bitbuf::maxbyt
Maximum length of an output BUFR message.
Definition at line 12 of file modules_arrs.F90.
Referenced by bfrini(), cpyupd(), igetmxby(), maxout(), and msgupd().
mbay
integer, dimension(:,:), allocatable moda_bitbuf::mbay
Current BUFR message for each internal I/O stream.
Definition at line 20 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), closmg(), copymg(), copysb(), cpymem(), cpyupd(), ireadmt(), iupvs01(), mesgbc(), minimg(), msgini(), msgupd(), rcstpl(), rdcmps(), rdmemm(), rdmems(), rdtree(), readerme(), readlc(), readmg(), reads3(), readsb(), rewnbf(), rtrcpt(), ufbget(), ufbinx(), ufbtab(), ufbtam(), wrcmps(), and writlc().
mbyt
integer, dimension(:), allocatable moda_bitbuf::mbyt
Length (in bytes) of current BUFR message for each internal I/O stream.
Definition at line 18 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cktaba(), closmg(), copysb(), cpyupd(), msgini(), msgupd(), rdcmps(), rdmems(), readsb(), rewnbf(), ufbget(), ufbinx(), ufbtab(), and ufbtam().