NCEPLIBS-bufr: moda_comprs Module Reference
moda_comprs Module Reference
Declare arrays and variables needed for the storage of data values needed when writing compressed data subsets to a BUFR message for output.
Variables
character *(:), dimension(:,:), allocatable catx
Character data values for all data subsets in message.
integer *8 incr
Increment used when compressing non-character data values.
integer *8, dimension(:,:), allocatable matx
Non-character data values for all data subsets in message.
integer ncol
Number of data subsets in message.
Detailed Description
Declare arrays and variables needed for the storage of data values needed when writing compressed data subsets to a BUFR message for output.
These values can only be stored for one compressed BUFR message at any given time.
Author
J. Woollen
Date
2002-05-14
Variable Documentation
catx
character*(:), dimension(:,:), allocatable moda_comprs::catx
Character data values for all data subsets in message.
Definition at line 134 of file modules_arrs.F90.
Referenced by ardllocf(), wrcmps(), and writlc().
incr
integer*8 moda_comprs::incr
Increment used when compressing non-character data values.
Definition at line 130 of file modules_arrs.F90.
Referenced by wrcmps().
matx
integer*8, dimension(:,:), allocatable moda_comprs::matx
Non-character data values for all data subsets in message.
Definition at line 132 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), wrcmps(), and writlc().
ncol
integer moda_comprs::ncol
Number of data subsets in message.
Definition at line 128 of file modules_arrs.F90.
Referenced by wrcmps(), and writlc().