NCEPLIBS-bufr: moda_dscach Module Reference
moda_dscach Module Reference
Declare arrays and variables for the internal Table A mnemonic cache that is used for Section 3 decoding of BUFR messages.
Variables
character *8, dimension(:), allocatable cnem
Table A mnemonics.
integer, dimension(:,:), allocatable idcach
WMO bit-wise representations of the child descriptors for the corresponding Table A mnemonic in cnem.
integer ncnem
Number of entries in the internal Table A mnemonic cache (up to a maximum of mxcnem).
integer, dimension(:), allocatable ndc
Number of child descriptors for the corresponding Table A mnemonic in cnem.
Detailed Description
Declare arrays and variables for the internal Table A mnemonic cache that is used for Section 3 decoding of BUFR messages.
Data values within this module are stored by subroutine reads3().
Author
J. Ator
Date
2012-03-02
Variable Documentation
cnem
character*8, dimension(:), allocatable moda_dscach::cnem
Table A mnemonics.
Definition at line 200 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and reads3().
idcach
integer, dimension(:,:), allocatable moda_dscach::idcach
WMO bit-wise representations of the child descriptors for the corresponding Table A mnemonic in cnem.
Definition at line 206 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and reads3().
ncnem
integer moda_dscach::ncnem
Number of entries in the internal Table A mnemonic cache (up to a maximum of mxcnem).
Definition at line 198 of file modules_arrs.F90.
Referenced by bfrini(), and reads3().
ndc
integer, dimension(:), allocatable moda_dscach::ndc
Number of child descriptors for the corresponding Table A mnemonic in cnem.
Definition at line 203 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and reads3().