NCEPLIBS-bufr: moda_nrv203 Module Reference
moda_nrv203 Module Reference
This module contains array and variable declarations for use with any 2-03-YYY (change reference value) operators present within the internal jump/link table.
Variables
integer ibtnrv
Number of bits in Section 4 occupied by each new reference value for the current 2-03-YYY operator in scope; set to 0 if no such operator is currently in scope.
integer, dimension(:), allocatable ienrv
End of entry range in jump/link table, within which the corresponding new reference value in nrv will be applied to all occurrences of the corresponding Table B mnemonic in tagnrv.
integer, dimension(:), allocatable inodnrv
Entries within jump/link table which contain new reference values.
integer ipfnrv
A number between 1 and nnrv, denoting the first entry within the module arrays which applies to the current data subset in scope; set to 0 if no 2-03-YYY operators have been applied to the current data subset in scope.
integer, dimension(:), allocatable isnrv
Start of entry range in jump/link table, within which the corresponding new reference value in nrv will be applied to all occurrences of the corresponding Table B mnemonic in tagnrv.
integer nnrv
Number of entries in the jump/link table which contain new reference values (up to a maximum of MXNRV).
integer *8, dimension(:), allocatable nrv
New reference values corresponding to inodnrv.
character *8, dimension(:), allocatable tagnrv
Table B mnemonic to which the corresponding new reference value in nrv applies.
Detailed Description
This module contains array and variable declarations for use with any 2-03-YYY (change reference value) operators present within the internal jump/link table.
Data values within this module are stored by subroutine tabsub().
Author
J. Ator
Date
2012-03-02
Variable Documentation
ibtnrv
integer moda_nrv203::ibtnrv
Number of bits in Section 4 occupied by each new reference value for the current 2-03-YYY operator in scope; set to 0 if no such operator is currently in scope.
Definition at line 468 of file modules_arrs.F90.
Referenced by tabent(), and tabsub().
ienrv
integer, dimension(:), allocatable moda_nrv203::ienrv
End of entry range in jump/link table, within which the corresponding new reference value in nrv will be applied to all occurrences of the corresponding Table B mnemonic in tagnrv.
Definition at line 488 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), ipks(), nemspecs(), tabsub(), and ups().
inodnrv
integer, dimension(:), allocatable moda_nrv203::inodnrv
Entries within jump/link table which contain new reference values.
Definition at line 478 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), ipks(), nemspecs(), tabent(), ufdump(), and ups().
ipfnrv
integer moda_nrv203::ipfnrv
A number between 1 and nnrv, denoting the first entry within the module arrays which applies to the current data subset in scope; set to 0 if no 2-03-YYY operators have been applied to the current data subset in scope.
Definition at line 473 of file modules_arrs.F90.
Referenced by tabent(), and tabsub().
isnrv
integer, dimension(:), allocatable moda_nrv203::isnrv
Start of entry range in jump/link table, within which the corresponding new reference value in nrv will be applied to all occurrences of the corresponding Table B mnemonic in tagnrv.
Definition at line 484 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), ipks(), nemspecs(), tabent(), and ups().
nnrv
integer moda_nrv203::nnrv
Number of entries in the jump/link table which contain new reference values (up to a maximum of MXNRV).
Definition at line 464 of file modules_arrs.F90.
Referenced by igetrfel(), ipks(), makestab(), nemspecs(), tabent(), tabsub(), ufdump(), and ups().
nrv
integer*8, dimension(:), allocatable moda_nrv203::nrv
New reference values corresponding to inodnrv.
Definition at line 480 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), ipks(), nemspecs(), and ups().
tagnrv
character*8, dimension(:), allocatable moda_nrv203::tagnrv
Table B mnemonic to which the corresponding new reference value in nrv applies.
Definition at line 476 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), igetrfel(), ipks(), nemspecs(), tabent(), and ups().