NCEPLIBS-bufr: moda_mstabs Module Reference
moda_mstabs Module Reference
Declare arrays and variables used to store master Table B and Table D entries within internal memory.
Variables
character, dimension(:,:), allocatable cbbw
Bit widths corresponding to ibfxyn.
character, dimension(:,:), allocatable cbelem
Element names corresponding to ibfxyn.
character, dimension(:,:), allocatable cbmnem
Mnemonics corresponding to ibfxyn.
character, dimension(:,:), allocatable cbscl
Scale factors corresponding to ibfxyn.
character, dimension(:,:), allocatable cbsref
Reference values corresponding to ibfxyn.
character, dimension(:,:), allocatable cbunit
Units corresponding to ibfxyn.
character, dimension(:,:), allocatable cdmnem
Mnemonics corresponding to idfxyn.
character, dimension(:,:), allocatable cdseq
Sequence names corresponding to idfxyn.
integer, dimension(:), allocatable ibfxyn
WMO bit-wise representations of FXY numbers for master Table B.
integer, dimension(:), allocatable idefxy
WMO bit-wise representations of child descriptors corresponding to idfxyn.
integer, dimension(:), allocatable idfxyn
WMO bit-wise representations of FXY numbers for master Table D.
integer, dimension(:), allocatable ndelem
Numbers of child descriptors corresponding to idfxyn.
integer nmtb
Number of master Table B entries (up to a maximum of mxmtbb).
integer nmtd
Number of master Table D entries (up to a maximum of mxmtbd).
Detailed Description
Declare arrays and variables used to store master Table B and Table D entries within internal memory.
Data values within this module are stored by subroutine ireadmt().
Author
J. Ator
Date
2014-12-10
Variable Documentation
cbbw
character, dimension(:,:), allocatable moda_mstabs::cbbw
Bit widths corresponding to ibfxyn.
Definition at line 415 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
cbelem
character, dimension(:,:), allocatable moda_mstabs::cbelem
Element names corresponding to ibfxyn.
Definition at line 421 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
cbmnem
character, dimension(:,:), allocatable moda_mstabs::cbmnem
Mnemonics corresponding to ibfxyn.
Definition at line 419 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
cbscl
character, dimension(:,:), allocatable moda_mstabs::cbscl
Scale factors corresponding to ibfxyn.
Definition at line 411 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
cbsref
character, dimension(:,:), allocatable moda_mstabs::cbsref
Reference values corresponding to ibfxyn.
Definition at line 413 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
cbunit
character, dimension(:,:), allocatable moda_mstabs::cbunit
Units corresponding to ibfxyn.
Definition at line 417 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
cdmnem
character, dimension(:,:), allocatable moda_mstabs::cdmnem
Mnemonics corresponding to idfxyn.
Definition at line 427 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
cdseq
character, dimension(:,:), allocatable moda_mstabs::cdseq
Sequence names corresponding to idfxyn.
Definition at line 425 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
ibfxyn
integer, dimension(:), allocatable moda_mstabs::ibfxyn
WMO bit-wise representations of FXY numbers for master Table B.
Definition at line 409 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
idefxy
integer, dimension(:), allocatable moda_mstabs::idefxy
WMO bit-wise representations of child descriptors corresponding to idfxyn.
Definition at line 431 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
idfxyn
integer, dimension(:), allocatable moda_mstabs::idfxyn
WMO bit-wise representations of FXY numbers for master Table D.
Definition at line 423 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
ndelem
integer, dimension(:), allocatable moda_mstabs::ndelem
Numbers of child descriptors corresponding to idfxyn.
Definition at line 429 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpmstabs(), and ireadmt().
nmtb
integer moda_mstabs::nmtb
Number of master Table B entries (up to a maximum of mxmtbb).
Definition at line 405 of file modules_arrs.F90.
Referenced by cpmstabs(), and ireadmt().
nmtd
integer moda_mstabs::nmtd
Number of master Table D entries (up to a maximum of mxmtbd).
Definition at line 407 of file modules_arrs.F90.
Referenced by cpmstabs(), and ireadmt().