NCEPLIBS-bufr: nemspecs.f File Reference
nemspecs.f File Reference
Get the scale factor, reference value and bit width associated with a specified occurrence of a Table B mnemonic.
Functions/Subroutines
subroutine nemspecs (LUNIT, NEMO, NNEMO, NSCL, NREF, NBTS, IRET)
Given a Table B mnemonic defined within a data subset, this subroutine returns the scale factor, reference value and bit width of a specified occurrence of that mnemonic within the overall data subset definition, counting from the beginning of the subset.
Detailed Description
Get the scale factor, reference value and bit width associated with a specified occurrence of a Table B mnemonic.
Definition in file nemspecs.f.
Function/Subroutine Documentation
nemspecs()
subroutine nemspecs (LUNIT, character*(*) NEMO, NNEMO, NSCL, NREF, NBTS, IRET)
Given a Table B mnemonic defined within a data subset, this subroutine returns the scale factor, reference value and bit width of a specified occurrence of that mnemonic within the overall data subset definition, counting from the beginning of the subset.
The values returned include the application of any Table C operators (e.g. 2-01-YYY, 2-02-YYY, 2-03-YYY, 2-07-YYY, 2-08-YYY) which may be in effect for the specified occurrence of the mnemonic.
Author
J. Ator
Date
2014-10-02
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
[in] NEMO – character*(*): Table B mnemonic
[in] NNEMO – integer: Ordinal occurrence of NEMO for which information is to be returned, counting from the beginning of the overall subset definition
[out] NSCL – integer: Scale factor in effect for (NNEMO)th occurrence of NEMO
[out] NREF – integer: Reference value in effect for (NNEMO)th occurrence of NEMO
[out] NBTS – integer: Bit width in effect for (NNEMO)th occurrence of NEMO
[out] IRET – integer: return code
0 = normal return
-1 = NEMO could not be found, or some other error occurred
A data subset must already be in scope within the BUFRLIB internal arrays for LUNIT, either via a previous call to one of the subset-reading subroutines (when reading BUFR data subsets) or via a previous call to one of the message-writing subroutines (when writing BUFR data subsets).
Program history log:
Date Programmer Comments
2014-10-02 J. Ator Original version
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 50 of file nemspecs.f.
References fstag(), moda_tables::ibt, moda_nrv203::ienrv, moda_nrv203::inodnrv, moda_tables::irf, moda_tables::isc, moda_nrv203::isnrv, moda_nrv203::nnrv, moda_nrv203::nrv, status(), strsuc(), moda_nrv203::tagnrv, and moda_tables::typ.
Referenced by bufr_c_interface_mod::nemspecs_c().