NCEPLIBS-bufr: nenubd.f File Reference
nenubd.f File Reference
Functions/Subroutines
subroutine nenubd (NEMO, NUMB, LUN)
THIS SUBROUTINE CHECKS A MNEMONIC AND FXY VALUE PAIR THAT WERE READ FROM A USER-SUPPLIED BUFR DICTIONARY TABLE IN CHARACTER FORMAT, IN ORDER TO MAKE SURE THAT NEITHER VALUE HAS ALREADY BEEN DEFINED WITHIN INTERNAL BUFR TABLE B OR D (IN MODULE TABABD) FOR THE GIVEN LUN.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file nenubd.f.
Function/Subroutine Documentation
nenubd()
subroutine nenubd (character*8 NEMO, character*6 NUMB, LUN)
THIS SUBROUTINE CHECKS A MNEMONIC AND FXY VALUE PAIR THAT WERE READ FROM A USER-SUPPLIED BUFR DICTIONARY TABLE IN CHARACTER FORMAT, IN ORDER TO MAKE SURE THAT NEITHER VALUE HAS ALREADY BEEN DEFINED WITHIN INTERNAL BUFR TABLE B OR D (IN MODULE TABABD) FOR THE GIVEN LUN.
IF EITHER VALUE HAS ALREADY BEEN DEFINED FOR THIS LUN, THEN AN APPROPRIATE CALL IS MADE TO BUFR ARCHIVE LIBRARY SUBROUTINE BORT.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR (ENTRY POINT IN NENUCK) 1995-06-28 J. WOOLLEN – INCREASED THE SIZE OF INTERNAL BUFR TABLE ARRAYS IN ORDER TO HANDLE BIGGER FILES 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" (IN PARENT ROUTINE NENUCK) 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) (IN PARENT ROUTINE NENUCK) 2002-05-14 J. WOOLLEN – CHANGED FROM AN ENTRY POINT TO INCREASE PORTABILITY TO OTHER PLATFORMS (NENUCK WAS THEN REMOVED BECAUSE IT WAS JUST A DUMMY ROUTINE WITH ENTRIES) 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION; OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL NENUBD (NEMO, NUMB, LUN) INPUT ARGUMENT LIST: NEMO - CHARACTER*8: MNEMONIC NUMB - CHARACTER*6: FXY VALUE ASSOCIATED WITH NEMO LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
THIS ROUTINE CALLS: BORT THIS ROUTINE IS CALLED BY: STBFDX STNTBI Normally not called by any application programs.
Definition at line 48 of file nenubd.f.
References bort(), moda_tababd::ntbb, moda_tababd::ntbd, moda_tababd::tabb, and moda_tababd::tabd.
Referenced by stbfdx(), and stntbi().