NCEPLIBS-bufr: nevn.f File Reference
nevn.f File Reference
Functions/Subroutines
function nevn (NODE, LUN, INV1, INV2, I1, I2, I3, USR)
THIS FUNCTION LOOKS FOR ALL STACKED DATA EVENTS FOR A SPECIFIED DATA VALUE AND LEVEL WITHIN THE PORTION OF THE CURRENT SUBSET BUFFER BOUNDED BY THE INDICES INV1 AND INV2.
Detailed Description
Author
WOOLLEN
Date
2003-11-04
Definition in file nevn.f.
Function/Subroutine Documentation
nevn()
function nevn (NODE, LUN, INV1, INV2, I1, I2, I3, real*8, dimension(i1,i2,i3) USR)
THIS FUNCTION LOOKS FOR ALL STACKED DATA EVENTS FOR A SPECIFIED DATA VALUE AND LEVEL WITHIN THE PORTION OF THE CURRENT SUBSET BUFFER BOUNDED BY THE INDICES INV1 AND INV2.
ALL SUCH EVENTS ARE ACCUMULATED AND RETURNED TO THE CALLING PROGRAM WITHIN ARRAY USR. THE VALUE OF THE FUNCTION ITSELF IS THE TOTAL NUMBER OF EVENTS FOUND.
PROGRAM HISTORY LOG: 2003-11-04 J. WOOLLEN – ORIGINAL AUTHOR (WAS IN VERIFICATION VERSION) 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2009-03-31 J. WOOLLEN – ADDED ADDITIONAL DOCUMENTATION 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: NEVN (NODE, LUN, INV1, INV2, I1, I2, I3, USR) INPUT ARGUMENT LIST: NODE - INTEGER: JUMP/LINK TABLE INDEX OF NODE TO RETURN STACKED VALUES FOR LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS INV1 - INTEGER: STARTING INDEX OF THE PORTION OF THE SUBSET BUFFER IN WHICH TO LOOK FOR STACK VALUES INV2 - INTEGER: ENDING INDEX OF THE PORTION OF THE SUBSET BUFFER IN WHICH TO LOOK FOR STACK VALUES I1 - INTEGER: LENGTH OF FIRST DIMENSION OF USR I2 - INTEGER: LENGTH OF SECOND DIMENSION OF USR I3 - INTEGER: LENGTH OF THIRD DIMENSION OF USR
OUTPUT ARGUMENT LIST: USR - REAL*8:(I1,I2,I3) STARTING ADDRESS OF DATA VALUES READ FROM DATA SUBSET, EVENTS ARE RETURNED IN THE THIRD DIMENSION FOR A PARTICULAR DATA VALUE AND LEVEL IN THE FIRST AND SECOND DIMENSIONS NEVN - INTEGER: NUMBER OF EVENTS IN STACK (MUST BE LESS THAN OR EQUAL TO I3)
REMARKS: IMPORTANT: THIS ROUTINE SHOULD ONLY BE CALLED BY ROUTINE UFBIN3, WHICH, ITSELF, IS CALLED ONLY BY VERIFICATION APPLICATION PROGRAM GRIDTOBS, WHERE IT WAS PREVIOUSLY AN IN-LINE SUBROUTINE. IN GENERAL, NEVN DOES NOT WORK PROPERLY IN OTHER APPLICATION PROGRAMS AT THIS TIME.
THIS ROUTINE CALLS: BORT INVWIN LSTJPB THIS ROUTINE IS CALLED BY: UFBIN3 Should NOT be called by any application programs!!!
Definition at line 54 of file nevn.f.
References bort(), invwin(), lstjpb(), and nevn().
Referenced by nevn(), and ufbin3().