NCEPLIBS-bufr: newwin.f File Reference
newwin.f File Reference
Functions/Subroutines
subroutine newwin (LUN, IWIN, JWIN)
GIVEN AN INDEX WITHIN THE INTERNAL JUMP/LINK TABLE WHICH POINTS TO THE START OF AN "RPC" WINDOW (I.E.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file newwin.f.
Function/Subroutine Documentation
subroutine newwin (LUN, IWIN, JWIN)
GIVEN AN INDEX WITHIN THE INTERNAL JUMP/LINK TABLE WHICH POINTS TO THE START OF AN "RPC" WINDOW (I.E.
ITERATION OF AN 8-BIT OR 16-BIT DELAYED REPLICATION SEQUENCE), THIS SUBROUTINE COMPUTES THE ENDING INDEX OF THE WINDOW. ALTERNATIVELY, IF THE GIVEN INDEX POINTS TO THE START OF A "SUB" WINDOW (I.E. THE FIRST NODE OF A SUBSET), THE SUBROUTINE RETURNS THE INDEX OF THE LAST NODE.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2002-05-14 J. WOOLLEN – REMOVED OLD CRAY COMPILER DIRECTIVES 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2009-03-31 J. WOOLLEN – ADDED DOCUMENTATION 2009-05-07 J. ATOR – USE LSTJPB INSTEAD OF LSTRPC 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL NEWWIN (LUN, IWIN, JWIN) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS IWIN - INTEGER: STARTING INDEX OF WINDOW ITERATION
OUTPUT ARGUMENT LIST: JWIN - INTEGER: ENDING INDEX OF WINDOW ITERATION
REMARKS:
SEE THE DOCBLOCK IN BUFR ARCHIVE LIBRARY SUBROUTINE GETWIN FOR AN EXPLANATION OF "WINDOWS" WITHIN THE CONTEXT OF A BUFR DATA SUBSET.
THIS ROUTINE CALLS: BORT LSTJPB THIS ROUTINE IS CALLED BY: DRSTPL UFBRW Normally not called by any application programs.
Definition at line 51 of file newwin.f.
References bort(), and lstjpb().
Referenced by drstpl(), and ufbrw().