NCEPLIBS-bufr: nmwrd.f File Reference
nmwrd.f File Reference
Determine the array size needed to store a BUFR message.
Functions/Subroutines
recursive function nmwrd (MBAY)
Given an integer array containing Section 0 from a BUFR message, this function determines the array size (in integers) needed to store the entire BUFR message.
Detailed Description
Determine the array size needed to store a BUFR message.
Author
J. Ator
Date
2005-11-29
Definition in file nmwrd.f.
Function/Subroutine Documentation
nmwrd()
recursive function nmwrd (dimension(*) MBAY)
Given an integer array containing Section 0 from a BUFR message, this function determines the array size (in integers) needed to store the entire BUFR message.
This function is similar to function lmsg(), except that it takes an integer array as input rather than a character string.
Parameters
[in] MBAY – integer(*): Section 0 from a BUFR message
Returns
nmwrd – integer: Array size (in integers) needed to store entire BUFR message
Remarks
In some cases, the value returned may be slightly larger than the minimum number of integers needed to store the entire BUFR message.
Author
J. Ator
Date
2005-11-29
Definition at line 23 of file nmwrd.f.
References modv_im8b::im8b, and iupbs01().
Referenced by cnved4(), cpdxmm(), lmsg(), msgwrt(), padmsg(), ufbmem(), and ufbmex().