NCEPLIBS-bufr: nvnwin.f File Reference
nvnwin.f File Reference
Search for all occurrences of a specified node within a specified portion of the current data subset.
Functions/Subroutines
function nvnwin (NODE, LUN, INV1, INV2, INVN, NMAX)
This function looks for and returns all occurrences of a specified node within the portion of the current subset buffer bounded by the indices inv1 and inv2.
Detailed Description
Search for all occurrences of a specified node within a specified portion of the current data subset.
Author
Woollen
Date
1994-01-06
Definition in file nvnwin.f.
Function/Subroutine Documentation
nvnwin()
function nvnwin (NODE, LUN, INV1, INV2, dimension(nmax) INVN, NMAX)
This function looks for and returns all occurrences of a specified node within the portion of the current subset buffer bounded by the indices inv1 and inv2.
The resulting list is a stack of "event" indices for the requested node.
Parameters
[in] NODE - integer: jump/link table index to look for.
[in] LUN - integer: i/o stream index into internal memory arrays.
[in] INV1 - integer: starting index of the portion of the subset buffer in which to look.
[in] INV2 - integer: ending index of the portion of the subset buffer in which to look.
[out] INVN - integer: array of stack "event" indices for node.
[in] NMAX - integer: dimensioned size of invn; used by the function to ensure that it does not overflow the invn array.
Returns
number of indices within invn.
Author
Woollen
Date
1994-01-06
Definition at line 23 of file nvnwin.f.
References bort(), errwrt(), and moda_usrint::inv.
Referenced by ufbevn().