NCEPLIBS-bufr: nwords.f File Reference
nwords.f File Reference
Functions/Subroutines
function nwords (N, LUN)
THIS FUNCTION ADDS UP THE COMPLETE LENGTH OF THE DELAYED REPLICATION SEQUENCE BEGINNING AT INDEX N OF THE DATA SUBSET.
Detailed Description
Author
WOOLLEN
Date
1996-10-09
Definition in file nwords.f.
Function/Subroutine Documentation
nwords()
function nwords (N, LUN)
THIS FUNCTION ADDS UP THE COMPLETE LENGTH OF THE DELAYED REPLICATION SEQUENCE BEGINNING AT INDEX N OF THE DATA SUBSET.
PROGRAM HISTORY LOG: 1996-10-09 J. WOOLLEN – ORIGINAL AUTHOR 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY) (INCOMPLETE) 2009-03-31 J. WOOLLEN – ADDED DOCUMENTATION 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: NWORDS (N, LUN) INPUT ARGUMENT LIST: N - INTEGER: INDEX TO START OF DELAYED REPLICATION SEQUENCE LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
OUTPUT ARGUMENT LIST: NWORDS - INTEGER: COMPLETE LENGTH OF DELAYED REPLICATION SEQUENCE WITHIN DATA SUBSET
REMARKS: THIS ROUTINE CALLS: None THIS ROUTINE IS CALLED BY: INVMRG Normally not called by any application programs.
Definition at line 38 of file nwords.f.
References nwords().
Referenced by invmrg(), and nwords().