NCEPLIBS-bufr: openbt.F90 File Reference
openbt.F90 File Reference
Specify DX BUFR table file of last resort.
Functions/Subroutines
recursive subroutine openbt (lundx, mtyp)
Specify a DX BUFR table of last resort, in case subroutine cktaba() is unable to locate a DX BUFR table on its own when reading/decoding a BUFR message.
Detailed Description
Specify DX BUFR table file of last resort.
Author
J. Woollen
Date
1998-07-08
Definition in file openbt.F90.
Function/Subroutine Documentation
openbt()
recursive subroutine openbt (integer, intent(out) lundx, integer, intent(in) mtyp)
Specify a DX BUFR table of last resort, in case subroutine cktaba() is unable to locate a DX BUFR table on its own when reading/decoding a BUFR message.
Within the NCEPLIBS-bufr distribution package, this subroutine is a default placeholder which always returns lundx = 0 and is only included to allow application programs to compile without generating a link error for an unresolved external reference. However, users are free to define their own inline version of this subroutine with the same name and calling sequence and include it within the compilation of their application program in order to override the default placeholder version of this subroutine. In such cases, subroutine cktaba() will then use the inline version of this subroutine as a last resort when attempting to locate the required DX BUFR table file.
Parameters
mtyp - Data category of BUFR message for which subroutine cktaba() was unable to locate a DX BUFR table file
lundx - Fortran logical unit number for file containing DX BUFR table information to be used in decoding message
0 = No such file is available
Remarks
See DX BUFR Tables for more information about the format and contents of DX BUFR table files.
Author
J. Woollen
Date
1998-07-08
Definition at line 30 of file openbt.F90.
References errwrt(), x48(), and x84().
Referenced by cktaba().