NCEPLIBS-bufr: parusr.f File Reference
parusr.f File Reference
Functions/Subroutines
subroutine parusr (STR, LUN, I1, IO)
THIS SUBROUTINE INITATES THE PROCESS TO PARSE OUT MNEMONICS (NODES) FROM A USER-SPECIFIED CHARACTER STRING, AND SEPARATES THEM INTO STORE AND CONDITION NODES.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file parusr.f.
Function/Subroutine Documentation
parusr()
subroutine parusr (character*(*) STR, LUN, I1, IO)
THIS SUBROUTINE INITATES THE PROCESS TO PARSE OUT MNEMONICS (NODES) FROM A USER-SPECIFIED CHARACTER STRING, AND SEPARATES THEM INTO STORE AND CONDITION NODES.
INFORMATION ABOUT THE STRING "PIECES" (I.E., THE MNEMONICS) IS STORED IN ARRAYS IN COMMON BLOCK /USRSTR/. CONDITION NODES ARE SORTED IN THE ORDER EXPECTED IN THE INTERNAL JUMP/LINK TABLES AND SEVERAL CHECKS ARE PERFORMED ON THE NODES.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT"; IMPROVED MACHINE PORTABILITY 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY; CHANGED CALL FROM BORT TO BORT2; RESPONDED TO CHANGE IN PARUTG (WHICH THIS ROUTINE CALLS) TO NO LONGER EXPECT AN ALTERNATE RETURN TO A STATEMENT NUMBER IN THIS ROUTINE WHICH CALLED BORT (BORT IS NOW CALLED IN PARUTG) 2007-01-19 J. ATOR – REPLACED CALL TO PARSEQ WITH CALL TO PARSTR 2009-05-07 J. ATOR – USE LSTJPB INSTEAD OF LSTRPC
USAGE: CALL PARUSR (STR, LUN, I1, IO) INPUT ARGUMENT LIST: STR - CHARACTER*(*): STRING OF BLANK-SEPARATED MNEMONICS LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS I1 - INTEGER: A NUMBER GREATER THAN OR EQUAL TO THE NUMBER OF BLANK-SEPARATED MNEMONICS IN STR IO - INTEGER: STATUS INDICATOR FOR BUFR FILE ASSOCIATED WITH LUN: 0 = input file 1 = output file
REMARKS: THIS ROUTINE CALLS: BORT2 LSTJPB PARSTR PARUTG THIS ROUTINE IS CALLED BY: STRING Normally not called by any application programs.
Definition at line 49 of file parusr.f.
References bort2(), lstjpb(), parstr(), and parutg().
Referenced by string().