NCEPLIBS-bufr: rdcmps.f File Reference
rdcmps.f File Reference
Functions/Subroutines
subroutine rdcmps (LUN)
THIS SUBROUTINE UNCOMPRESSES AND UNPACKS THE NEXT SUBSET FROM THE INTERNAL COMPRESSED MESSAGE BUFFER (ARRAY MBAY IN MODULE BITBUF) AND STORES THE UNPACKED SUBSET WITHIN THE INTERNAL ARRAY VAL(*,LUN) IN MODULE USRINT.
Detailed Description
Author
WOOLLEN
Date
2000-09-19
Definition in file rdcmps.f.
Function/Subroutine Documentation
rdcmps()
subroutine rdcmps (LUN)
THIS SUBROUTINE UNCOMPRESSES AND UNPACKS THE NEXT SUBSET FROM THE INTERNAL COMPRESSED MESSAGE BUFFER (ARRAY MBAY IN MODULE BITBUF) AND STORES THE UNPACKED SUBSET WITHIN THE INTERNAL ARRAY VAL(*,LUN) IN MODULE USRINT.
PROGRAM HISTORY LOG: 2000-09-19 J. WOOLLEN – ORIGINAL AUTHOR 2002-05-14 J. WOOLLEN – IMPROVED GENERALITY, PREVIOUSLY RDCMPS WOULD NOT RECOGNIZE COMPRESSED DELAYED REPLICATION AS A LEGITIMATE DATA STRUCTURE 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION 2004-08-18 J. ATOR – INITIALIZE CVAL TO EMPTY BEFORE CALLING UPC; CORRECT LOGIC FOR WHEN A CHARACTER VALUE IS THE SAME FOR ALL SUBSETS IN A MESSAGE; MAXIMUM MESSAGE LENGTH INCREASED FROM 20,000 TO 50,000 BYTES 2009-03-23 J. ATOR – PREVENT OVERFLOW OF CVAL AND CREF FOR STRINGS LONGER THAN 8 CHARACTERS 2012-03-02 J. ATOR – USE FUNCTION UPS 2012-06-04 J. ATOR – SET DECODED REAL*8 VALUE TO "MISSING" WHEN CORRESPONDING CHARACTER FIELD HAS ALL BITS SET TO 1 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS 2022-05-06 J. WOOLLEN – USE UP8 FOR 8BYTE INTEGER OPERATION
USAGE: CALL RDCMPS (LUN) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
REMARKS: THIS ROUTINE CALLS: BORT ICBFMS IGETRFEL STRBTM UPB UP8 UPC UPS USRTPL THIS ROUTINE IS CALLED BY: READSB Normally not called by any application programs.
Definition at line 46 of file rdcmps.f.
References modv_bmiss::bmiss, bort(), moda_tables::ibt, icbfms(), igetrfel(), moda_tables::itp, moda_bitbuf::mbay, moda_bitbuf::mbyt, modv_mxrst::mxrst, strbtm(), moda_tables::tag, up8(), upb(), upc(), ups(), and usrtpl().
Referenced by readsb().