NCEPLIBS-bufr: rdmgsb.f File Reference
rdmgsb.f File Reference
Functions/Subroutines
subroutine rdmgsb (LUNIT, IMSG, ISUB)
THIS SUBROUTINE OPENS A BUFR FILE IN LOGICAL UNIT LUNIT FOR INPUT OPERATIONS, THEN READS A PARTICULAR SUBSET INTO INTERNAL SUBSET ARRAYS FROM A PARTICULAR BUFR MESSAGE IN A MESSAGE BUFFER.
Detailed Description
Author
WOOLLEN
Date
2003-11-04
Definition in file rdmgsb.f.
Function/Subroutine Documentation
rdmgsb()
subroutine rdmgsb (LUNIT, IMSG, ISUB)
THIS SUBROUTINE OPENS A BUFR FILE IN LOGICAL UNIT LUNIT FOR INPUT OPERATIONS, THEN READS A PARTICULAR SUBSET INTO INTERNAL SUBSET ARRAYS FROM A PARTICULAR BUFR MESSAGE IN A MESSAGE BUFFER.
THIS IS BASED ON THE SUBSET NUMBER IN THE MESSAGE AND THE MESSAGE NUMBER IN THE BUFR FILE. THE MESSAGE NUMBER DOES NOT INCLUDE THE DICTIONARY MESSAGES AT THE BEGINNING OF THE FILE.
PROGRAM HISTORY LOG: 2003-11-04 J. WOOLLEN – ORIGINAL AUTHOR (WAS IN VERIFICATION VERSION BUT MAY HAVE BEEN IN THE PRODUCTION VERSION AT ONE TIME AND THEN REMOVED) 2003-11-04 D. KEYSER – INCORPORATED INTO "UNIFIED" BUFR ARCHIVE LIBRARY; UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION; OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2004-08-09 J. ATOR – MAXIMUM MESSAGE LENGTH INCREASED FROM 20,000 TO 50,000 BYTES 2009-03-23 J. ATOR – MODIFY LOGIC TO HANDLE BUFR TABLE MESSAGES ENCOUNTERED ANYWHERE IN THE FILE (AND NOT JUST AT THE BEGINNING!) 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL RDMGSB (LUNIT, IMSG, ISUB) INPUT ARGUMENT LIST: LUNIT - INTEGER: FORTRAN LOGICAL UNIT NUMBER FOR BUFR FILE IMSG - INTEGER: POINTER TO BUFR MESSAGE NUMBER TO READ IN BUFR FILE ISUB - INTEGER: POINTER TO SUBSET NUMBER TO READ IN BUFR MESSAGE
INPUT FILES: UNIT "LUNIT" - BUFR FILE
REMARKS: THIS ROUTINE CALLS: BORT OPENBF READMG READSB STATUS UPB THIS ROUTINE IS CALLED BY: None Normally called only by application programs.
Definition at line 45 of file rdmgsb.f.
References bort(), moda_bitbuf::mbay, moda_bitbuf::mbyt, openbf(), readmg(), readsb(), status(), and upb().