NCEPLIBS-bufr: rdmsgw.F90 File Reference
rdmsgw.F90 File Reference
Read a BUFR message.
Functions/Subroutines
subroutine rdmsgw (lunit, mesg, iret)
Read the next BUFR message from logical unit lunit as an array of integer words.
Detailed Description
Read a BUFR message.
Author
J. Ator
Date
2005-11-29
Definition in file rdmsgw.F90.
Function/Subroutine Documentation
rdmsgw()
subroutine rdmsgw (integer lunit, integer, dimension(*) mesg, integer iret)
Read the next BUFR message from logical unit lunit as an array of integer words.
Parameters
[in] lunit - integer: Fortran logical unit number for BUFR file.
[out] mesg - integer(*): BUFR message.
[out] iret - integer: return code:
0 normal return.
-1 end-of-file encountered while reading from lunit.
Author
J. Ator
Date
2005-11-29
Definition at line 15 of file rdmsgw.F90.
References errwrt(), modv_mxmsgl::mxmsgld4, and status().
Referenced by copybf(), cpdxmm(), datebf(), dumpbf(), mesgbc(), mesgbf(), posapx(), rdbfdx(), readmg(), ufbmem(), and ufbmex().