NCEPLIBS-bufr: rdmtbf.f File Reference
rdmtbf.f File Reference
Read master Code/Flag table information from local file system.
Functions/Subroutines
subroutine rdmtbf (LUNSTF, LUNLTF)
This subroutine reads master Code/Flag table information from two separate ASCII files (one standard and one local) and then merges the output into a single set of arrays.
Detailed Description
Read master Code/Flag table information from local file system.
Author
J. Ator
Date
2017-10-17
Definition in file rdmtbf.f.
Function/Subroutine Documentation
rdmtbf()
subroutine rdmtbf (LUNSTF, LUNLTF)
This subroutine reads master Code/Flag table information from two separate ASCII files (one standard and one local) and then merges the output into a single set of arrays.
Each of the two ASCII files must already be individually sorted in ascending order with respect to the FXY numbers.
Parameters
[in] LUNSTF – integer: Fortran logical unit number for ASCII file containing standard Code/Flag table information
[in] LUNLTF – integer: Fortran logical unit number for ASCII file containing local Code/Flag table information
Author
J. Ator
Date
2017-10-17
Definition at line 21 of file rdmtbf.f.
References bort(), getntbe(), gettbh(), sntbfe(), and wrdlen().
Referenced by ireadmt().