NCEPLIBS-bufr: rdmtbb.f File Reference
rdmtbb.f File Reference
Read master Table B information from local file system.
Functions/Subroutines
subroutine rdmtbb (LUNSTB, LUNLTB, MXMTBB, IMT, IMTV, IOGCE, ILTV, NMTBB, IMFXYN, CMSCL, CMSREF, CMBW, CMUNIT, CMMNEM, CMDSC, CMELEM)
This subroutine reads master Table B information from two separate ASCII files (one standard and one local) and then merges the output into a single set of arrays.
Detailed Description
Read master Table B information from local file system.
Definition in file rdmtbb.f.
Function/Subroutine Documentation
rdmtbb()
subroutine rdmtbb (LUNSTB, LUNLTB, MXMTBB, IMT, IMTV, IOGCE, ILTV, NMTBB, integer, dimension(*) IMFXYN, character, dimension(4,*) CMSCL, character, dimension(12,*) CMSREF, character, dimension(4,*) CMBW, character, dimension(24,*) CMUNIT, character, dimension(8,*) CMMNEM, character*4, dimension(*) CMDSC, character, dimension(120,*) CMELEM)
This subroutine reads master Table B information from two separate ASCII files (one standard and one local) and then merges the output into a single set of arrays.
Each of the two ASCII files must already be individually sorted in ascending order with respect to the FXY numbers.
Author
J. Ator
Date
2007-01-19
Parameters
[in] LUNSTB – integer: Fortran logical unit number for ASCII file containing standard Table B information
[in] LUNLTB – integer: Fortran logical unit number for ASCII file containing local Table B information
[in] MXMTBB – integer: Dimensioned size (in integers) of merged output arrays; used by the subroutine to ensure that it doesn't overflow these arrays
[out] IMT – integer: Master table
This value is read from both ASCII files and must be identical between them.
[out] IMTV – integer: Version number of master table
This value is read from the standard ASCII file.
[out] IOGCE – integer: Originating center
This value is read from the local ASCII file.
[out] ILTV – integer: Version number of local table
This value is read from the local ASCII file.
[out] NMTBB – integer: Number of entries in merged output arrays
[out] IMFXYN – integer(*): Merged array containing bit-wise representations of FXY numbers
[out] CMSCL – character*4(*): Merged array containing scale factors
[out] CMSREF – character*12(*): Merged array containing reference values
[out] CMBW – character*4(*): Merged array containing bit widths
[out] CMUNIT – character*24(*): Merged array containing units
[out] CMMNEM – character*8(*): Merged array containing mnemonics
[out] CMDSC – character*4(*): Merged array containing descriptor codes
[out] CMELEM – character*120(*): Merged array containing element names
Program history log:
Date Programmer Comments
2007-01-19 J. Ator Original author
2021-01-08 J. Ator Modified mstabs array declarations for GNUv10 portability
2021-05-17 J. Ator Allow up to 24 characters in cmunit
Definition at line 61 of file rdmtbb.f.
References adn30(), bort(), getntbe(), gettbh(), sntbbe(), and wrdlen().
Referenced by ireadmt().