NCEPLIBS-bufr: rdusdx.f File Reference
rdusdx.f File Reference
Functions/Subroutines
subroutine rdusdx (LUNDX, LUN)
THIS SUBROUTINE READS AND PARSES A FILE CONTAINING A USER- SUPPLIED BUFR DICTIONARY TABLE IN CHARACTER FORMAT, AND THEN STORES THIS INFORMATION INTO INTERNAL ARRAYS IN MODULE TABABD (SEE REMARKS FOR CONTENTS OF INTERNAL ARRAYS).
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file rdusdx.f.
Function/Subroutine Documentation
rdusdx()
subroutine rdusdx (LUNDX, LUN)
THIS SUBROUTINE READS AND PARSES A FILE CONTAINING A USER- SUPPLIED BUFR DICTIONARY TABLE IN CHARACTER FORMAT, AND THEN STORES THIS INFORMATION INTO INTERNAL ARRAYS IN MODULE TABABD (SEE REMARKS FOR CONTENTS OF INTERNAL ARRAYS).
THIS SUBROUTINE PERFORMS A FUNCTION SIMILAR TO BUFR ARCHIVE LIBRARY SUBROUTINE RDBFDX, EXECPT THAT RDBFDX READS THE BUFR TABLE DIRECTLY FROM MESSAGES AT BEGINNING OF AN INPUT BUFR FILE.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1995-06-28 J. WOOLLEN – INCREASED THE SIZE OF INTERNAL BUFR TABLE ARRAYS IN ORDER TO HANDLE BIGGER FILES 1996-12-17 J. WOOLLEN – FIXED FOR SOME MVS COMPILER'S TREATMENT OF INTERNAL READS (INCREASES PORTABILITY) 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT"; CORRECTED SOME MINOR ERRORS 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION; OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY; CHANGED CALL FROM BORT TO BORT2 2006-04-14 D. KEYSER – ABORTS IF A USER-DEFINED MESSAGE TYPE "011" IS READ (EITHER DIRECTLY FROM A TABLE A MNEMONIC OR FROM THE "Y" VALUE OF A TABLE A FXY SEQUENCE DESCRIPTOR), MESSAGE TYPE "011" IS RESERVED FOR DICTIONARY MESSAGES (PREVIOUSLY WOULD STORE DATA WITH MESSAGE TYPE "011" BUT SUCH MESSAGES WOULD BE SKIPPED OVER WHEN READ) 2007-01-19 J. ATOR – MODIFIED IN RESPONSE TO NUMBCK CHANGES 2009-03-23 J. ATOR – INCREASE SIZE OF BORT_STR2; USE STNTBIA 2013-01-08 J. WHITING – ADD ERR= OPTION TO READ STATEMENT 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL RDUSDX (LUNDX, LUN) INPUT ARGUMENT LIST: LUNDX - INTEGER: FORTRAN LOGICAL UNIT NUMBER FOR USER- SUPPLIED BUFR DICTIONARY TABLE IN CHARACTER FORMAT LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
INPUT FILES: UNIT "LUNDX" - USER-SUPPLIED BUFR DICTIONARY TABLE IN CHARACTER FORMAT
REMARKS:
THIS ROUTINE CALLS: BORT2 DXINIT ELEMDX IGETNTBI MAKESTAB NEMOCK NUMBCK SEQSDX STNTBI STNTBIA THIS ROUTINE IS CALLED BY: CKTABA READDX Normally not called by any application programs.
Definition at line 64 of file rdusdx.f.
References bort2(), dxinit(), elemdx(), igetntbi(), makestab(), nemock(), numbck(), seqsdx(), stntbi(), and stntbia().
Referenced by cktaba(), and readdx().