NCEPLIBS-bufr: readdx.f File Reference
readdx.f File Reference
Read DX BUFR table information into internal arrays.
Functions/Subroutines
subroutine readdx (LUNIT, LUN, LUNDX)
This subroutine initializes modules moda_tababd and moda_msgcwd with DX BUFR (dictionary) tables.
Detailed Description
Read DX BUFR table information into internal arrays.
Author
Woollen
Date
1994-01-06
Definition in file readdx.f.
Function/Subroutine Documentation
readdx()
subroutine readdx (LUNIT, LUN, LUNDX)
This subroutine initializes modules moda_tababd and moda_msgcwd with DX BUFR (dictionary) tables.
These tables are needed to read, write, initialize or append a BUFR file.
The modules are initialized from:
an external, user-supplied BURF dictionary table file (i.e., a BUFR mnemonic table).
the BUFR file indicated by LUNIT.
another currently opened BUFR file.
If the modules are initialized by the BUFF file indicated by LUNIT, then it must have been opened for input processing and positioned at a dictionary table > message somewhere in the file.
Once initialzed, the dictionary arrays are associated with the BUFR file indicated by LUNIT, until the file is closed with closbf().
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file being read, written, initialized or appended.
[in] LUN - integer: I/O stream index into internal memory arrays (associated with file connected to logical unit LUNIT)
[in] LUNDX - integer: Fortran logical unit number containing dictionary table information to be used in reading/ writing from/to LUNIT (depending on the case); may be set equal to LUNIT if dictionary table information is already embedded in LUNIT (but only if LUNIT is being read).
Author
Woollen
Date
1994-01-06
Definition at line 34 of file readdx.f.
References bort(), cpbfdx(), errwrt(), makestab(), rdbfdx(), rdusdx(), and status().
Referenced by openbf(), and writdx().