NCEPLIBS-bufr: rtrcpt.f File Reference
rtrcpt.f File Reference
Read the tank receipt time from Section 1 of a BUFR message.
Functions/Subroutines
subroutine rtrcpt (LUNIT, IYR, IMO, IDY, IHR, IMI, IRET)
This subroutine reads the tank receipt time (if one exists) from Section 1 of a BUFR message.
Detailed Description
Read the tank receipt time from Section 1 of a BUFR message.
Definition in file rtrcpt.f.
Function/Subroutine Documentation
rtrcpt()
subroutine rtrcpt (LUNIT, IYR, IMO, IDY, IHR, IMI, IRET)
This subroutine reads the tank receipt time (if one exists) from Section 1 of a BUFR message.
It is similar to subroutine rtrcptb(), except that rtrcptb() operates on a BUFR message passed in via a memory array, whereas this subroutine operates on the BUFR message that was read into internal arrays via the most recent call to any of the other message-reading subroutines for a specified Fortran logical unit.
Author
J. Ator
Date
2009-03-23
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
[out] IYR – integer: Tank receipt year
[out] IMO – integer: Tank receipt month
[out] IDY – integer: Tank receipt day
[out] IHR – integer: Tank receipt hour
[out] IMI – integer: Tank receipt minute
[out] IRET – integer: return code
0 = normal return
-1 = no tank receipt time exists within the BUFR message currently open for input within internal arrays
Program history log:
Date Programmer Comments
2009-03-23 J. Ator Original author
2013-10-07 J. Ator Modified to call rtrcptb()
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 35 of file rtrcpt.f.
References bort(), moda_bitbuf::mbay, rtrcptb(), and status().