NCEPLIBS-bufr: sinv.F90 File Reference
sinv.F90 File Reference
Produces a BUFR file inventory by satellite type.
Functions/Subroutines
subroutine satcode (lunit, icode, csad, jcode, csid)
This subroutine looks in the master BUFR tables for meaning strings associated with specified code figures for the satellite platform and instrument.
program sinv
Usage: sinv <satbufrfile> will print inventory of satellites by platform and instrument.
Detailed Description
Produces a BUFR file inventory by satellite type.
Looks in the BUFR tables to get meaning strings for satellite platform and instrument codes.
Author
J Woollen
Date
2010
Definition in file sinv.F90.
Function/Subroutine Documentation
satcode()
subroutine satcode (lunit, icode, character(16) csad, jcode, character(80) csid)
This subroutine looks in the master BUFR tables for meaning strings associated with specified code figures for the satellite platform and instrument.
Parameters
[in] lunit - integer: Fortran logical unit number for BUFR file
[in] icode - integer: satellite platform code
[out] csad - character*16: meaning string associated with icode
[in] jcode - integer: satellite instrument code
[out] csid - character*80: meaning string associated with jcode
Author
J Woollen
Date
2010
Definition at line 119 of file sinv.F90.
References getcfmng().
Referenced by sinv().
sinv()
program sinv
Usage: sinv <satbufrfile> will print inventory of satellites by platform and instrument.
Returns
0 for success, error message otherwise.
Author
J Woollen
Date
2010
Definition at line 11 of file sinv.F90.
References bort(), codflg(), mtinfo(), openbf(), readmg(), satcode(), and ufbtab().