NCEPLIBS-bufr: sntbfe.f File Reference
sntbfe.f File Reference
Store a master Code/Flag table entry into internal memory.
Functions/Subroutines
subroutine sntbfe (LUNT, IFXYN, LINE)
This subroutine stores the first line of an entry that was previously read from an ASCII master Code/Flag table file into an internal memory structure.
Detailed Description
Store a master Code/Flag table entry into internal memory.
Definition in file sntbfe.f.
Function/Subroutine Documentation
sntbfe()
subroutine sntbfe (LUNT, IFXYN, character*(*) LINE)
This subroutine stores the first line of an entry that was previously read from an ASCII master Code/Flag table file into an internal memory structure.
It then reads and stores all remaining lines of that same entry into the same internal memory structure.
Author
J. Ator
Date
2017-11-02
Parameters
[in] LUNT – integer: Fortran logical unit number for ASCII file containing Code/Flag table information
[in] IFXYN – integer: Bit-wise representation of FXY number
[in] LINE – character*(*): First line of Code/Flag table entry
Program history log:
Date Programmer Comments
2017-11-02 J. Ator Original author
2021-09-30 J. Ator Replace jstchr with Fortran intrinsic adjustl
Definition at line 25 of file sntbfe.f.
References adn30(), bort2(), ifxy(), igetfxy(), igetntbl(), parstr(), strnum(), and strtbfe().
Referenced by rdmtbf().