NCEPLIBS-bufr: split_by_subset.F90 File Reference
split_by_subset.F90 File Reference
Split a BUFR file into separate BUFR files by subset type.
Functions/Subroutines
program split_by_subset
Read BUFR file messages, collating them into output files by message type/subtype (eg NC001002, aka subset type).
Detailed Description
Split a BUFR file into separate BUFR files by subset type.
Author
Woollen
Date
2000-01-01
Definition in file split_by_subset.F90.
Function/Subroutine Documentation
split_by_subset()
program split_by_subset
Read BUFR file messages, collating them into output files by message type/subtype (eg NC001002, aka subset type).
This is the opposite of combfr.f, which concatenates BUFR messages from listed input files.
Returns
0 for success, error code otherwise.
Author
Woollen
Date
2000-01-01
Definition at line 15 of file split_by_subset.F90.
References bort(), closbf(), copymg(), ireadmg(), iupvs01(), maxout(), nmsub(), and openbf().