NCEPLIBS-bufr: stbfdx.f File Reference
stbfdx.f File Reference
Functions/Subroutines
subroutine stbfdx (LUN, MESG)
THIS SUBROUTINE COPIES A BUFR TABLE (DICTIONARY) MESSAGE FROM THE INPUT ARRAY MESG INTO THE INTERNAL MEMORY ARRAYS IN MODULE TABABD.
Detailed Description
Author
J
Date
2009-03-23
Definition in file stbfdx.f.
Function/Subroutine Documentation
stbfdx()
subroutine stbfdx (LUN, dimension(*) MESG)
THIS SUBROUTINE COPIES A BUFR TABLE (DICTIONARY) MESSAGE FROM THE INPUT ARRAY MESG INTO THE INTERNAL MEMORY ARRAYS IN MODULE TABABD.
PROGRAM HISTORY LOG: 2009-03-23 J. ATOR – ORIGINAL AUTHOR, USING LOGIC COPIED FROM PREVIOUS VERSION OF RDBFDX 2014-11-14 J. ATOR – REPLACE CHRTRNA CALLS WITH UPC CALLS 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL STBFDX (LUN,MESG) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS MESG - INTEGER: *-WORD PACKED BINARY ARRAY CONTAINING BUFR TABLE (DICTIONARY) MESSAGE
REMARKS: THIS ROUTINE CALLS: BORT CAPIT GETLENS IGETNTBI IDN30 IFXY IUPB IUPBS01 NENUBD PKTDD STNTBIA UPC THIS ROUTINE IS CALLED BY: RDBFDX RDMEMM READERME Normally not called by any application programs.
Definition at line 28 of file stbfdx.f.
References bort(), capit(), getlens(), idn30(), moda_tababd::idnb, moda_tababd::idnd, ifxy(), igetntbi(), iupb(), iupbs01(), modv_maxcd::maxcd, nenubd(), moda_tababd::ntbb, moda_tababd::ntbd, pktdd(), stntbia(), moda_tababd::taba, moda_tababd::tabb, moda_tababd::tabd, and upc().
Referenced by rdbfdx(), rdmemm(), and readerme().