NCEPLIBS-bufr: stntbi.f File Reference
stntbi.f File Reference
Store a new entry within the internal BUFR Table B or D.
Functions/Subroutines
subroutine stntbi (N, LUN, NUMB, NEMO, CELSQ)
Store a new entry within the internal BUFR Table B or D.
Detailed Description
Store a new entry within the internal BUFR Table B or D.
Author
Ator
Date
2009-03-23
Definition in file stntbi.f.
Function/Subroutine Documentation
stntbi()
subroutine stntbi (N, LUN, character*(*) NUMB, character*(*) NEMO, character*(*) CELSQ)
Store a new entry within the internal BUFR Table B or D.
This subroutine stores a new entry within internal BUFR Table B or D, depending on the value of NUMB.
Parameters
[in] N - integer: storage index into internal Table B or D.
[in] LUN - integer: File ID.
[in] NUMB - character*6: FXY number for new Table B or D entry (in format FXXYYY).
[in] NEMO - character*8: mnemonic corresponding to NUMB.
[in] CELSQ - character*55: element or sequence description corresponding to NUMB.
Author
Ator
Date
2009-03-23
Definition at line 19 of file stntbi.f.
References moda_tababd::idnb, moda_tababd::idnd, ifxy(), nenubd(), moda_tababd::ntbb, moda_tababd::ntbd, moda_tababd::tabb, and moda_tababd::tabd.
Referenced by rdusdx(), and bufr_c2f_interface::stntbi_c().