NCEPLIBS-bufr: strbtm.f File Reference
strbtm.f File Reference
Functions/Subroutines
subroutine strbtm (N, LUN)
THIS SUBROUTINE STORES INTERNAL INFORMATION IN MODULE BITMAPS IF THE INPUT ELEMENT IS PART OF A BITMAP.
Detailed Description
Author
J
Date
2016-05-27
Definition in file strbtm.f.
Function/Subroutine Documentation
strbtm()
subroutine strbtm (N, LUN)
THIS SUBROUTINE STORES INTERNAL INFORMATION IN MODULE BITMAPS IF THE INPUT ELEMENT IS PART OF A BITMAP.
PROGRAM HISTORY LOG: 2016-05-27 J. ATOR – ORIGINAL AUTHOR 2019-05-22 J. ATOR – ADD CONFIRMATION CHECK
USAGE: CALL STRBTM (N, LUN) INPUT ARGUMENT LIST: N - INTEGER: SUBSET ELEMENT LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
THIS ROUTINE CALLS: BORT IBFMS LSTJPB THIS ROUTINE IS CALLED BY: RCSTPL RDCMPS Normally not called by any application programs.
Definition at line 21 of file strbtm.f.
References bort(), moda_bitmaps::ctco, ibfms(), moda_bitmaps::ibtmse, moda_bitmaps::inodtamc, moda_bitmaps::inodtco, moda_tables::isc, moda_bitmaps::istbtm, moda_bitmaps::iszbtm, moda_tables::itp, moda_bitmaps::linbtm, lstjpb(), modv_mxbtm::mxbtm, modv_mxbtmse::mxbtmse, moda_bitmaps::nbtm, moda_bitmaps::nbtmse, moda_bitmaps::ntamc, moda_bitmaps::ntco, and moda_tables::tag.
Referenced by rcstpl(), and rdcmps().