NCEPLIBS-bufr: strnum.f File Reference
strnum.f File Reference
Decode an integer from a character string.
Functions/Subroutines
subroutine strnum (STR, NUM)
This subroutine decodes an integer from a character string.
Detailed Description
Decode an integer from a character string.
Definition in file strnum.f.
Function/Subroutine Documentation
subroutine strnum (character*(*) STR, NUM)
This subroutine decodes an integer from a character string.
The string should contain only digits and (optional) trailing blanks. It should not contain any sign ('+' or '-') character nor any leading blanks nor embedded blanks.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] STR – character*(*): String
[out] NUM – integer: Value decoded from STR
-1 = decode was unsuccessful
Program History Log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
2003-11-04 J. Ator Added documentation
2009-04-21 J. Ator Use errwrt()
Definition at line 23 of file strnum.f.
References errwrt(), and strsuc().
Referenced by fdebufr(), jstnum(), parutg(), seqsdx(), sntbfe(), and stseq().