NCEPLIBS-bufr: tabent.f File Reference
tabent.f File Reference
Store an entry for a Table B or D mnemonic within the internal jump/link table.
Functions/Subroutines
subroutine tabent (LUN, NEMO, TAB, ITAB, IREP, IKNT, JUM0)
This subroutine builds and stores an entry for a Table B or Table D mnemonic within the internal jump/link table.
Detailed Description
Store an entry for a Table B or D mnemonic within the internal jump/link table.
Author
Woollen
Date
1994-01-06
Definition in file tabent.f.
Function/Subroutine Documentation
tabent()
subroutine tabent (LUN, character*8 NEMO, character*1 TAB, ITAB, IREP, IKNT, JUM0)
This subroutine builds and stores an entry for a Table B or Table D mnemonic within the internal jump/link table.
Parameters
[in] LUN - integer: I/O stream index into internal memory arrays.
[in] NEMO - character*8: Table B or D mnemonic to store in jump/link table.
[in] TAB - character*1: internal BUFR table array ('B' or 'D') in which NEMO is defined.
[in] ITAB - integer: positional index of NEMO within TAB.
[in] IREP - integer: positional index within common /reptab/ arrays, for use when NEMO is replicated:
0, if NEMO is not replicated.
[in] IKNT - integer: number of replications, for use when NEMO is replicated using F=1 regular (i.e., non-delayed) replication:
0, if NEMO is not replicated using F=1 regular (i.e., non-delayed) replication
[in] JUM0 - integer: index value to be stored for NEMO within internal jump/link table array jmpb(*).
Author
Woollen
Date
1994-01-06
Definition at line 22 of file tabent.f.
References bort(), moda_tables::ibt, moda_nrv203::ibtnrv, inctab(), moda_nrv203::inodnrv, moda_nrv203::ipfnrv, moda_tables::irf, moda_tables::isc, moda_nrv203::isnrv, moda_tables::jmpb, moda_tables::jump, moda_tables::link, modv_mxnrv::mxnrv, nemtbb(), moda_nrv203::nnrv, and moda_nrv203::tagnrv.
Referenced by tabsub().