NCEPLIBS-bufr: tabsub.f File Reference
tabsub.f File Reference
Functions/Subroutines
subroutine tabsub (LUN, NEMO)
THIS SUBROUTINE BUILDS THE ENTIRE JUMP/LINK TREE (I.E., INCLUDING RECURSIVELY RESOLVING ALL "CHILD" MNEMONICS) FOR A TABLE A MNEMONIC (NEMO) WITHIN THE INTERNAL JUMP/LINK TABLE.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file tabsub.f.
Function/Subroutine Documentation
tabsub()
subroutine tabsub (LUN, character*8 NEMO)
THIS SUBROUTINE BUILDS THE ENTIRE JUMP/LINK TREE (I.E., INCLUDING RECURSIVELY RESOLVING ALL "CHILD" MNEMONICS) FOR A TABLE A MNEMONIC (NEMO) WITHIN THE INTERNAL JUMP/LINK TABLE.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 2000-09-19 J. WOOLLEN – ADDED CAPABILITY TO ENCODE AND DECODE DATA USING THE OPERATOR DESCRIPTORS (BUFR TABLE C) FOR CHANGING WIDTH AND CHANGING SCALE 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION; OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2005-11-29 J. ATOR – ADDED SUPPORT FOR 207 AND 208 OPERATORS 2012-03-02 J. ATOR – ADDED SUPPORT FOR 203 OPERATOR 2012-04-19 J. ATOR – FIXED BUG FOR CASES WHERE A TABLE C OPERATOR IMMEDIATELY FOLLOWS A TABLE D SEQUENCE 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS 2016-05-24 J. ATOR – STORE TABLE C OPERATORS IN MODULE BITMAPS 2017-04-03 J. ATOR – ADD A DIMENSION TO ALL TCO ARRAYS SO THAT EACH SUBSET DEFINITION IN THE JUMP/LINK TABLE HAS ITS OWN SET OF TABLE C OPERATORS
USAGE: CALL TABSUB (LUN, NEMO) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS NEMO - CHARACTER*8: TABLE A MNEMONIC
THIS ROUTINE CALLS: BORT INCTAB IOKOPER NEMTAB NEMTBD TABENT THIS ROUTINE IS CALLED BY: MAKESTAB Normally not called by any application programs.
Definition at line 46 of file tabsub.f.
References bort(), moda_bitmaps::ctco, moda_tables::ibt, moda_nrv203::ibtnrv, moda_nrv203::ienrv, inctab(), moda_bitmaps::inodtamc, moda_bitmaps::inodtco, iokoper(), moda_nrv203::ipfnrv, moda_tables::irf, moda_tables::isc, moda_tables::jmpb, moda_tables::jump, moda_tables::link, modv_mxtamc::mxtamc, modv_mxtco::mxtco, nemtab(), nemtbd(), moda_nrv203::nnrv, moda_tables::ntab, moda_bitmaps::ntamc, moda_bitmaps::ntco, and tabent().
Referenced by makestab().