NCEPLIBS-bufr: ufbmms.f File Reference
ufbmms.f File Reference
Read a specified data subset from internal arrays.
Functions/Subroutines
recursive subroutine ufbmms (IMSG, ISUB, SUBSET, JDATE)
Read a specified data subset from internal arrays.
Detailed Description
Read a specified data subset from internal arrays.
Author
J. Woollen
Date
1994-01-06
Definition in file ufbmms.f.
Function/Subroutine Documentation
ufbmms()
recursive subroutine ufbmms (IMSG, ISUB, character*8 SUBSET, JDATE)
Read a specified data subset from internal arrays.
This subroutine provides a handy way to combine the functionality of subroutines rdmemm() and rdmems() within a single subroutine call.
Whenever this subroutine returns successfully, the requested data subset can now be easily manipulated or further parsed via calls to any of the values-reading subroutines using the Fortran logical unit number IUNIT that was returned from the most recent call to subroutine ufbmem().
Parameters
[in] IMSG - integer: Number of BUFR message to be read into scope for further processing, counting from the beginning of the internal arrays in memory.
[in] ISUB - integer: Number of data subset to be read from the (IMSG)th BUFR message, counting from the beginning of the message.
[out] SUBSET - character*8: Table A mnemonic for type of (IMSG)th BUFR message (see DX BUFR Tables for further information about Table A mnemonics).
[out] JDATE - integer: Date-time stored within Section 1 of (IMSG)th BUFR message, in format of either YYMMDDHH or YYYYMMDDHH, depending on the most recent call to subroutine datelen().
Author
J. Woollen
Date
1994-01-06
Definition at line 31 of file ufbmms.f.
References bort(), modv_im8b::im8b, moda_msgmem::msgp, moda_msgcwd::msub, moda_msgmem::munit, rdmemm(), rdmems(), status(), x48(), and x84().