NCEPLIBS-bufr: ufbovr.f File Reference
ufbovr.f File Reference
Functions/Subroutines
subroutine ufbovr (LUNIT, USR, I1, I2, IRET, STR)
THIS SUBROUTINE WRITES OVER SPECIFIED VALUES WHICH EXIST IN CURRENT INTERNAL BUFR SUBSET ARRAYS IN A FILE OPEN FOR OUTPUT.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file ufbovr.f.
Function/Subroutine Documentation
subroutine ufbovr (LUNIT, real*8, dimension(i1,i2) USR, I1, I2, IRET, character*(*) STR)
THIS SUBROUTINE WRITES OVER SPECIFIED VALUES WHICH EXIST IN CURRENT INTERNAL BUFR SUBSET ARRAYS IN A FILE OPEN FOR OUTPUT.
THE DATA VALUES CORRESPOND TO MNEMONICS WHICH ARE PART OF A DELAYED-REPLICATION SEQUENCE, OR FOR WHICH THERE IS NO REPLICATION AT ALL. EITHER BUFR ARCHIVE LIBRARY SUBROUTINE OPENMG OR OPENMB MUST HAVE BEEN PREVIOUSLY CALLED TO OPEN AND INITIALIZE A BUFR MESSAGE WITHIN MEMORY FOR THIS LUNIT. IN ADDITION, BUFR ARCHIVE LIBRARY SUBROUTINE WRITSB OR INVMRG MUST HAVE BEEN CALLED TO STORE DATA IN THE INTERNAL OUTPUT SUBSET ARRAYS.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2002-05-14 J. WOOLLEN – REMOVED OLD CRAY COMPILER DIRECTIVES 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY OR UNUSUAL THINGS HAPPEN; CHANGED CALL FROM BORT TO BORT2 IN SOME CASES 2004-08-18 J. ATOR – ADDED SAVE FOR IFIRST1 AND IFIRST2 FLAGS 2009-04-21 J. ATOR – USE ERRWRT 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS 2015-09-24 D. STOKES – FIX MISSING DECLARATION OF COMMON /QUIET/
USAGE: CALL UFBOVR (LUNIT, USR, I1, I2, IRET, STR) INPUT ARGUMENT LIST: LUNIT - INTEGER: FORTRAN LOGICAL UNIT NUMBER FOR BUFR FILE USR - REAL*8: (I1,I2) STARTING ADDRESS OF DATA VALUES WRITTEN TO DATA SUBSET I1 - INTEGER: LENGTH OF FIRST DIMENSION OF USR (MUST BE AT LEAST AS LARGE AS THE NUMBER OF BLANK-SEPARATED MNEMONICS IN STR) I2 - INTEGER: NUMBER OF "LEVELS" OF DATA VALUES TO BE WRITTEN TO DATA SUBSET STR - CHARACTER*(*): STRING OF BLANK-SEPARATED TABLE B MNEMONICS IN ONE-TO-ONE CORRESPONDENCE WITH FIRST DIMENSION OF USR
OUTPUT ARGUMENT LIST: IRET - INTEGER: NUMBER OF "LEVELS" OF DATA VALUES WRITTEN TO DATA SUBSET (SHOULD BE SAME AS I2)
REMARKS: THIS ROUTINE CALLS: BORT BORT2 ERRWRT STATUS STRING TRYBUMP THIS ROUTINE IS CALLED BY: None Normally called only by application programs.
Definition at line 64 of file ufbovr.f.
References bort(), bort2(), errwrt(), status(), string(), and trybump().