NCEPLIBS-bufr: ufbqcp.f File Reference
ufbqcp.f File Reference
Functions/Subroutines
subroutine ufbqcp (LUNIT, QCP, NEMO)
THIS SUBROUTINE READS IN A FXY DESCRIPTOR ENTRY (Y) FOR A SEQUENCE DESCRIPTOR (F=3) WITH TABLE D CATEGORY 63 (X=63) WHEN THE DESCRIPTOR IS KNOWN TO BE IN THE BUFR TABLE IN LOGICAL UNIT LUNIT, AND RETURNS THE MNEMONIC ASSOCIATED WITH IT.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file ufbqcp.f.
Function/Subroutine Documentation
ufbqcp()
subroutine ufbqcp (LUNIT, QCP, character*(*) NEMO)
THIS SUBROUTINE READS IN A FXY DESCRIPTOR ENTRY (Y) FOR A SEQUENCE DESCRIPTOR (F=3) WITH TABLE D CATEGORY 63 (X=63) WHEN THE DESCRIPTOR IS KNOWN TO BE IN THE BUFR TABLE IN LOGICAL UNIT LUNIT, AND RETURNS THE MNEMONIC ASSOCIATED WITH IT.
THIS ROUTINE WILL NOT WORK FOR ANY OTHER TYPE OF DESCRIPTOR OR ANY OTHER SEQUENCE DESCRIPTOR TABLE D CATEGORY. LUNIT MUST ALREADY BE OPENED FOR INPUT OR OUTPUT VIA A CALL TO BUFR ARCHIVE LIBRARY SUBROUTINE OPENBF. THIS ROUTINE IS ESPECIALLY USEFUL WHEN THE CALLING PROGRAM IS READING "EVENTS" FROM AN INPUT BUFR FILE IN LUNIT (USUALLY THE "PREPBUFR" FILE) SINCE THE DESCRIPTOR ENTRY (Y) HERE DEFINES THE EVENT PROGRAM CODE. THUS, THE CALLING PROGRAM CAN OBTAIN THE MNEMONIC NAME ASSOCIATED WITH AN EVENT PROGRAM CODE.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY
USAGE: CALL UFBQCP (LUNIT, QCP, NEMO) INPUT ARGUMENT LIST: LUNIT - INTEGER: FORTRAN LOGICAL UNIT NUMBER FOR BUFR FILE (ASSOCIATED BUFR TABLE MAY BE INTERNAL OR EXTERNAL) QCP - REAL: SEQUENCE DESCRIPTOR ENTRY (I.E., EVENT PROGRAM CODE) (Y IN FXY DESCRIPTOR)
OUTPUT ARGUMENT LIST: NEMO - CHARACTER*(*): MNEMONIC IN BUFR TABLE ASSOCIATED WITH SEQUENCE DESCRIPTOR FXY WHERE F=3 AND X=63 AND Y=INT(QCP)
REMARKS: THIS SUBROUTINE IS THE INVERSE OF BUFR ARCHIVE LIBRARY ROUTINE UFBQCD.
THIS ROUTINE CALLS: BORT IFXY NUMTAB STATUS THIS ROUTINE IS CALLED BY: None Normally called only by application programs.
Definition at line 50 of file ufbqcp.f.
References bort(), ifxy(), numtab(), and status().