NCEPLIBS-bufr: valx.f File Reference
valx.f File Reference
Decode a real number from a character string.
Functions/Subroutines
function valx (STR)
This function decodes a real number from a character string.
Detailed Description
Decode a real number from a character string.
Definition in file valx.f.
Function/Subroutine Documentation
valx()
function valx (character*(*) STR)
This function decodes a real number from a character string.
The string may contain a leading sign ('+' or '-') character. If the decode fails for any reason, then the current placeholder value for "missing" data is returned.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] STR – character*(*): String
Returns
VALX – real: Value decoded from STR
Program History Log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1998-07-08 J. Woollen Replaced call to CRAY library routine "ABORT" with call to new internal routine bort()
1999-11-18 J. Woollen Renamed from val$ to valx because the $ symbol causes problems on certain platforms
2003-11-04 D. Keyser Use bort2() instead of bort()
2009-04-21 J. Ator Use errwrt()
2021-09-30 J. Ator Replace rjust with Fortran intrinsic adjustr
Definition at line 25 of file valx.f.
References modv_bmiss::bmiss, bort2(), errwrt(), and valx().
Referenced by gettbh(), nemtbb(), upftbv(), and valx().