NCEPLIBS-bufr: writcp.f File Reference
writcp.f File Reference
Write a data subset into a BUFR message using compression.
Functions/Subroutines
recursive subroutine writcp (LUNIT)
Write a data subset into a BUFR message using compression.
Detailed Description
Write a data subset into a BUFR message using compression.
Author
J. Woollen
Date
2002-05-14
Definition in file writcp.f.
Function/Subroutine Documentation
writcp()
recursive subroutine writcp (LUNIT)
Write a data subset into a BUFR message using compression.
This subroutine is similar to subroutine writsb(), except that when the subset is encoded and packed into the current message for the BUFR file associated with logical unit LUNIT, it is packed using compression as prescribed within the official WMO BUFR regulations.
This subroutine activates compression via an internal call to subroutine cmpmsg(), followed by an internal call to subroutine writsb(), followed by a second internal call to subroutine cmpmsg() to deactivate compression. For this reason, most application programs which write compressed BUFR messages now call subroutines cmpmsg() and writsb() directly; however, this subroutine is still supported within the BUFRLIB software for backwards-compatibility with certain legacy application programs.
Parameters
[in] lunit - integer: Fortran logical unit number for BUFR file.
Author
J. Woollen
Date
2002-05-14
Definition at line 27 of file writcp.f.
References cmpmsg(), modv_im8b::im8b, writsb(), and x84().