NCEPLIBS-bufr: wrtree.f File Reference
wrtree.f File Reference
Functions/Subroutines
subroutine wrtree (LUN)
THIS SUBROUTINE CONVERTS USER NUMBERS INTO SCALED INTEGERS AND PACKS THE USER ARRAY INTO THE SUBSET BUFFER.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file wrtree.f.
Function/Subroutine Documentation
subroutine wrtree (LUN)
THIS SUBROUTINE CONVERTS USER NUMBERS INTO SCALED INTEGERS AND PACKS THE USER ARRAY INTO THE SUBSET BUFFER.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – CORRECTED SOME MINOR ERRORS 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2000-09-19 J. WOOLLEN – MAXIMUM MESSAGE LENGTH INCREASED FROM 10,000 TO 20,000 BYTES 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); REPL. "IVAL(N)=ANINT(PKS(NODE))" WITH "IVAL(N)=NINT(PKS(NODE))" (FORMER CAUSED PROBLEMS ON SOME FOREIGN MACHINES) 2004-03-10 J. WOOLLEN – CONVERTED PACKING FUNCTION 'PKS' TO REAL*8 2004-08-09 J. ATOR – MAXIMUM MESSAGE LENGTH INCREASED FROM 20,000 TO 50,000 BYTES 2007-01-19 J. ATOR – PREVENT OVERFLOW OF CVAL FOR STRINGS LONGER THAN 8 CHARACTERS; USE FUNCTION IBFMS 2009-08-03 J. WOOLLEN – ADDED CAPABILITY TO COPY LONG STRINGS VIA UFBCPY USING FILE POINTER STORED IN NEW COMMON UFBCPL 2012-03-02 J. ATOR – USE IPKS TO HANDLE 2-03 OPERATOR CASES 2012-06-04 J. ATOR – ENSURE "MISSING" CHARACTER FIELDS ARE PROPERLY ENCODED WITH ALL BITS SET TO 1 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL WRTREE (LUN) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
REMARKS: THIS ROUTINE CALLS: IBFMS IPKM PKB PKC IPKS READLC THIS ROUTINE IS CALLED BY: WRITSA WRITSB Normally not called by any application programs.
Definition at line 49 of file wrtree.f.
References ibfms(), ipkm(), ipks(), pkb(), pkc(), and readlc().
Referenced by writsa(), and writsb().