NCEPLIBS-bufr: wtstat.f File Reference
wtstat.f File Reference
Update the status of a system file with respect to the BUFRLIB software.
Functions/Subroutines
subroutine wtstat (LUNIT, LUN, IL, IM)
This subroutine can be used to connect or disconnect a specified Fortran logical unit number to/from the BUFRLIB software, and it can also be used to set or reset the internal message status associated with that logical unit number.
Detailed Description
Update the status of a system file with respect to the BUFRLIB software.
Definition in file wtstat.f.
Function/Subroutine Documentation
wtstat()
subroutine wtstat (LUNIT, LUN, IL, IM)
This subroutine can be used to connect or disconnect a specified Fortran logical unit number to/from the BUFRLIB software, and it can also be used to set or reset the internal message status associated with that logical unit number.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
[in] LUN – integer: Internal I/O stream index associated with LUNIT
[in] IL – integer: File status update option
0 = Disconnect LUNIT from the software
1 = Connect LUNIT to the software for output operations (i.e. writing/encoding BUFR), if not already connected
-1 = Connect LUNIT to the software for input operations (i.e. reading/decoding BUFR), if not already connected
[in] IM – integer: Message status update option, to indicate whether a message is now open within the internal arrays for LUNIT
0 = No
1 = Yes
Before this subroutine is called to connect any LUNIT to the software, a previous call should have been made to subroutine status() to confirm that internal space is available to connect the associated file, as well as to obtain an LUN value to use in connecting it. Once a file is connected, the corresponding LUNIT and LUN values remain linked to each other for as long as the file is connected to the software.
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1998-07-08 J. Woollen Replaced call to Cray library routine ABORT with call to new internal routine bort()
1999-11-18 J. Woollen The number of BUFR files which can be opened at one time increased from 10 to 32
2003-11-04 J. Ator Corrected a typo in test for IM validity; added documentation
2003-11-04 S. Bender Added remarks and routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added documentation; outputs more complete diagnostic info when routine terminates abnormally
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 52 of file wtstat.f.
References bort().
Referenced by closbf(), closmg(), openbf(), openmb(), openmg(), rdmemm(), readerme(), readmg(), and rewnbf().