//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.04.12 at 04:45:24 PM EDT 
//


package TableB14.jabx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="No" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ClassNo" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ClassName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FXY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ElementName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BUFR_Unit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BUFR_Scale" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BUFR_ReferenceValue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BUFR_DataWidth_Bits" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CREX_Unit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CREX_Scale" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CREX_DataWidth" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Status" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Notes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="536870910"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "no",
    "classNo",
    "className",
    "fxy",
    "elementName",
    "bufrUnit",
    "bufrScale",
    "bufrReferenceValue",
    "bufrDataWidthBits",
    "crexUnit",
    "crexScale",
    "crexDataWidth",
    "status",
    "notes"
})
@XmlRootElement(name = "Exporting_BCTableB_E")
public class ExportingBCTableBE {

    @XmlElement(name = "No")
    protected Integer no;
    @XmlElement(name = "ClassNo")
    protected String classNo;
    @XmlElement(name = "ClassName")
    protected String className;
    @XmlElement(name = "FXY")
    protected String fxy;
    @XmlElement(name = "ElementName")
    protected String elementName;
    @XmlElement(name = "BUFR_Unit")
    protected String bufrUnit;
    @XmlElement(name = "BUFR_Scale")
    protected String bufrScale;
    @XmlElement(name = "BUFR_ReferenceValue")
    protected String bufrReferenceValue;
    @XmlElement(name = "BUFR_DataWidth_Bits")
    protected String bufrDataWidthBits;
    @XmlElement(name = "CREX_Unit")
    protected String crexUnit;
    @XmlElement(name = "CREX_Scale")
    protected String crexScale;
    @XmlElement(name = "CREX_DataWidth")
    protected String crexDataWidth;
    @XmlElement(name = "Status")
    protected String status;
    @XmlElement(name = "Notes")
    protected String notes;

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNo(Integer value) {
        this.no = value;
    }

    /**
     * Gets the value of the classNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassNo() {
        return classNo;
    }

    /**
     * Sets the value of the classNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassNo(String value) {
        this.classNo = value;
    }

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the fxy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFXY() {
        return fxy;
    }

    /**
     * Sets the value of the fxy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFXY(String value) {
        this.fxy = value;
    }

    /**
     * Gets the value of the elementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementName() {
        return elementName;
    }

    /**
     * Sets the value of the elementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementName(String value) {
        this.elementName = value;
    }

    /**
     * Gets the value of the bufrUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUFRUnit() {
        return bufrUnit;
    }

    /**
     * Sets the value of the bufrUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUFRUnit(String value) {
        this.bufrUnit = value;
    }

    /**
     * Gets the value of the bufrScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUFRScale() {
        return bufrScale;
    }

    /**
     * Sets the value of the bufrScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUFRScale(String value) {
        this.bufrScale = value;
    }

    /**
     * Gets the value of the bufrReferenceValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUFRReferenceValue() {
        return bufrReferenceValue;
    }

    /**
     * Sets the value of the bufrReferenceValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUFRReferenceValue(String value) {
        this.bufrReferenceValue = value;
    }

    /**
     * Gets the value of the bufrDataWidthBits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUFRDataWidthBits() {
        return bufrDataWidthBits;
    }

    /**
     * Sets the value of the bufrDataWidthBits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUFRDataWidthBits(String value) {
        this.bufrDataWidthBits = value;
    }

    /**
     * Gets the value of the crexUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREXUnit() {
        return crexUnit;
    }

    /**
     * Sets the value of the crexUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREXUnit(String value) {
        this.crexUnit = value;
    }

    /**
     * Gets the value of the crexScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREXScale() {
        return crexScale;
    }

    /**
     * Sets the value of the crexScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREXScale(String value) {
        this.crexScale = value;
    }

    /**
     * Gets the value of the crexDataWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCREXDataWidth() {
        return crexDataWidth;
    }

    /**
     * Sets the value of the crexDataWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCREXDataWidth(String value) {
        this.crexDataWidth = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

}
