//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.12 at 03:38:32 PM EDT 
//


package C2.jabx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="No" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DateOfAssignment" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="rara" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BUFR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RadiosondeSoundingSystemUsed_E" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Status" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "no",
    "dateOfAssignment",
    "rara",
    "bufr",
    "radiosondeSoundingSystemUsedE",
    "status"
})
@XmlRootElement(name = "Exporting_CommonCodeTableC2_E")
public class ExportingCommonCodeTableC2E {

    @XmlElement(name = "No")
    protected Integer no;
    @XmlElement(name = "DateOfAssignment")
    protected String dateOfAssignment;
    protected String rara;
    @XmlElement(name = "BUFR")
    protected String bufr;
    @XmlElement(name = "RadiosondeSoundingSystemUsed_E")
    protected String radiosondeSoundingSystemUsedE;
    @XmlElement(name = "Status")
    protected String status;

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNo(Integer value) {
        this.no = value;
    }

    /**
     * Gets the value of the dateOfAssignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfAssignment() {
        return dateOfAssignment;
    }

    /**
     * Sets the value of the dateOfAssignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfAssignment(String value) {
        this.dateOfAssignment = value;
    }

    /**
     * Gets the value of the rara property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRara() {
        return rara;
    }

    /**
     * Sets the value of the rara property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRara(String value) {
        this.rara = value;
    }

    /**
     * Gets the value of the bufr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUFR() {
        return bufr;
    }

    /**
     * Sets the value of the bufr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUFR(String value) {
        this.bufr = value;
    }

    /**
     * Gets the value of the radiosondeSoundingSystemUsedE property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadiosondeSoundingSystemUsedE() {
        return radiosondeSoundingSystemUsedE;
    }

    /**
     * Sets the value of the radiosondeSoundingSystemUsedE property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadiosondeSoundingSystemUsedE(String value) {
        this.radiosondeSoundingSystemUsedE = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
