NCEPLIBS-bufr: bort.f File Reference
bort.f File Reference
Log one error message and abort application program.
Functions/Subroutines
subroutine bort (STR)
This subroutine calls subroutine errwrt() to log an error message, then calls subroutine bort_exit() to abort the application program.
Detailed Description
Log one error message and abort application program.
Definition in file bort.f.
Function/Subroutine Documentation
subroutine bort (character*(*) STR)
This subroutine calls subroutine errwrt() to log an error message, then calls subroutine bort_exit() to abort the application program.
It is similar to subroutine bort2(), except that bort2() logs two error messages instead of one.
Author
J. Woollen
Date
1998-07-08
Parameters
[in] STR - character*(*): Error message
Program history log:
1998-07-08 J. Woollen – Original author
2003-11-04 J. Ator – Added documentation; replaced call to intrinsic C routine "exit" with call to bort_exit() to ensure return of non-zero status code
2009-04-21 J. Ator – Use errwrt()
Definition at line 23 of file bort.f.
References bort_exit(), and errwrt().
Referenced by adn30(), arallocc(), arallocf(), atrcpt(), bvers(), chekstab(), cktaba(), closmg(), cmpmsg(), cmsgini(), cnved4(), cobfl(), codflg(), copybf(), copymg(), copysb(), cpdxmm(), cpymem(), cpyupd(), crbmg(), cwbmg(), datebf(), datelen(), drfini(), dumpbf(), dxdump(), dxmini(), getcfmng(), gettbh(), getwin(), idn30(), ifbget(), igetntbi(), igetrfel(), igetsc(), igettdi(), inctab(), inittbf(), invmrg(), ipkm(), isize(), iupm(), iupvs01(), jstnum(), lcmgdf(), lstjpb(), makestab(), minimg(), msgini(), msgwrt(), nemtba(), nemtbax(), nemtbb(), nemtbd(), nenubd(), nevn(), newwin(), nmsub(), nummtb(), nvnwin(), nxtwin(), openbf(), openmb(), openmg(), pad(), padmsg(), parutg(), pkb(), pkbs1(), pkvs01(), posapx(), rcstpl(), rdbfdx(), rdcmps(), rdmemm(), rdmems(), rdmgsb(), rdmtbb(), rdmtbd(), rdmtbf(), readdx(), readerme(), readlc(), readmg(), readns(), reads3(), readsb(), rewnbf(), rtrcpt(), sntbbe(), sntbde(), split_by_subset(), status(), stbfdx(), stdmsg(), stndrd(), stntbia(), strbtm(), strcpt(), strtbfe(), stseq(), tabent(), tabsub(), ufbcnt(), ufbcpy(), ufbcup(), ufbdmp(), ufbevn(), ufbget(), ufbin3(), ufbint(), ufbinx(), ufbmem(), ufbmex(), ufbmms(), ufbmns(), ufbovr(), ufbpos(), ufbqcd(), ufbqcp(), ufbrep(), ufbrms(), ufbseq(), ufbstp(), ufbtab(), ufbtam(), ufdump(), upds3(), upftbv(), uptdd(), usrtpl(), wrcmps(), wrdesc(), wrdlen(), wrdxtb(), writdx(), writlc(), writsa(), writsb(), and wtstat().