NCEPLIBS-bufr: bort2.f File Reference
bort2.f File Reference
Log two error messages and abort application program.
Functions/Subroutines
subroutine bort2 (STR1, STR2)
This subroutine calls subroutine errwrt() to log two error messages, then calls subroutine bort_exit() to abort the application program.
Detailed Description
Log two error messages and abort application program.
Definition in file bort2.f.
Function/Subroutine Documentation
subroutine bort2 (character*(*) STR1, character*(*) STR2)
This subroutine calls subroutine errwrt() to log two error messages, then calls subroutine bort_exit() to abort the application program.
It is similar to subroutine bort(), except that bort() logs one error message instead of two.
Author
D. Keyser
Date
2003-11-04
Parameters
[in] STR1 - character*(*): First error message
[in] STR2 - character*(*): Second error message
Program history log:
2003-11-04 D. Keyser – Original author
2009-04-21 J. Ator – Use errwrt()
Definition at line 20 of file bort2.f.
References bort_exit(), and errwrt().
Referenced by elemdx(), getntbe(), ireadmt(), mtfnam(), mtinfo(), parstr(), parusr(), parutg(), rdusdx(), seqsdx(), sntbbe(), sntbde(), sntbfe(), string(), ufbint(), ufbovr(), ufbrep(), ufbstp(), and valx().