NCEPLIBS-bufr: minimg.f File Reference
minimg.f File Reference
Write a minutes value into Section 1 of a BUFR message.
Functions/Subroutines
subroutine minimg (LUNIT, MINI)
This subroutine writes a minutes value into Section 1 of the BUFR message that was most recently opened for writing via a call to one of the message-writing subroutines for a specified Fortran logical unit.
Detailed Description
Write a minutes value into Section 1 of a BUFR message.
Definition in file minimg.f.
Function/Subroutine Documentation
subroutine minimg (LUNIT, MINI)
This subroutine writes a minutes value into Section 1 of the BUFR message that was most recently opened for writing via a call to one of the message-writing subroutines for a specified Fortran logical unit.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file
[in] MINI - integer: Minutes value
Program history log:
1994-01-06 J. Woollen – Original author
1998-07-08 J. Woollen – Replaced call to Cray library routine ABORT with call to new internal routine bort()
1999-11-18 J. Woollen – The number of BUFR files which can be opened at one time increased from 10 to 32 (necessary in order to process multiple BUFR files under the MPI)
2000-09-19 J. Woollen – Maximum message length increased from 10,000 to 20,000 bytes
2002-05-14 J. Woollen – Changed from an entry point to increase portability to other platforms
2003-11-04 J. Ator – Added documentation
2004-08-09 J. Ator – Maximum message length increased from 20,000 to 50,000 bytes
2005-11-29 J. Ator – Use pkbs1()
2014-12-10 J. Ator – Use modules instead of COMMON blocks
Definition at line 34 of file minimg.f.
References bort(), pkbs1(), and status().