NCEPLIBS-bufr: rdtree.f File Reference
rdtree.f File Reference
Functions/Subroutines
subroutine rdtree (LUN, IRET)
THIS SUBROUTINE UNPACKS THE NEXT SUBSET FROM THE INTERNAL UNCOMPRESSED MESSAGE BUFFER (ARRAY MBAY IN MODULE BITBUF) AND STORES THE UNPACKED SUBSET WITHIN THE INTERNAL ARRAY VAL(*,LUN) IN MODULE USRINT.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file rdtree.f.
Function/Subroutine Documentation
subroutine rdtree (LUN, IRET)
THIS SUBROUTINE UNPACKS THE NEXT SUBSET FROM THE INTERNAL UNCOMPRESSED MESSAGE BUFFER (ARRAY MBAY IN MODULE BITBUF) AND STORES THE UNPACKED SUBSET WITHIN THE INTERNAL ARRAY VAL(*,LUN) IN MODULE USRINT.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-10-27 J. WOOLLEN – MODIFIED TO CORRECT PROBLEMS CAUSED BY IN- LINING CODE WITH FPP DIRECTIVES 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2000-09-19 J. WOOLLEN – MAXIMUM MESSAGE LENGTH INCREASED FROM 10,000 TO 20,000 BYTES 2003-11-04 J. WOOLLEN – FIXED A BUG WHICH COULD ONLY OCCUR WHEN THE LAST ELEMENT IN A SUBSET IS A CHARACTER 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY) 2004-08-09 J. ATOR – MAXIMUM MESSAGE LENGTH INCREASED FROM 20,000 TO 50,000 BYTES 2007-01-19 J. ATOR – PREVENT OVERFLOW OF CVAL FOR STRINGS LONGER THAN 8 CHARACTERS 2012-03-02 J. ATOR – USE FUNCTION UPS 2012-06-04 J. ATOR – SET DECODED REAL*8 VALUE TO "MISSING" WHEN CORRESPONDING CHARACTER FIELD HAS ALL BITS SET TO 1 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS 2016-11-09 J. ATOR – ADDED IRET ARGUMENT AND CHECK FOR POSSIBLY CORRUPT SUBSETS
USAGE: CALL RDTREE (LUN,IRET) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
OUTPUT ARGUMENT LIST: IRET - INTEGER: RETURN CODE: 0 = NORMAL RETURN -1 = AN ERROR OCCURRED, POSSIBLY DUE TO A CORRUPT SUBSET IN THE INPUT MESSAGE
REMARKS: THIS ROUTINE CALLS: RCSTPL ICBFMS UPBB UPC UPS THIS ROUTINE IS CALLED BY: READSB Normally not called by any application programs.
Definition at line 57 of file rdtree.f.
References icbfms(), rcstpl(), upbb(), upc(), and ups().
Referenced by readsb().