NCEPLIBS-bufr: sntbde.f File Reference
sntbde.f File Reference
Functions/Subroutines
subroutine sntbde (LUNT, IFXYN, LINE, MXMTBD, MXELEM, NMTBD, IMFXYN, CMMNEM, CMDSC, CMSEQ, NMELEM, IEFXYN, CEELEM)
THIS SUBROUTINE PARSES THE FIRST LINE OF AN ENTRY THAT WAS PREVIOUSLY READ FROM AN ASCII MASTER TABLE D FILE AND STORES THE OUTPUT INTO THE MERGED ARRAYS.
Detailed Description
Author
ATOR
Date
2007-01-19
Definition in file sntbde.f.
Function/Subroutine Documentation
subroutine sntbde (LUNT, IFXYN, character*(*) LINE, MXMTBD, MXELEM, NMTBD, integer, dimension(*) IMFXYN, character, dimension(8,*) CMMNEM, character*4, dimension(*) CMDSC, character, dimension(120,*) CMSEQ, integer, dimension(*) NMELEM, integer, dimension(mxmtbd,mxelem) IEFXYN, character*120, dimension(mxmtbd,mxelem) CEELEM)
THIS SUBROUTINE PARSES THE FIRST LINE OF AN ENTRY THAT WAS PREVIOUSLY READ FROM AN ASCII MASTER TABLE D FILE AND STORES THE OUTPUT INTO THE MERGED ARRAYS.
IT THEN READS AND PARSES ALL REMAINING LINES FOR THAT SAME ENTRY AND THEN LIKEWISE STORES THAT OUTPUT INTO THE MERGED ARRAYS. THE RESULT IS THAT, UPON OUTPUT, THE MERGED ARRAYS NOW CONTAIN ALL OF THE INFORMATION FOR THE CURRENT TABLE ENTRY.
PROGRAM HISTORY LOG: 2007-01-19 J. ATOR – ORIGINAL AUTHOR 2021-01-08 J. ATOR – MODIFIED MSTABS ARRAY DECLARATIONS FOR GNUv10 PORTABILITY
USAGE: CALL SNTBDE (LUNT, IFXYN, LINE, MXMTBD, MXELEM, NMTBD, IMFXYN, CMMNEM, CMDSC, CMSEQ, NMELEM, IEFXYN, CEELEM) INPUT ARGUMENT LIST: LUNT - INTEGER: FORTRAN LOGICAL UNIT NUMBER OF ASCII FILE CONTAINING MASTER TABLE D INFORMATION IFXYN - INTEGER: BIT-WISE REPRESENTATION OF FXY NUMBER FOR TABLE ENTRY; THIS FXY NUMBER IS THE SEQUENCE DESCRIPTOR LINE - CHARACTER*(*): FIRST LINE OF TABLE ENTRY MXMTBD - INTEGER: MAXIMUM NUMBER OF ENTRIES TO BE STORED IN MERGED MASTER TABLE D ARRAYS; THIS SHOULD BE THE SAME NUMBER AS WAS USED TO DIMENSION THE OUTPUT ARRAYS IN THE CALLING PROGRAM, AND IT IS USED BY THIS SUBROUTINE TO ENSURE THAT IT DOESN'T OVERFLOW THESE ARRAYS MXELEM - INTEGER: MAXIMUM NUMBER OF ELEMENTS TO BE STORED PER ENTRY WITHIN THE MERGED MASTER TABLE D ARRAYS; THIS SHOULD BE THE SAME NUMBER AS WAS USED TO DIMENSION THE OUTPUT ARRAYS IN THE CALLING PROGRAM, AND IT IS USED BY THIS SUBROUTINE TO ENSURE THAT IT DOESN'T OVERFLOW THESE ARRAYS
OUTPUT ARGUMENT LIST: NMTBD - INTEGER: NUMBER OF ENTRIES IN MERGED MASTER TABLE D ARRAYS IMFXYN(*)- INTEGER: MERGED ARRAY CONTAINING BIT-WISE REPRESENTATIONS OF FXY NUMBERS (I.E. SEQUENCE DESCRIPTORS) CMMNEM(*)- CHARACTER*8: MERGED ARRAY CONTAINING MNEMONICS CMDSC(*) - CHARACTER*4: MERGED ARRAY CONTAINING DESCRIPTOR CODES CMSEQ(*) - CHARACTER*120: MERGED ARRAY CONTAINING SEQUENCE NAMES NMELEM(*)- INTEGER: MERGED ARRAY CONTAINING NUMBER OF ELEMENTS STORED FOR EACH ENTRY IEFXYN(*,*)- INTEGER: MERGED ARRAY CONTAINING BIT-WISE REPRESENTATIONS OF ELEMENT FXY NUMBERS CEELEM(*,*)- CHARACTER*120: MERGED ARRAY CONTAINING ELEMENT NAMES
REMARKS: THIS ROUTINE CALLS: ADN30 BORT BORT2 IFXY IGETFXY IGETNTBL JSTCHR NEMOCK PARSTR THIS ROUTINE IS CALLED BY: RDMTBD Normally not called by any application programs.
Definition at line 61 of file sntbde.f.
References adn30(), bort(), bort2(), ifxy(), igetfxy(), igetntbl(), jstchr(), nemock(), and parstr().
Referenced by rdmtbd().