NCEPLIBS-bufr: sntbbe.f File Reference
sntbbe.f File Reference
Functions/Subroutines
subroutine sntbbe (IFXYN, LINE, MXMTBB, NMTBB, IMFXYN, CMSCL, CMSREF, CMBW, CMUNIT, CMMNEM, CMDSC, CMELEM)
THIS SUBROUTINE PARSES AN ENTRY THAT WAS PREVIOUSLY READ FROM AN ASCII MASTER TABLE B FILE AND THEN STORES THE OUTPUT INTO THE MERGED ARRAYS.
Detailed Description
Author
ATOR
Date
2007-01-19
Definition in file sntbbe.f.
Function/Subroutine Documentation
subroutine sntbbe (IFXYN, character*(*) LINE, MXMTBB, NMTBB, integer, dimension(*) IMFXYN, character, dimension(4,*) CMSCL, character, dimension(12,*) CMSREF, character, dimension(4,*) CMBW, character, dimension(14,*) CMUNIT, character, dimension(8,*) CMMNEM, character*4, dimension(*) CMDSC, character, dimension(120,*) CMELEM)
THIS SUBROUTINE PARSES AN ENTRY THAT WAS PREVIOUSLY READ FROM AN ASCII MASTER TABLE B FILE AND THEN STORES THE OUTPUT INTO THE MERGED ARRAYS.
PROGRAM HISTORY LOG: 2007-01-19 J. ATOR – ORIGINAL AUTHOR 2021-01-08 J. ATOR – MODIFIED MSTABS ARRAY DECLARATIONS FOR GNUv10 PORTABILITY
USAGE: CALL SNTBBE (IFXYN, LINE, MXMTBB, NMTBB, IMFXYN, CMSCL, CMSREF, CMBW, CMUNIT, CMMNEM, CMDSC, CMELEM) INPUT ARGUMENT LIST: IFXYN - INTEGER: BIT-WISE REPRESENTATION OF FXY NUMBER FOR TABLE ENTRY; THIS FXY NUMBER IS THE ELEMENT DESCRIPTOR LINE - CHARACTER*(*): TABLE ENTRY MXMTBB - INTEGER: MAXIMUM NUMBER OF ENTRIES TO BE STORED IN MERGED MASTER TABLE B ARRAYS; THIS SHOULD BE THE SAME NUMBER AS WAS USED TO DIMENSION THE OUTPUT ARRAYS IN THE CALLING PROGRAM, AND IT IS USED BY THIS SUBROUTINE TO ENSURE THAT IT DOESN'T OVERFLOW THESE ARRAYS
OUTPUT ARGUMENT LIST: NMTBB - INTEGER: NUMBER OF ENTRIES IN MERGED MASTER TABLE B ARRAYS IMFXYN(*)- INTEGER: MERGED ARRAY CONTAINING BIT-WISE REPRESENTATIONS OF FXY NUMBERS (I.E. ELEMENT DESCRIPTORS) CMSCL(*) - CHARACTER*4: MERGED ARRAY CONTAINING SCALE FACTORS CMSREF(*)- CHARACTER*12: MERGED ARRAY CONTAINING REFERENCE VALUES CMBW(*) - CHARACTER*4: MERGED ARRAY CONTAINING BIT WIDTHS CMUNIT(*)- CHARACTER*14: MERGED ARRAY CONTAINING UNITS CMMNEM(*)- CHARACTER*8: MERGED ARRAY CONTAINING MNEMONICS CMDSC(*) - CHARACTER*4: MERGED ARRAY CONTAINING DESCRIPTOR CODES CMELEM(*)- CHARACTER*120: MERGED ARRAY CONTAINING ELEMENT NAMES
REMARKS: THIS ROUTINE CALLS: BORT BORT2 JSTCHR NEMOCK PARSTR RJUST THIS ROUTINE IS CALLED BY: RDMTBB Normally not called by any application programs.
Definition at line 47 of file sntbbe.f.
References bort(), bort2(), jstchr(), nemock(), parstr(), and rjust().
Referenced by rdmtbb().