NCEPLIBS-bufr: uptdd.f File Reference
uptdd.f File Reference
Functions/Subroutines
subroutine uptdd (ID, LUN, IENT, IRET)
THIS SUBROUTINE RETURNS THE BIT-WISE REPRESENTATION OF THE FXY VALUE CORRESPONDING TO, SEQUENTIALLY, A PARTICULAR (IENT'th) "CHILD" MNEMONIC OF A TABLE D SEQUENCE ("PARENT") MNEMONIC.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file uptdd.f.
Function/Subroutine Documentation
subroutine uptdd (ID, LUN, IENT, IRET)
THIS SUBROUTINE RETURNS THE BIT-WISE REPRESENTATION OF THE FXY VALUE CORRESPONDING TO, SEQUENTIALLY, A PARTICULAR (IENT'th) "CHILD" MNEMONIC OF A TABLE D SEQUENCE ("PARENT") MNEMONIC.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1995-06-28 J. WOOLLEN – INCREASED THE SIZE OF INTERNAL BUFR TABLE ARRAYS IN ORDER TO HANDLE BIGGER FILES 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION; OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL UPTDD (ID, LUN, IENT, IRET) INPUT ARGUMENT LIST: ID - INTEGER: POSITIONAL INDEX OF PARENT MNEMONIC WITHIN INTERNAL BUFR TABLE D ARRAY TABD LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS IENT - INTEGER: ORDINAL INDICATOR OF CHILD MNEMONIC TO RETURN FROM WITHIN TABD(ID,LUN) SEQUENCE: 0 = return a count of the total number of child mnemonics within TABD(ID,LUN)
OUTPUT ARGUMENT LIST: IRET - INTEGER: RETURN VALUE (SEE REMARKS)
REMARKS: THE INTERPRETATION OF THE RETURN VALUE IRET DEPENDS UPON THE INPUT VALUE IENT, AS FOLLOWS:
IF (IENT = 0) THEN IRET = a count of the total number of child mnemonics within TABD(ID,LUN) ELSE IRET = the bit-wise representation of the FXY value corresponding to the IENT'th child mnemonic of TABD(ID,LUN) END IF
THIS ROUTINE CALLS:        BORT     IUPM
THIS ROUTINE IS CALLED BY: NEMTBD   RESTD
                           Normally not called by any application
                           programs.
Definition at line 60 of file uptdd.f.
References bort(), and iupm().
Referenced by nemtbd(), and restd().