NCEPLIBS-bufr: arallocc.c File Reference
arallocc.c File Reference
Dynamically allocate C language arrays within internal memory.
#include "bufrlib.h"
#include "cread.h"
#include "mstabs.h"
Functions
void arallocc (void)
This subroutine is called internally during the first call to subroutine openbf() from an application program, in order to dynamically allocate internal C language arrays based on parameter values set during one or more previous calls to function isetprm().
Detailed Description
Dynamically allocate C language arrays within internal memory.
Definition in file arallocc.c.
Function Documentation
void arallocc (void)
This subroutine is called internally during the first call to subroutine openbf() from an application program, in order to dynamically allocate internal C language arrays based on parameter values set during one or more previous calls to function isetprm().
This subroutine isn't normally called directly from an application program, since it's automatically called internally during the first call to subroutine openbf() from an application program.
Author
J. Ator
Date
2014-12-04
Remarks
All memory allocated within this subroutine can be freed via a subsequent call to subroutine exitbufr() from within the application program, or else it will be freed automatically by the operating system once the application program terminates.
Program history log:
Date Programmer Comments
2014-12-04 J. Ator Original author
2021-05-17 J. Ator Allow up to 24 characters in cbunit
Definition at line 36 of file arallocc.c.
References bort(), igetprm(), lstpos, and pb.
Referenced by openbf().