NCEPLIBS-bufr: datelen.f File Reference
datelen.f File Reference
Specify format of Section 1 date-time when reading BUFR messages.
Functions/Subroutines
subroutine datelen (LEN)
This subroutine is used to specify the format of Section 1 date-time values that will be output by future calls to any of the BUFRLIB message-reading subroutines.
Detailed Description
Specify format of Section 1 date-time when reading BUFR messages.
Definition in file datelen.f.
Function/Subroutine Documentation
subroutine datelen (LEN)
This subroutine is used to specify the format of Section 1 date-time values that will be output by future calls to any of the BUFRLIB message-reading subroutines.
Author
J. Woollen
Date
1998-07-08
Parameters
[in] LEN – integer: Length of Section 1 date-time values to be output by all future calls to message-reading subroutines
8 = YYMMDDHH format with 2-digit year (the default)
10 = YYYYMMDDHH format with 4-digit year
This subroutine can be called at any time from within the application program, and the specified value for LEN will remain in effect for all future calls to any of the BUFRLIB subroutines which read BUFR messages, unless a subsequent call is made to this subroutine to reset the value of LEN again. If this subroutine is never called, a default value of 8 is used for LEN, as set within subroutine bfrini().
Program history log:
Date Programmer Comments
1998-07-08 J. Woollen Original author
2002-05-14 J. Woollen Changed from an entry point in readmg() to stand-alone subroutine, to increase portability to other platforms
2003-11-04 J. Ator Added documentation
2004-12-20 D. Keyser Calls wrdlen() to initialize local machine information, in case it has not yet been called
Definition at line 35 of file datelen.f.
References bort(), and wrdlen().
Referenced by fdebufr().