NCEPLIBS-bufr: igetdate.f File Reference
igetdate.f File Reference
Read the date-time from Section 1 of a BUFR message.
Functions/Subroutines
function igetdate (MBAY, IYR, IMO, IDY, IHR)
This function returns the date-time from within Section 1 of a BUFR message.
Detailed Description
Read the date-time from Section 1 of a BUFR message.
Definition in file igetdate.f.
Function/Subroutine Documentation
function igetdate (dimension(*) MBAY, IYR, IMO, IDY, IHR)
This function returns the date-time from within Section 1 of a BUFR message.
The function will work on any BUFR message encoded using BUFR edition 2, 3, or 4.
Author
J. Ator
Date
2005-11-29
Parameters
[in] MBAY – integer(*): BUFR message
[out] IYR – integer: Year stored within Section 1 of MBAY, in format of either YY or YYYY, depending on the most recent call to subroutine datelen()
[out] IMO – integer: Month stored within Section 1 of MBAY
[out] IDY – integer: Day stored within Section 1 of MBAY
[out] IHR – integer: Hour stored within Section 1 of MBAY
Returns
igetdate – integer: Date-time stored within Section 1 of MBAY, in format of either YYMMDDHH or YYYYMMDDHH, depending on the most recent call to subroutine datelen()
Remarks
The start of the BUFR message (i.e. the string 'BUFR') must be aligned on the first 4 bytes of MBAY.
Program history log:
Date Programmer Comments
2005-11-29 J. Ator Original author
Definition at line 34 of file igetdate.f.
References iupbs01().
Referenced by cktaba(), datebf(), and dumpbf().