NCEPLIBS-bufr: iupb.f File Reference
iupb.f File Reference
Functions/Subroutines
function iupb (MBAY, NBYT, NBIT)
THIS FUNCTION UNPACKS AND RETURNS A BINARY INTEGER WORD CONTAINED WITHIN NBIT BITS OF A BUFR MESSAGE PACKED INTO THE INTEGER ARRAY MBAY, STARTING WITH THE FIRST BIT OF BYTE NBYT.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file iupb.f.
Function/Subroutine Documentation
function iupb (dimension(*) MBAY, NBYT, NBIT)
THIS FUNCTION UNPACKS AND RETURNS A BINARY INTEGER WORD CONTAINED WITHIN NBIT BITS OF A BUFR MESSAGE PACKED INTO THE INTEGER ARRAY MBAY, STARTING WITH THE FIRST BIT OF BYTE NBYT.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION
USAGE: IUPB (MBAY, NBYT, NBIT) INPUT ARGUMENT LIST: MBAY - INTEGER: *-WORD PACKED BINARY ARRAY CONTAINING BUFR MESSAGE NBYT - INTEGER: BYTE WITHIN MBAY AT WHOSE FIRST BIT TO BEGIN UNPACKING NBIT - INTEGER: NUMBER OF BITS WITHIN MBAY TO BE UNPACKED
OUTPUT ARGUMENT LIST: IUPB - INTEGER: UNPACKED INTEGER WORD
REMARKS: THIS ROUTINE CALLS: UPB THIS ROUTINE IS CALLED BY: CKTABA CPYUPD GETLENS IUPBS01 IUPBS3 MSGUPD MSGWRT RDMEMS RTRCPTB STBFDX STNDRD STRCPT UPDS3 WRDXTB WRITLC Normally not called by any application programs.
Definition at line 36 of file iupb.f.
References upb().
Referenced by cktaba(), cpyupd(), getlens(), iupbs01(), iupbs3(), main(), msgupd(), rdmems(), rtrcptb(), stbfdx(), stndrd(), upds3(), and wrdxtb().