NCEPLIBS-bufr: mtinfo.f File Reference
mtinfo.f File Reference
Specify location of master BUFR tables on local file system.
Functions/Subroutines
subroutine mtinfo (CMTDIR, LUNMT1, LUNMT2)
This subroutine allows the specification of the directory location and Fortran logical unit numbers to be used when reading master BUFR tables on the local file system.
Detailed Description
Specify location of master BUFR tables on local file system.
Definition in file mtinfo.f.
Function/Subroutine Documentation
subroutine mtinfo (character*(*) CMTDIR, LUNMT1, LUNMT2)
This subroutine allows the specification of the directory location and Fortran logical unit numbers to be used when reading master BUFR tables on the local file system.
Author
J. Ator
Date
2009-03-23
Parameters
[in] CMTDIR – character*(*): Directory location of master BUFR tables on local file system (up to 100 characters)
[in] LUNMT1 – integer: First Fortran logical unit number to use when reading master BUFR tables on local file system
[in] LUNMT2 – integer: Second Fortran logical unit number to use when reading master BUFR tables on local file system
See Master BUFR Tables for more information about master BUFR tables. In particular, note that this subroutine is normally only ever called after a prior call has been made to subroutine openbf() with IO = 'SEC3'. But in such cases, any call to this subroutine must be made prior to any subsequent calls to any of the BUFR message-reading subroutines for the associated BUFR file; otherwise, default values for CMTDIR, LUNMT1 and LUNMT2 will be used as defined within subroutine bfrini().
For CMTDIR, any full or relative directory pathname that is legal on the local filesystem is permissible, up to a total maximum length of 100 characters. The BUFRLIB software will then automatically search within this directory for any necessary master table files and open and read them as needed.
The logical unit numbers LUNMT1 and LUNMT2 should be distinct from each other but should not already be assigned to any files on the local system.
Program history log:
Date Programmer Comments
2009-03-23 J. Ator Original author
Definition at line 46 of file mtinfo.f.
References bort2(), and strsuc().
Referenced by bfrini(), fdebufr(), and bufr_c_interface_mod::mtinfo_c().