NCEPLIBS-bufr: numtab.f File Reference
numtab.f File Reference
Get information about a descriptor, based on the FXY value.
Functions/Subroutines
subroutine numtab (LUN, IDN, NEMO, TAB, IRET)
This subroutine returns information about a descriptor from the internal DX BUFR tables, based on the bit-wise representation of the FXY value associated with that descriptor.
Detailed Description
Get information about a descriptor, based on the FXY value.
Definition in file numtab.f.
Function/Subroutine Documentation
subroutine numtab (LUN, IDN, character*(*) NEMO, character*1 TAB, IRET)
This subroutine returns information about a descriptor from the internal DX BUFR tables, based on the bit-wise representation of the FXY value associated with that descriptor.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUN – integer: Internal I/O stream index associated with DX BUFR tables
[in] IDN – integer: Bit-wise representation of FXY value for descriptor
[out] NEMO – character*(*): Mnemonic associated with IDN
[out] TAB – character: Type associated with IDN
'B' = Table B descriptor
'D' = Table D descriptor
'C' = Table C operator
'R' = Replication descriptor
'F' = Replication factor
[out] IRET – integer:
Positional index of IDN within internal Table B, if TAB = 'B'
Positional index of IDN within internal Table D, if TAB = 'D'
The X portion of the FXY value in IDN, if TAB = 'C'
((-1) * the Y portion of the FXY value in IDN), if TAB = 'R' and the replication is regular (i.e. non-delayed)
5, if TAB = 'R' or TAB = 'F' and the replication is 1-bit delayed
4, if TAB = 'R' or TAB = 'F' and the replication is 8-bit delayed (stack)
3, if TAB = 'R' or TAB = 'F' and the replication is 8-bit delayed
2, if TAB = 'R' or TAB = 'F' and the replication is 16-bit delayed
0, otherwise
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1995-06-28 J. Woollen Increased the size of internal BUFR table arrays in order to handle bigger files
1999-11-18 J. Woollen The number of BUFR files which can be opened at one time increased from 10 to 32
2000-09-19 J. Woollen Added capability to encode and decode data using the operator descriptors (BUFR table C) for changing width and changing scale
2003-11-04 J. Ator Added documentation
2003-11-04 S. Bender Added remarks and routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added history documentation; corrected typo
2005-11-29 J. Ator Added support for 207 and 208 operators
2009-04-21 J. Ator Use numtbd()
2010-03-19 J. Ator Added support for 204 and 205 operators
2012-03-02 J. Ator Added support for 203 operator
2015-02-25 J. Ator Allow processing of 2-2x, 2-3x and 2-4X non-marker operators in DX tables
Definition at line 58 of file numtab.f.
References adn30(), iokoper(), and numtbd().
Referenced by cktaba(), nemtbd(), seqsdx(), stndrd(), and ufbqcp().