NCEPLIBS-bufr: ufbmns.f File Reference
ufbmns.f File Reference
Read a specified data subset from internal arrays.
Functions/Subroutines
subroutine ufbmns (IREP, SUBSET, IDATE)
This subroutine reads a specified data subset from internal arrays in memory, so that it is now in scope for processing via calls to any of the values-reading subroutines using the Fortran logical unit number IUNIT that was returned from the most recent call to subroutine ufbmem().
Detailed Description
Read a specified data subset from internal arrays.
Definition in file ufbmns.f.
Function/Subroutine Documentation
subroutine ufbmns (IREP, character*8 SUBSET, IDATE)
This subroutine reads a specified data subset from internal arrays in memory, so that it is now in scope for processing via calls to any of the values-reading subroutines using the Fortran logical unit number IUNIT that was returned from the most recent call to subroutine ufbmem().
This subroutine does not return any information about which BUFR message within the internal arrays contained the specified data subset.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] IREP – integer: Number of data subset to be read into scope for further processing, counting from the beginning of the internal arrays in memory
[out] SUBSET – character*8: Table A mnemonic for type of BUFR message that was read into scope (see DX BUFR Tables for further information about Table A mnemonics)
[out] IDATE – integer: Date-time stored within Section 1 of BUFR message that was read into scope, in format of either YYMMDDHH or YYYYMMDDHH, depending on the most recent call to subroutine datelen()
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1998-07-08 J. Woollen Replaced call to Cray library routine "ABORT" with call to new internal routine bort()
1999-11-18 J. Woollen Increased MAXMEM from 4 Mb to 8 Mb
2001-08-15 D. Keyser Increased MAXMEM from 8 Mb to 16 Mb
2004-11-15 D. Keyser Increased MAXMEM from 16 Mb to 50 Mb
2009-03-23 J. Ator Use ireadmm() instead of rdmemm(); simplify logic
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 42 of file ufbmns.f.
References bort(), ireadmm(), nmsub(), and rdmems().