NCEPLIBS-bufr: usrtpl.f File Reference
usrtpl.f File Reference
Functions/Subroutines
subroutine usrtpl (LUN, INVN, NBMP)
THIS SUBROUTINE STORES THE SUBSET TEMPLATE INTO INTERNAL SUBSET ARRAYS IN MODULE USRINT FOR CASES OF NODE EXPANSION (I.E.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file usrtpl.f.
Function/Subroutine Documentation
subroutine usrtpl (LUN, INVN, NBMP)
THIS SUBROUTINE STORES THE SUBSET TEMPLATE INTO INTERNAL SUBSET ARRAYS IN MODULE USRINT FOR CASES OF NODE EXPANSION (I.E.
WHEN THE NODE IS EITHER A TABLE A MNEMONIC OR A DELAYED REPLICATION FACTOR).
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2002-05-14 J. WOOLLEN – REMOVED OLD CRAY COMPILER DIRECTIVES 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY) (INCOMPLETE); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY OR UNUSUAL THINGS HAPPEN; COMMENTED OUT HARDWIRE OF VTMP TO "BMISS" (10E10) WHEN IT IS > 10E9 (CAUSED PROBLEMS ON SOME FOREIGN MACHINES) 2009-03-31 J. WOOLLEN – ADD DOCUMENTATION 2009-04-21 J. ATOR – USE ERRWRT 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL USRTPL (LUN, INVN, NBMP) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS INVN - INTEGER: STARTING JUMP/LINK TABLE INDEX OF THE NODE TO BE EXPANDED WITHIN THE SUBSET TEMPLATE NBMP - INTEGER: NUMBER OF TIMES BY WHICH INVN IS TO BE EXPANDED (I.E. NUMBER OF REPLICATIONS OF NODE)
REMARKS: THIS ROUTINE CALLS: BORT ERRWRT THIS ROUTINE IS CALLED BY: DRFINI DRSTPL MSGUPD OPENMB OPENMG RDCMPS TRYBUMP UFBGET UFBTAB UFBTAM WRCMPS WRITLC Normally not called by any application programs.
Definition at line 51 of file usrtpl.f.
References bort(), and errwrt().
Referenced by drfini(), drstpl(), msgupd(), openmb(), openmg(), rdcmps(), trybump(), ufbget(), ufbtab(), ufbtam(), wrcmps(), and writlc().