NCEPLIBS-bufr: wrdlen.F File Reference
wrdlen.F File Reference
Determine important information about the local machine.
Functions/Subroutines
subroutine wrdlen
This subroutine figures out some important information about the local machine on which the BUFRLIB software is being run, including the native endianness, the number of bytes in an integer, and whether the machine uses the ASCII or EBCDIC character set.
Detailed Description
Determine important information about the local machine.
Definition in file wrdlen.F.
Function/Subroutine Documentation
subroutine wrdlen (void)
This subroutine figures out some important information about the local machine on which the BUFRLIB software is being run, including the native endianness, the number of bytes in an integer, and whether the machine uses the ASCII or EBCDIC character set.
This subroutine isn't normally called directly by any application program, because it's automatically called internally from within subroutine openbf() during the first time that subroutine is called by any application program. It's also called as needed from within several other subroutines, but it always keeps track of its results as well as whether it has already been called during the life of an application program, and that way if it does end up being called more than once, it will just quietly return without having to recompute all of its results from the first call.
Authors
J. Woollen
J. Ator
Date
1994-01-06
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1998-07-08 J. Woollen Replaced call to Cray library routine ABORT with call to new internal routine bort()
2003-11-04 J. Ator Added documentation
2003-11-04 S. Bender Added remarks and routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added documentation; outputs more complete diagnostic info when routine terminates abnormally, initialized NBYTW to zero during the first call
2004-08-18 J. Ator Added SAVE For IFIRST flag and immediate return if IFIRST=1
2007-01-19 J. Ator Big-endian vs. little-endian is now determined at compile time and configured within BUFRLIB via conditional compilation directives
2009-03-23 J. Ator Call bvers() to get version number
Definition at line 35 of file wrdlen.F.
References bort(), errwrt(), and iupm().
Referenced by cobfl(), copybf(), datelen(), dumpbf(), iupbs01(), iupbs3(), main(), openbf(), rdmtbb(), rdmtbd(), rdmtbf(), and upds3().