NCEPLIBS-bufr: writdx.f File Reference
writdx.f File Reference
Functions/Subroutines
subroutine writdx (LUNIT, LUN, LUNDX)
THIS SUBROUTINE WRITES BUFR TABLE (DICTIONARY) MESSAGES TO THE BEGINNING OF AN OUTPUT BUFR FILE IN LUNIT.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file writdx.f.
Function/Subroutine Documentation
subroutine writdx (LUNIT, LUN, LUNDX)
THIS SUBROUTINE WRITES BUFR TABLE (DICTIONARY) MESSAGES TO THE BEGINNING OF AN OUTPUT BUFR FILE IN LUNIT.
THE TABLE MESSAGES ARE READ FROM ARRAYS IN INTERNAL MEMORY (MODULE TABABD). AN INITIAL CALL TO BUFR ARCHIVE LIBRARY SUBROUTINE READDX GENERATES THESE INTERNAL ARRAYS.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1995-06-28 J. WOOLLEN – INCREASED THE SIZE OF INTERNAL BUFR TABLE ARRAYS IN ORDER TO HANDLE BIGGER FILES 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2000-09-19 J. WOOLLEN – MAXIMUM MESSAGE LENGTH INCREASED FROM 10,000 TO 20,000 BYTES 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2004-08-09 J. ATOR – MAXIMUM MESSAGE LENGTH INCREASED FROM 20,000 TO 50,000 BYTES 2009-03-23 J. ATOR – USE WRDXTB
USAGE: CALL WRITDX (LUNIT, LUN, LUNDX) INPUT ARGUMENT LIST: LUNIT - INTEGER: FORTRAN LOGICAL UNIT NUMBER FOR BUFR FILE BEING WRITTEN LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS (ASSOCIATED WITH FILE CONNECTED TO LOGICAL UNIT LUNIT) LUNDX - INTEGER: FORTRAN LOGICAL UNIT NUMBER CONTAINING DICTIONARY TABLE INFORMATION TO BE USED (BY READDX) TO CREATE INTERNAL TABLES WRITTEN TO LUNIT (SEE READDX); IF SET EQUAL TO LUNIT, THIS SUBROUTINE CALLS BORT
REMARKS: THIS ROUTINE CALLS: BORT READDX WRDXTB THIS ROUTINE IS CALLED BY: OPENBF Normally not called by any application programs.
Definition at line 50 of file writdx.f.
References bort(), readdx(), and wrdxtb().
Referenced by openbf().