//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.18 at 04:08:06 PM GMT-05:00 
//


package CodeFlag27.jabx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="No" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="FXY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ElementName_en" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CodeFigure" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EntryName_en" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="536870910"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EntryName_sub1_en" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="536870910"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EntryName_sub2_en" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Note_en" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Status" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "no",
    "fxy",
    "elementNameEn",
    "codeFigure",
    "entryNameEn",
    "entryNameSub1En",
    "entryNameSub2En",
    "noteEn",
    "status"
})
@XmlRootElement(name = "BUFRCREX_27_0_0_CodeFlag_en")
public class BUFRCREX2700CodeFlagEn {

    @XmlElement(name = "No")
    protected Float no;
    @XmlElement(name = "FXY")
    protected String fxy;
    @XmlElement(name = "ElementName_en")
    protected String elementNameEn;
    @XmlElement(name = "CodeFigure")
    protected String codeFigure;
    @XmlElement(name = "EntryName_en")
    protected String entryNameEn;
    @XmlElement(name = "EntryName_sub1_en")
    protected String entryNameSub1En;
    @XmlElement(name = "EntryName_sub2_en")
    protected String entryNameSub2En;
    @XmlElement(name = "Note_en")
    protected String noteEn;
    @XmlElement(name = "Status")
    protected String status;

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setNo(Float value) {
        this.no = value;
    }

    /**
     * Gets the value of the fxy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFXY() {
        return fxy;
    }

    /**
     * Sets the value of the fxy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFXY(String value) {
        this.fxy = value;
    }

    /**
     * Gets the value of the elementNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementNameEn() {
        return elementNameEn;
    }

    /**
     * Sets the value of the elementNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementNameEn(String value) {
        this.elementNameEn = value;
    }

    /**
     * Gets the value of the codeFigure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeFigure() {
        return codeFigure;
    }

    /**
     * Sets the value of the codeFigure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeFigure(String value) {
        this.codeFigure = value;
    }

    /**
     * Gets the value of the entryNameEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryNameEn() {
        return entryNameEn;
    }

    /**
     * Sets the value of the entryNameEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryNameEn(String value) {
        this.entryNameEn = value;
    }

    /**
     * Gets the value of the entryNameSub1En property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryNameSub1En() {
        return entryNameSub1En;
    }

    /**
     * Sets the value of the entryNameSub1En property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryNameSub1En(String value) {
        this.entryNameSub1En = value;
    }

    /**
     * Gets the value of the entryNameSub2En property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryNameSub2En() {
        return entryNameSub2En;
    }

    /**
     * Sets the value of the entryNameSub2En property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryNameSub2En(String value) {
        this.entryNameSub2En = value;
    }

    /**
     * Gets the value of the noteEn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteEn() {
        return noteEn;
    }

    /**
     * Sets the value of the noteEn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteEn(String value) {
        this.noteEn = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
