!> @file
!> @brief Specify location for logging of error and diagnostic messages.
!>
!> @author J. Ator @date 2009-04-21

!> Specify a custom location for the logging of error and diagnostic messages
!> generated by the NCEPLIBS-bufr software.
!>
!> By default, all such messages are printed to standard output.
!> However, if a user would like to direct such messages elsewhere,
!> this can be done by providing an inline version of this subroutine,
!> using the same calling sequence shown below, in order to override
!> the default version of this subroutine contained within the NCEPLIBS-bufr
!> distribution package. The user does not need to explicitly call
!> this subroutine from within the application code, since the NCEPLIBS-bufr
!> software automatically issues an internal call to errwrt when needed.
!> Instead, the user simply needs to define his or her own version of
!> this subroutine with the same name and calling sequence and include
!> it within the compilation, and then the input string str can be
!> logged or handled in any way of the user's choosing.
!>
!> @param str - Error message or other diagnostic to be printed to standard output (default) or
!> to another location (if specified via an inline replacement version of this subroutine)
!>
!> @remarks
!> - The amount and types of diagnostic messages generated for
!> logging can be controlled via a separate call to subroutine
!> openbf() with io = 'QUIET'.
!>
!> @author J. Ator @date 2009-04-21
subroutine errwrt(str)

  implicit none

  character*(*), intent(in) :: str

  print'(1x,a)',str

  return
end subroutine errwrt
