# 1 "moda_mstabs.F"
	MODULE MODA_MSTABS



	  USE MODV_MAXCD




	  USE MODV_MXMTBB




	  USE MODV_MXMTBD


# 33

	  INTEGER, BIND(C) :: NMTB
	  INTEGER, BIND(C) :: NMTD
	  INTEGER, BIND(C) :: IBFXYN(MXMTBB)
	  CHARACTER*4, BIND(C) :: CBSCL(MXMTBB)
	  CHARACTER*12, BIND(C) :: CBSREF(MXMTBB)
	  CHARACTER*4, BIND(C) :: CBBW(MXMTBB)
	  CHARACTER*14, BIND(C) :: CBUNIT(MXMTBB)
	  CHARACTER*8, BIND(C) :: CBMNEM(MXMTBB)
	  CHARACTER*120, BIND(C) :: CBELEM(MXMTBB)
	  INTEGER, BIND(C) :: IDFXYN(MXMTBD)
	  CHARACTER*120, BIND(C) :: CDSEQ(MXMTBD)
	  CHARACTER*8, BIND(C) :: CDMNEM(MXMTBD)
	  INTEGER, BIND(C) :: NDELEM(MXMTBD)
	  INTEGER, BIND(C) :: IDEFXY(MXMTBD*MAXCD)


	END MODULE
