C> @file
C> @brief Position an output BUFR file for appending.
C>
C> @author Woollen @date 1994-01-06

C> Reads to the end of the file pointed to by
C> abs(LUNXX) and positions it for appending. The file must have
C> already been opened for output operations.
C>
C< If LUNXX > 0, then the file is backspaced before being positioned for append.
C> If LUNXX < 0, then the file is not backspaced before being positioned for append.
C>
C> @param[in] LUNXX - integer: absolute value is fortran logical unit number
C> for BUFR file
C>
C> @author Woollen @date 1994-01-06
      SUBROUTINE POSAPX(LUNXX)

      use bufrlib

      use moda_mgwa

C-----------------------------------------------------------------------
C-----------------------------------------------------------------------

      LUNIT = ABS(LUNXX)

      CALL STATUS(LUNIT,LUN,IL,IM)
      IF(IL.EQ.0) GOTO 901
      IF(IL.LT.0) GOTO 902

C  TRY TO READ TO THE END OF THE FILE
C  ----------------------------------

1     CALL RDMSGW(LUNIT,MGWA,IER)
      IF(IER.LT.0) RETURN
      IF(IDXMSG(MGWA).EQ.1) THEN

C       This is an internal dictionary message that was generated by the
C       NCEPLIBS-bufr software.  Backspace the file pointer and
C       then read and store all such dictionary messages (they should be
C       stored consecutively!) and reset the internal tables.

        CALL BACKBUFR_C(LUN) !BACKSPACE LUNIT
        CALL RDBFDX(LUNIT,LUN)

      ENDIF
      GOTO 1

C  ERROR EXITS
C  -----------

901   CALL BORT('BUFRLIB: POSAPX - INPUT BUFR FILE IS CLOSED, IT MUST'//
     . ' BE OPEN FOR OUTPUT')
902   CALL BORT('BUFRLIB: POSAPX - INPUT BUFR FILE IS OPEN FOR INPUT'//
     . ', IT MUST BE OPEN FOR OUTPUT')
      END
