/** @file
 *  @brief Declare variables for internal storage of replication sequences.
 *
 *  These variables are used within functions strrpsq() and srchrpsq() to
 *  maintain an internal cache of replication sequences generated by function stseq().
 *
 *  @author J. Ator @date 2024-08-26
 */

/** Maximum number of entries in internal replication sequences cache.
 *
 *  Note that this value is constrained by the fact that any new rpidns value would
 *  have been generated by a previous call to function igettdi().
*/
#define MAX_RPSQ 256

/** @var nrpsq
 *  Number of entries in internal replication sequences cache
 *
 *  @var rpidns
 *  WMO bit-wise representation of FXY number for each entry
 *
 *  @var ncdescs
 *  Number of child descriptors for each entry
 *
 *  @var cdescs
 *  Child descriptors for each entry
 */
#ifdef IN_ARALLOCC
    int nrpsq;
    int rpidns[MAX_RPSQ];
    int ncdescs[MAX_RPSQ];
    int *cdescs;
#else
    extern int nrpsq;
    extern int rpidns[MAX_RPSQ];
    extern int ncdescs[MAX_RPSQ];
    extern int *cdescs;
#endif
