NCEPLIBS-bufr: atrcpt.f File Reference
atrcpt.f File Reference
Add a tank receipt time to a BUFR message.
Functions/Subroutines
subroutine atrcpt (MSGIN, LMSGOT, MSGOT)
This subroutine reads an input message and outputs an equivalent BUFR message with a tank receipt time added to Section 1.
Detailed Description
Add a tank receipt time to a BUFR message.
Definition in file atrcpt.f.
Function/Subroutine Documentation
atrcpt()
subroutine atrcpt (dimension(*) MSGIN, LMSGOT, dimension(*) MSGOT)
This subroutine reads an input message and outputs an equivalent BUFR message with a tank receipt time added to Section 1.
The tank receipt time to be added must have been specified via a previous call to subroutine strcpt(). This subroutine performs the same function as subroutine strcpt() when the latter is called with CF = 'Y', except that the latter subroutine operates on BUFR messages internally within the software, whereas this subroutine operates on a single BUFR message passed in via a memory array.
Author
J. Ator
Date
2009-03-23
Parameters
[in] MSGIN – integer(*): BUFR message
[in] LMSGOT – integer: Dimensioned size (in integers) of MSGOT; used by the subroutine to ensure that it doesn't overflow the MSGOT array
[out] MSGOT – integer(*): Copy of MSGIN with a tank receipt time added to Section 1
Remarks
MSGIN and MSGOT must be separate arrays.
MSGOT will be longer in length than MSGIN, so the user must allow for extra space when allocating MSGOT within the application program.
Program history log:
Date Programmer Comments
2009-03-23 J. Ator Original author
Definition at line 34 of file atrcpt.f.
References bort(), getlens(), iupbs01(), mvb(), and pkb().
Referenced by msgwrt().