NCEPLIBS-bufr: capit.f File Reference
capit.f File Reference
Capitalize a character string.
Functions/Subroutines
subroutine capit (STR)
This subroutine capitalizes all of the alphabetic characters in a string.
Detailed Description
Capitalize a character string.
Definition in file capit.f.
Function/Subroutine Documentation
capit()
subroutine capit (character*(*) STR)
This subroutine capitalizes all of the alphabetic characters in a string.
The string is modified in place.
Author
J. Woollen
Date
2002-05-14
Parameters
[in,out] STR – character*(*): String
Program History Log:
Date Programmer Comments
2002-05-14 J. Woollen Original author
2012-03-02 J. Ator Changed name of ups array to upcs to avoid namespace contention with function ups()
Definition at line 18 of file capit.f.
Referenced by cmpmsg(), codflg(), elemdx(), stbfdx(), stdmsg(), and strcpt().