NCEPLIBS-bufr: chrtrna.f File Reference
chrtrna.f File Reference
Copy a specified number of characters from an array into a string.
Functions/Subroutines
subroutine chrtrna (STR, CHR, N)
This subroutine copies a specified number of characters from an array of characters into a character string.
Detailed Description
Copy a specified number of characters from an array into a string.
Definition in file chrtrna.f.
Function/Subroutine Documentation
chrtrna()
subroutine chrtrna (character*(*) STR, character*1, dimension(n) CHR, N)
This subroutine copies a specified number of characters from an array of characters into a character string.
The characters in the input array CHR are assumed to be ASCII, so for cases where the native machine is EBCDIC, an ASCII-to-EBCDIC translation is done on the final character string before it is output as STR.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] CHR – character(*): Array of characters in ASCII
[in] N – integer: Number of characters to be copied from CHR, starting from the beginning of the array
[out] STR – character*(*): Character string in ASCII or EBCDIC, depending on native machine
Remarks
The determination as to whether the native machine is ASCII or EBCDIC is made via an internal call to subroutine wrdlen().
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
2003-11-04 J. Ator Added documentation
Definition at line 33 of file chrtrna.f.
References ipkm(), and iupm().
Referenced by ichkstr().