NCEPLIBS-bufr: cnved4.f File Reference
cnved4.f File Reference
Convert a BUFR edition 3 message to BUFR edition 4.
Functions/Subroutines
subroutine cnved4 (MSGIN, LMSGOT, MSGOT)
This subroutine reads an input BUFR message encoded using BUFR edition 3 and outputs an equivalent BUFR message encoded using BUFR edition 4.
Detailed Description
Convert a BUFR edition 3 message to BUFR edition 4.
Definition in file cnved4.f.
Function/Subroutine Documentation
cnved4()
subroutine cnved4 (dimension(*) MSGIN, LMSGOT, dimension(*) MSGOT)
This subroutine reads an input BUFR message encoded using BUFR edition 3 and outputs an equivalent BUFR message encoded using BUFR edition 4.
This subroutine performs the same function as subroutine pkvs01() when the latter is called with S01MNEM = 'BEN' and IVAL = 4, except that the latter subroutine operates on BUFR messages internally within the software, whereas this subroutine operates on a single BUFR message passed in via a memory array.
Author
J. Ator
Date
2005-11-29
Parameters
[in] MSGIN – integer(*): BUFR message
[in] LMSGOT – integer: Dimensioned size (in integers) of MSGOT; used by the subroutine to ensure that it doesn't overflow the MSGOT array
[out] MSGOT – integer(*): Copy of MSGIN encoded using BUFR edition 4
Remarks
MSGIN and MSGOT must be separate arrays.
BUFR edition 4 messages are usually longer in length than their BUFR edition 3 counterparts, so it's usually a good idea to allow for extra space when allocating MSGOT within the application program.
Program history log:
Date Programmer Comments
2005-11-29 J. Ator Original author
2009-08-12 J. Ator Allow silent return (instead of bort() return) if MSGIN is already encoded using edition 4
Definition at line 36 of file cnved4.f.
References bort(), getlens(), iupbs01(), mvb(), nmwrd(), and pkb().
Referenced by msgwrt().