NCEPLIBS-bufr: copybf.f File Reference
copybf.f File Reference
Copy an entire BUFR file.
Functions/Subroutines
subroutine copybf (LUNIN, LUNOT)
This subroutine copies an entire BUFR file from one Fortran logical unit to another.
Detailed Description
Copy an entire BUFR file.
Definition in file copybf.f.
Function/Subroutine Documentation
copybf()
subroutine copybf (LUNIN, LUNOT)
This subroutine copies an entire BUFR file from one Fortran logical unit to another.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUNIN – integer: Fortran logical unit number for source BUFR file
[in] LUNOT – integer: Fortran logical unit number for target BUFR file
The logical unit numbers LUNIN and LUNOT must already be associated with actual filenames on the local system, typically via a Fortran "OPEN" statement.
Remarks
This subroutine uses subroutine msgwrt() to copy each BUFR message from LUNIN to LUNOT; therefore, this subroutine can be used to create a copy of LUNIN where each corresponding message in LUNOT contains any or all of the updates described in the documentation for subroutine msgwrt().
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1998-07-08 J. Woollen Replaced call to Cray library routine ABORT with call to new internal routine bort()
2000-09-19 J. Woollen Maximum message length increased from 10,000 to 20,000 bytes
2004-08-09 J. Ator Maximum message length increased from 20,000 to 50,000 bytes
2005-11-29 J. Ator Use rdmsgw() and iupbs01()
2012-09-15 J. Woollen Modified for C/I/O/BUFR interface; use status()
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 37 of file copybf.f.
References bort(), closbf(), iupbs01(), msgwrt(), openbf(), rdmsgw(), status(), and wrdlen().