NCEPLIBS-bufr: dxmini.f File Reference
dxmini.f File Reference
Functions/Subroutines
subroutine dxmini (LUN, MBAY, MBYT, MB4, MBA, MBB, MBD)
THIS SUBROUTINE INITIALIZES A BUFR TABLE (DICTIONARY) MESSAGE, WRITING ALL THE PRELIMINARY INFORMATION INTO SECTIONS 0, 1, 3, 4.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file dxmini.f.
Function/Subroutine Documentation
dxmini()
subroutine dxmini (LUN, dimension(*) MBAY, MBYT, MB4, MBA, MBB, MBD)
THIS SUBROUTINE INITIALIZES A BUFR TABLE (DICTIONARY) MESSAGE, WRITING ALL THE PRELIMINARY INFORMATION INTO SECTIONS 0, 1, 3, 4.
BUFR ARCHIVE LIBRARY SUBROUTINE WRDXTB WILL WRITE THE ACTUAL TABLE INFORMATION INTO THE MESSAGE.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1997-07-29 J. WOOLLEN – MODIFIED TO UPDATE THE CURRENT BUFR VERSION WRITTEN IN SECTION 0 FROM 2 TO 3 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 2000-09-19 J. WOOLLEN – MAXIMUM MESSAGE LENGTH INCREASED FROM 10,000 TO 20,000 BYTES 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2004-08-09 J. ATOR – MAXIMUM MESSAGE LENGTH INCREASED FROM 20,000 TO 50,000 BYTES 2005-11-29 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 12 2009-05-07 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 13 2019-05-21 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 29 2021-05-14 J. ATOR – CHANGED DEFAULT MASTER TABLE VERSION TO 36
USAGE: CALL DXMINI (LUN, MBAY, MBYT, MB4, MBA, MBB, MBD) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
OUTPUT ARGUMENT LIST: MBAY - INTEGER: (MXMSGLD4)-WORD PACKED BINARY ARRAY CONTAINING BUFR MESSAGE MBYT - INTEGER: LENGTH OF BUFR MESSAGE (BYTES) MB4 - INTEGER: BYTE NUMBER IN MESSAGE OF FIRST BYTE IN SECTION 4 MBA - INTEGER: BYTE NUMBER IN MESSAGE OF FOURTH BYTE IN SECTION 4 MBB - INTEGER: BYTE NUMBER IN MESSAGE OF FIFTH BYTE IN SECTION 4 MBD - INTEGER: BYTE NUMBER IN MESSAGE OF SIXTH BYTE IN SECTION 4
REMARKS: ARGUMENT LUN IS NOT REFERENCED IN THIS SUBROUTINE. IT IS LEFT HERE IN CASE AN APPLICATION PROGRAM CALLS THIS SUBROUTINE.
THIS ROUTINE CALLS: BORT IUPM PKB PKC THIS ROUTINE IS CALLED BY: WRDXTB Normally not called by any application programs.
Definition at line 57 of file dxmini.f.
References bort(), iupm(), modv_mxmsgl::mxmsgld4, pkb(), and pkc().
Referenced by wrdxtb().