NCEPLIBS-bufr: fstag.f File Reference
fstag.f File Reference
Functions/Subroutines
subroutine fstag (LUN, UTAG, NUTAG, NIN, NOUT, IRET)
THIS SUBROUTINE FINDS THE (NUTAG)th OCCURRENCE OF MNEMONIC UTAG WITHIN THE CURRENT OVERALL SUBSET DEFINITION, STARTING FROM PARAMETER #(NIN) WITHIN THE SUBSET.
Detailed Description
Author
J
Date
2014-10-02
Definition in file fstag.f.
Function/Subroutine Documentation
fstag()
subroutine fstag (LUN, character*(*) UTAG, NUTAG, NIN, NOUT, IRET)
THIS SUBROUTINE FINDS THE (NUTAG)th OCCURRENCE OF MNEMONIC UTAG WITHIN THE CURRENT OVERALL SUBSET DEFINITION, STARTING FROM PARAMETER #(NIN) WITHIN THE SUBSET.
THE SUBROUTINE SEARCHES FORWARD FROM NIN IF NUTAG IS POSITIVE OR ELSE BACKWARD IF NUTAG IS NEGATIVE.
PROGRAM HISTORY LOG: 2014-10-02 J. ATOR – ORIGINAL AUTHOR 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL FSTAG (LUN, UTAG, NUTAG, NIN, NOUT, IRET) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS UTAG - CHARACTER*(*): MNEMONIC NUTAG - INTEGER: ORDINAL OCCURRENCE OF UTAG TO SEARCH FOR WITHIN THE OVERALL SUBSET DEFINITION, COUNTING FROM PARAMETER #(NIN) WITHIN THE SUBSET. THE SUBROUTINE WILL SEARCH IN A FORWARD DIRECTION FROM PARAMETER #(NIN) IF NUTAG IS POSITIVE OR ELSE IN A BACKWARD DIRECTION IF NUTAG IS NEGATIVE. NIN - INTEGER: LOCATION WITHIN THE OVERALL SUBSET DEFINITION FROM WHICH TO BEGIN SEARCHING FOR UTAG.
OUTPUT ARGUMENT LIST: NOUT - INTEGER: LOCATION OF (NUTAG)th OCCURRENCE OF UTAG IRET - INTEGER: RETURN CODE 0 = NORMAL RETURN -1 = REQUESTED MNEMONIC COULD NOT BE FOUND, OR SOME OTHER ERROR OCCURRED
REMARKS: THIS ROUTINE CALLS: PARSTR THIS ROUTINE IS CALLED BY: GETTAGPR GETTAGRE GETVALNB NEMSPECS SETVALNB UFDUMP Normally not called by any application programs.
Definition at line 40 of file fstag.f.
References parstr(), and moda_tables::tag.
Referenced by gettagpr(), gettagre(), getvalnb(), nemspecs(), setvalnb(), and ufdump().