NCEPLIBS-bufr: icbfms.f File Reference
icbfms.f File Reference
Test whether a character string is "missing".
Functions/Subroutines
integer function icbfms (STR, LSTR)
This function provides a handy way to check whether a character string returned from a previous call to subroutine readlc() was encoded as "missing" (all bits set to 1) within the actual BUFR data subset.
Detailed Description
Test whether a character string is "missing".
Definition in file icbfms.f.
Function/Subroutine Documentation
icbfms()
integer function icbfms (character*(*) STR, LSTR)
This function provides a handy way to check whether a character string returned from a previous call to subroutine readlc() was encoded as "missing" (all bits set to 1) within the actual BUFR data subset.
Author
J. Ator
Date
2012-06-07
Parameters
[in] STR – character*(*): String
[in] LSTR – integer: Length of string, i.e. number of characters within STR to be tested
Returns
icbfms – integer:
0 = STR is not "missing"
1 = STR is "missing"
Remarks
The use of an integer return code allows this function to be called in a logical context from application programs written in C as well as in Fortran.
Program history log:
Date Programmer Comments
2012-06-07 J. Ator Original author
2015-03-10 J. Woollen Improved logic for testing legacy cases prior to BUFRLIB V10.2.0
2016-02-12 J. Ator Modified for CRAYFTN compatibility
Definition at line 31 of file icbfms.f.
References icbfms(), and iupm().
Referenced by icbfms(), rdcmps(), rdtree(), ufbdmp(), and ufdump().