NCEPLIBS-bufr: idn30.f File Reference
idn30.f File Reference
Convert an FXY value from its five or six character representation to its bit-wise (integer) representation.
Functions/Subroutines
function idn30 (ADN30, L30)
This function converts an FXY value from its 5 or 6 character representation to its bit-wise (integer) representation.
Detailed Description
Convert an FXY value from its five or six character representation to its bit-wise (integer) representation.
Definition in file idn30.f.
Function/Subroutine Documentation
idn30()
function idn30 (character*(*) ADN30, L30)
This function converts an FXY value from its 5 or 6 character representation to its bit-wise (integer) representation.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] ADN30 – character*(*): FXY value
[in] L30 – integer: Length of ADN30; can be either 5 or 6 characters
Returns
idn30 – integer: Bit-wise representation of FXY value
Remarks
This function is the logical inverse of function adn30().
Program History Log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1998-07-08 J. Woollen Replaced call to CRAY library routine "ABORT" with call to new internal BUFRLIB routine bort()
2003-11-04 S. Bender Added remarks and routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added history documentation
Definition at line 27 of file idn30.f.
References adn30(), bort(), idn30(), and ifxy().
Referenced by idn30(), and stbfdx().