NCEPLIBS-bufr: ifxy.f File Reference
ifxy.f File Reference
Convert an FXY value from its six character representation to its bit-wise (integer) representation.
Functions/Subroutines
function ifxy (ADSC)
This function converts an FXY value from its 6 character representation to its bit-wise (integer) representation.
Detailed Description
Convert an FXY value from its six character representation to its bit-wise (integer) representation.
Definition in file ifxy.f.
Function/Subroutine Documentation
ifxy()
function ifxy (character*6 ADSC)
This function converts an FXY value from its 6 character representation to its bit-wise (integer) representation.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] ADSC – character*6: FXY value
Returns
ifxy – integer: Bit-wise representation of FXY value
Remarks
Per the official WMO BUFR regulations, an FXY value can be represented as a bit-wise integer in 16 bits, ordered from left (most significant) to right (least significant), and where the F value occupies the first 2 bits, the X value occupies the next 6 bits, and the Y value occupies the last 8 bits.
For example, if ADSC = '063022'
   F |     X     |      Y
   0 |     63    |      22
  0 0 1 1 1 1 1 1 0 0 0 1 0 1 1 0
then the corresponding ifxy
  = ( 2**13 + 2**12 + 2**11 + 2**10 + 2**9 + 2**8 +
      2**4 + 2**2 + 2**1 )
  = 16150
Program History Log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
2003-11-04 J. Ator Added documentation
2003-11-04 S. Bender Added remarks and routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added history documentation
Definition at line 42 of file ifxy.f.
References ifxy().
Referenced by bfrini(), dxinit(), getcfmng(), getntbe(), idn30(), ifxy(), ireadmt(), nemtab(), nemtbb(), nemtbd(), nummtb(), numtbd(), reads3(), sntbde(), sntbfe(), stbfdx(), stntbi(), and ufbqcp().