NCEPLIBS-bufr: ishrdx.f File Reference
ishrdx.f File Reference
Check whether two BUFR files are sharing the same DX BUFR table.
Functions/Subroutines
integer function ishrdx (LUD, LUN)
This function determines whether the same DX BUFR Table is being shared between two Fortran logical units.
Detailed Description
Check whether two BUFR files are sharing the same DX BUFR table.
Definition in file ishrdx.f.
Function/Subroutine Documentation
ishrdx()
integer function ishrdx (LUD, LUN)
This function determines whether the same DX BUFR Table is being shared between two Fortran logical units.
Author
J. Ator
Date
2009-06-18
Parameters
[in] LUD – integer: Internal I/O stream index associated with first BUFR file
[in] LUN – integer: Internal I/O stream index associated with second BUFR file
Returns
ishrdx – integer: Flag indicating whether the same DX BUFR table is being shared between the BUFR file associated with LUD and the BUFR file associated with LUN
0 = No
1 = Yes
Program history log:
Date Programmer Comments
2009-06-18 J. Ator Original author
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 29 of file ishrdx.f.
References ishrdx(), moda_tababd::mtab, and moda_tababd::ntba.
Referenced by icmpdx(), ishrdx(), and makestab().