NCEPLIBS-bufr: lstjpb.f File Reference
lstjpb.f File Reference
Functions/Subroutines
function lstjpb (NODE, LUN, JBTYP)
THIS FUNCTION SEARCHES BACKWARDS, BEGINNING FROM A GIVEN NODE WITHIN THE JUMP/LINK TABLE, UNTIL IT FINDS THE MOST RECENT NODE OF TYPE JBTYP.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file lstjpb.f.
Function/Subroutine Documentation
lstjpb()
function lstjpb (NODE, LUN, character*(*) JBTYP)
THIS FUNCTION SEARCHES BACKWARDS, BEGINNING FROM A GIVEN NODE WITHIN THE JUMP/LINK TABLE, UNTIL IT FINDS THE MOST RECENT NODE OF TYPE JBTYP.
THE INTERNAL JMPB ARRAY IS USED TO JUMP BACKWARDS WITHIN THE JUMP/LINK TABLE, AND THE FUNCTION RETURNS THE TABLE INDEX OF THE FOUND NODE. IF THE INPUT NODE ITSELF IS OF TYPE JBTYP, THEN THE FUNCTION SIMPLY RETURNS THE INDEX OF THAT SAME NODE.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2009-03-31 J. WOOLLEN – ADDED ADDITIONAL DOCUMENTATION 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: LSTJPB (NODE, LUN, JBTYP) INPUT ARGUMENT LIST: NODE - INTEGER: JUMP/LINK TABLE INDEX OF ENTRY TO BEGIN SEARCHING BACKWARDS FROM LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS JBTYP - CHARACTER*(*): TYPE OF NODE FOR WHICH TO SEARCH
OUTPUT ARGUMENT LIST: LSTJPB - INTEGER: INDEX OF FIRST NODE OF TYPE JBTYP FOUND BY JUMPING BACKWARDS FROM INPUT NODE 0 = NO SUCH NODE FOUND
REMARKS:
SEE THE DOCBLOCK IN BUFR ARCHIVE LIBRARY SUBROUTINE TABSUB FOR AN EXPLANATION OF THE VARIOUS NODE TYPES PRESENT WITHIN AN INTERNAL JUMP/LINK TABLE
THIS ROUTINE CALLS: BORT THIS ROUTINE IS CALLED BY: GETWIN IGETRFEL NEVN NEWWIN NXTWIN PARUSR STRBTM TRYBUMP UFBRW Normally not called by any application programs.
Definition at line 57 of file lstjpb.f.
References bort(), moda_tables::isc, moda_tables::jmpb, lstjpb(), moda_tables::tag, and moda_tables::typ.
Referenced by getwin(), igetrfel(), lstjpb(), nevn(), newwin(), nxtwin(), parusr(), strbtm(), trybump(), and ufbrw().