NCEPLIBS-bufr: nemdefs.f File Reference
nemdefs.f File Reference
Get the element name and units associated with a Table B mnemonic.
Functions/Subroutines
subroutine nemdefs (LUNIT, NEMO, CELEM, CUNIT, IRET)
Given a Table B mnemonic defined in the DX BUFR Tables associated with a BUFR file (or in the master BUFR tables, if the file was opened in subroutine openbf() with IO = 'SEC3'), this subroutine returns the element name and units associated with that mnemonic.
Detailed Description
Get the element name and units associated with a Table B mnemonic.
Definition in file nemdefs.f.
Function/Subroutine Documentation
nemdefs()
subroutine nemdefs (LUNIT, character*(*) NEMO, character*(*) CELEM, character*(*) CUNIT, IRET)
Given a Table B mnemonic defined in the DX BUFR Tables associated with a BUFR file (or in the master BUFR tables, if the file was opened in subroutine openbf() with IO = 'SEC3'), this subroutine returns the element name and units associated with that mnemonic.
Author
J. Ator
Date
2014-10-02
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
[in] NEMO – character*(*): Table B mnemonic
[out] CELEM – character*55: Element name associated with NEMO
[out] CUNIT – character*24: Units associated with NEMO
[out] IRET – integer: return code
0 = normal return
-1 = NEMO could not be found, or some other error occurred
Logical unit LUNIT should have already been opened for input or output operations via a previous call to subroutine openbf().
Program history log:
Date Programmer Comments
2014-10-02 J. Ator Original version
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 36 of file nemdefs.f.
References nemtab(), status(), and moda_tababd::tabb.
Referenced by bufr_c_interface_mod::nemdefs_c().