NCEPLIBS-bufr: nemock.f File Reference
nemock.f File Reference
Functions/Subroutines
function nemock (NEMO)
THIS FUNCTION CHECKS A MNEMONIC TO VERIFY THAT IT HAS A LENGTH OF BETWEEN ONE AND EIGHT CHARACTERS AND THAT IT ONLY CONTAINS CHARACTERS FROM THE ALLOWABLE CHARACTER SET.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file nemock.f.
Function/Subroutine Documentation
nemock()
function nemock (character*(*) NEMO)
THIS FUNCTION CHECKS A MNEMONIC TO VERIFY THAT IT HAS A LENGTH OF BETWEEN ONE AND EIGHT CHARACTERS AND THAT IT ONLY CONTAINS CHARACTERS FROM THE ALLOWABLE CHARACTER SET.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – SPLIT NON-ZERO RETURN INTO -1 FOR LENGTH NOT 1-8 CHARACTERS AND -2 FOR INVALID CHARACTERS (RETURN ONLY -1 BEFORE FOR ALL PROBLEMATIC CASES); UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION
USAGE: NEMOCK (NEMO) INPUT ARGUMENT LIST: NEMO - CHARACTER*(*): MNEMONIC TO BE CHECKED
OUTPUT ARGUMENT LIST: NEMOCK - INTEGER: INDICATOR AS TO WHETHER NEMO IS VALID: 0 = yes -1 = no, length not between 1 and 8 characters -2 = no, it does not contain characters from the allowable character set
REMARKS: THIS ROUTINE CALLS: None THIS ROUTINE IS CALLED BY: RDUSDX SEQSDX SNTBBE SNTBDE Normally not called by any application programs.
Definition at line 36 of file nemock.f.
References nemock().
Referenced by nemock(), rdusdx(), seqsdx(), sntbbe(), and sntbde().