NCEPLIBS-bufr: nemtab.f File Reference
nemtab.f File Reference
Get information about a descriptor, based on the mnemonic.
Functions/Subroutines
subroutine nemtab (LUN, NEMO, IDN, TAB, IRET)
This subroutine returns information about a descriptor from the internal DX BUFR tables, based on the mnemonic associated with that descriptor.
Detailed Description
Get information about a descriptor, based on the mnemonic.
Definition in file nemtab.f.
Function/Subroutine Documentation
nemtab()
subroutine nemtab (LUN, character*(*) NEMO, IDN, character*1 TAB, IRET)
This subroutine returns information about a descriptor from the internal DX BUFR tables, based on the mnemonic associated with that descriptor.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUN – integer: Internal I/O stream index associated with DX BUFR tables
[in] NEMO – character*(*): Mnemonic
[out] IDN – integer: Bit-wise representation of FXY value for descriptor associated with NEMO
[out] TAB – character: Type associated with IDN
'B' = Table B descriptor
'D' = Table D descriptor
'C' = Table C operator
[out] IRET – integer:
Positional index of IDN within internal Table B, if TAB = 'B'
Positional index of IDN within internal Table D, if TAB = 'D'
The X portion of the FXY value in IDN, if TAB = 'C'
0, otherwise
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1995-06-28 J. Woollen Increased the size of internal BUFR table arrays in order to handle bigger files
1999-11-18 J. Woollen The number of BUFR files which can be opened at one time increased from 10 to 32
2000-09-19 J. Woollen Added capability to encode and decode data using the operator descriptors (BUFR table C) for changing width and changing scale
2003-11-04 J. Ator Added documentation
2003-11-04 S. Bender Added remarks and routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added documentation
2005-11-29 J. Ator Added support for 207 and 208 operators
2010-03-19 J. Ator Added support for 204 and 205 operators
2012-03-02 J. Ator Added support for 203 operator
2015-02-25 J. Ator Allow processing of 2-2x, 2-3x and 2-4X non-marker operators in DX tables
Definition at line 44 of file nemtab.f.
References moda_tababd::idnb, moda_tababd::idnd, ifxy(), iokoper(), moda_tababd::ntbb, moda_tababd::ntbd, moda_tababd::tabb, and moda_tababd::tabd.
Referenced by chekstab(), cmsgini(), elemdx(), getcfmng(), igetrfel(), msgini(), nemdefs(), bufr_c_interface_mod::nemtab_c(), seqsdx(), tabsub(), ufbdmp(), ufbqcd(), ufdump(), and upftbv().