NCEPLIBS-bufr: nemtba.f File Reference
nemtba.f File Reference
Search for a Table A descriptor within the internal DX BUFR tables.
Functions/Subroutines
subroutine nemtba (LUN, NEMO, MTYP, MSBT, INOD)
This subroutine searches for a descriptor within Table A of the internal DX BUFR tables.
Detailed Description
Search for a Table A descriptor within the internal DX BUFR tables.
Definition in file nemtba.f.
Function/Subroutine Documentation
nemtba()
subroutine nemtba (LUN, character*(*) NEMO, MTYP, MSBT, INOD)
This subroutine searches for a descriptor within Table A of the internal DX BUFR tables.
It is similar to subroutine nemtbax(), except that it calls subroutine bort() if the descriptor is not found in Table A, whereas nemtbax() will return an INOD value of 0 in such cases.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUN – integer: Internal I/O stream index associated with DX BUFR tables
[in] NEMO – character*(*): Mnemonic for Table A descriptor
[out] MTYP – integer: Message type corresponding to NEMO
[out] MSBT – integer: Message subtype corresponding to NEMO
[out] INOD – integer: Positional index of NEMO within internal Table A
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1995-06-28 J. Woollen Increased the size of internal BUFR table arrays in order to handle bigger files
1998-07-08 J. Woollen Replaced call to Cray library routine "ABORT" with call to new internal routine bort()
1999-11-18 J. Woollen The number of bufr files which can be opened at one time increased from 10 to 32
2003-11-04 J. Ator Added documentation
2003-11-04 S. Bender Added remarks/bufrlib routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added documentation; outputs more complete diagnostic info when routine terminates abnormally
| 2009-05-07 | J. Ator | Use nemtbax |()
Definition at line 35 of file nemtba.f.
References bort(), and nemtbax().
Referenced by cmsgini(), copymg(), cpymem(), lcmgdf(), msgini(), openmb(), and openmg().