NCEPLIBS-bufr: nemtbd.f File Reference
nemtbd.f File Reference
Get information about a Table D descriptor.
Functions/Subroutines
subroutine nemtbd (LUN, ITAB, NSEQ, NEMS, IRPS, KNTS)
This subroutine returns information about a Table D descriptor from the internal DX BUFR tables.
Detailed Description
Get information about a Table D descriptor.
Definition in file nemtbd.f.
Function/Subroutine Documentation
nemtbd()
subroutine nemtbd (LUN, ITAB, NSEQ, character*8, dimension(*) NEMS, dimension(*) IRPS, dimension(*) KNTS)
This subroutine returns information about a Table D descriptor from the internal DX BUFR tables.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] LUN – integer: Internal I/O stream index associated with DX BUFR tables
[in] ITAB – integer: Positional index of descriptor within internal Table D
[out] NSEQ – integer: Number of child mnemonics for descriptor
[out] NEMS – character*8(*): Child mnemonics
[out] IRPS – integer(*): Array of values corresponding to NEMS
5, if corresponding NEMS value is a Table D mnemonic using 1-bit delayed replication
4, if corresponding NEMS value is a Table D mnemonic using 8-bit delayed (stack) replication
3, if corresponding NEMS value is a Table D mnemonic using 8-bit delayed replication
2, if corresponding NEMS value is a Table D mnemonic using 16-bit delayed replication
1, if corresponding NEMS value is a Table D mnemonic using regular (non-delayed) replication
0, otherwise
[out] KNTS – integer(*): Array of values corresponding to NEMS
Number of replications, if corresponding NEMS value is a Table D mnemonic using regular (non-delayed) replication
0, otherwise
Remarks
This subroutine does not recursively resolve any child mnemonics which may themselves be Table D mnemonics. Instead, this subroutine only returns the list of mnemonics which are direct children of the descriptor referenced by ITAB. This information should have already been stored into internal arrays via previous calls to subroutine pktdd().
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1995-06-28 J. Woollen Increased the size of internal BUFR table arrays in order to handle bigger files
1998-07-08 J. Woollen Replaced call to Cray library routine "ABORT" with call to new internal routine bort()
1999-11-18 J. Woollen The number of BUFR files which can be opened at one time increased from 10 to 32
2000-09-19 J. Woollen Handle child mnemonics which are Table C operators
2003-11-04 S. Bender Added remarks/bufrlib routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added documentation; outputs more complete diagnostic info when routine terminates abnormally
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 54 of file nemtbd.f.
References bort(), moda_tababd::idnd, ifxy(), modv_maxcd::maxcd, moda_tababd::ntbd, numtab(), rsvfvm(), moda_tababd::tabd, and uptdd().
Referenced by chekstab(), dxdump(), getabdb(), and tabsub().