NCEPLIBS-bufr: nemtbax.f File Reference
nemtbax.f File Reference
Search for a Table A descriptor within the internal DX BUFR tables.
Functions/Subroutines
subroutine nemtbax (LUN, NEMO, MTYP, MSBT, INOD)
This subroutine searches for a descriptor within Table A of the internal DX BUFR tables.
Detailed Description
Search for a Table A descriptor within the internal DX BUFR tables.
Definition in file nemtbax.f.
Function/Subroutine Documentation
nemtbax()
subroutine nemtbax (LUN, character*(*) NEMO, MTYP, MSBT, INOD)
This subroutine searches for a descriptor within Table A of the internal DX BUFR tables.
It is similar to subroutine nemtba(), except it returns an INOD value of 0 if the descriptor is not found in Table A, whereas nemtba() will call subroutine bort() in such cases.
Author
J. Woollen
Date
1999-11-18
Parameters
[in] LUN – integer: Internal I/O stream index associated with DX BUFR tables
[in] NEMO – character*(*): Mnemonic for Table A descriptor
[out] MTYP – integer: Message type corresponding to NEMO
[out] MSBT – integer: Message subtype corresponding to NEMO
[out] INOD – integer:
Positional index of NEMO within internal Table A, if found
0, otherwise
Program history log:
Date Programmer Comments
1999-11-18 J. Woollen Original author
2003-11-04 S. Bender Added remarks/bufrlib routine interdependencies
2003-11-04 D. Keyser Unified/portable for WRF; added documentation; outputs more complete diagnostic info when routine terminates abnormally
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 33 of file nemtbax.f.
References bort(), moda_tababd::idna, moda_tababd::mtab, moda_tababd::ntba, and moda_tababd::taba.
Referenced by cktaba(), iok2cpy(), nemtba(), and stndrd().