NCEPLIBS-bufr: nxtwin.f File Reference
nxtwin.f File Reference
Functions/Subroutines
subroutine nxtwin (LUN, IWIN, JWIN)
GIVEN INDICES WITHIN THE INTERNAL JUMP/LINK TABLE WHICH POINT TO THE START AND END OF AN "RPC" WINDOW (I.E.
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file nxtwin.f.
Function/Subroutine Documentation
nxtwin()
subroutine nxtwin (LUN, IWIN, JWIN)
GIVEN INDICES WITHIN THE INTERNAL JUMP/LINK TABLE WHICH POINT TO THE START AND END OF AN "RPC" WINDOW (I.E.
ITERATION OF AN 8-BIT OR 16-BIT DELAYED REPLICATION SEQUENCE), THIS SUBROUTINE COMPUTES THE START AND END INDICES OF THE NEXT WINDOW.
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1998-07-08 J. WOOLLEN – REPLACED CALL TO CRAY LIBRARY ROUTINE "ABORT" WITH CALL TO NEW INTERNAL BUFRLIB ROUTINE "BORT" 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2002-05-14 J. WOOLLEN – REMOVED OLD CRAY COMPILER DIRECTIVES 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – MAXJL (MAXIMUM NUMBER OF JUMP/LINK ENTRIES) INCREASED FROM 15000 TO 16000 (WAS IN VERIFICATION VERSION); UNIFIED/PORTABLE FOR WRF; ADDED DOCUMENTATION (INCLUDING HISTORY) (INCOMPLETE); OUTPUTS MORE COMPLETE DIAGNOSTIC INFO WHEN ROUTINE TERMINATES ABNORMALLY 2009-03-31 J. WOOLLEN – ADDED ADDITIONAL DOCUMENTATION 2009-05-07 J. ATOR – USE LSTJPB INSTEAD OF LSTRPC 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL NXTWIN (LUN, IWIN, JWIN) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS IWIN - INTEGER: STARTING INDEX OF CURRENT WINDOW ITERATION JWIN - INTEGER: ENDING INDEX OF CURRENT WINDOW ITERATION
OUTPUT ARGUMENT LIST: IWIN - INTEGER: STARTING INDEX OF NEXT WINDOW ITERATION JWIN - INTEGER: ENDING INDEX OF NEXT WINDOW ITERATION
REMARKS:
SEE THE DOCBLOCK IN BUFR ARCHIVE LIBRARY SUBROUTINE GETWIN FOR AN EXPLANATION OF "WINDOWS" WITHIN THE CONTEXT OF A BUFR DATA SUBSET.
THIS ROUTINE CALLS: BORT LSTJPB THIS ROUTINE IS CALLED BY: UFBEVN UFBIN3 UFBRW Normally not called by any application programs.
Definition at line 52 of file nxtwin.f.
References bort(), and lstjpb().
Referenced by ufbevn(), ufbin3(), and ufbrw().