NCEPLIBS-bufr: parstr.f File Reference
parstr.f File Reference
Functions/Subroutines
subroutine parstr (STR, TAGS, MTAG, NTAG, SEP, LIMIT80)
THIS SUBROUTINE PARSES A STRING CONTAINING ONE OR MORE SUBSTRINGS INTO AN ARRAY OF SUBSTRINGS.
Detailed Description
Author
J
Date
2007-01-19
Definition in file parstr.f.
Function/Subroutine Documentation
parstr()
subroutine parstr (character*(*) STR, character*(*), dimension(mtag) TAGS, MTAG, NTAG, character*1 SEP, logical LIMIT80)
THIS SUBROUTINE PARSES A STRING CONTAINING ONE OR MORE SUBSTRINGS INTO AN ARRAY OF SUBSTRINGS.
THE SEPARATOR FOR THE SUBSTRINGS IS SPECIFIED DURING INPUT, AND MULTIPLE ADJACENT OCCURRENCES OF THIS CHARACTER WILL BE TREATED AS A SINGLE OCCURRENCE WHEN THE STRING IS ACTUALLY PARSED.
PROGRAM HISTORY LOG: 2007-01-19 J. ATOR – BASED UPON SUBROUTINE PARSEQ
USAGE: CALL PARSTR (STR, TAGS, MTAG, NTAG, SEP, LIMIT80) INPUT ARGUMENT LIST: STR - CHARACTER*(*): STRING MTAG - INTEGER: MAXIMUM NUMBER OF SUBSTRINGS TO BE PARSED FROM STRING SEP - CHARACTER*1: SEPARATOR CHARACTER FOR SUBSTRINGS LIMIT80 - LOGICAL: .TRUE. IF AN ABORT SHOULD OCCUR WHEN STR IS LONGER THAN 80 CHARACTERS; INCLUDED FOR HISTORICAL CONSISTENCY WITH OLD SUBROUTINE PARSEQ
OUTPUT ARGUMENT LIST: TAGS - CHARACTER*(*): MTAG-WORD ARRAY OF SUBSTRINGS (FIRST NTAG WORDS FILLED) NTAG - INTEGER: NUMBER OF SUBSTRINGS RETURNED
REMARKS: THIS ROUTINE CALLS: BORT2 THIS ROUTINE IS CALLED BY: FSTAG GETCFMNG GETNTBE GETTBH PARUSR READLC SEQSDX SNTBBE SNTBDE SNTBFE UFBSEQ UFBTAB UFBTAM WRITLC Normally not called by any application programs but it could be.
Definition at line 37 of file parstr.f.
References bort2().
Referenced by fdebufr(), fstag(), getcfmng(), getntbe(), gettbh(), parusr(), readlc(), seqsdx(), sntbbe(), sntbde(), sntbfe(), ufbseq(), ufbtab(), ufbtam(), and writlc().