NCEPLIBS-bufr: pktdd.f File Reference
pktdd.f File Reference
Functions/Subroutines
subroutine pktdd (ID, LUN, IDN, IRET)
THIS SUBROUTINE STORES INFORMATION ABOUT A "CHILD" MNEMONIC WITHIN THE INTERNAL BUFR TABLE D ENTRY (IN MODULE TABABD) FOR A TABLE D SEQUENCE ("PARENT") MNEMONIC WHEN THE "CHILD" MNEMONIC IS CONTAINED WITHIN THE SEQUENCE REPRESENTED BY THE "PARENT" MNEMONIC (AS DETERMINED WITHIN BUFR ARCHIVE LIBRARY SUBROUTINE SEQSDX).
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file pktdd.f.
Function/Subroutine Documentation
pktdd()
subroutine pktdd (ID, LUN, IDN, IRET)
THIS SUBROUTINE STORES INFORMATION ABOUT A "CHILD" MNEMONIC WITHIN THE INTERNAL BUFR TABLE D ENTRY (IN MODULE TABABD) FOR A TABLE D SEQUENCE ("PARENT") MNEMONIC WHEN THE "CHILD" MNEMONIC IS CONTAINED WITHIN THE SEQUENCE REPRESENTED BY THE "PARENT" MNEMONIC (AS DETERMINED WITHIN BUFR ARCHIVE LIBRARY SUBROUTINE SEQSDX).
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 1995-06-28 J. WOOLLEN – INCREASED THE SIZE OF INTERNAL BUFR TABLE ARRAYS IN ORDER TO HANDLE BIGGER FILES 1999-11-18 J. WOOLLEN – THE NUMBER OF BUFR FILES WHICH CAN BE OPENED AT ONE TIME INCREASED FROM 10 TO 32 (NECESSARY IN ORDER TO PROCESS MULTIPLE BUFR FILES UNDER THE MPI) 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION; ADDED MORE COMPLETE DIAGNOSTIC INFO WHEN UNUSUAL THINGS HAPPEN 2009-04-21 J. ATOR – USE ERRWRT 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS
USAGE: CALL PKTDD (ID, LUN, IDN, IRET) INPUT ARGUMENT LIST: ID - INTEGER: POSITIONAL INDEX OF PARENT MNEMONIC WITHIN INTERNAL BUFR TABLE D ARRAY TABD(*,*) LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS IDN - INTEGER: BIT-WISE REPRESENTATION OF FXY VALUE CORRESPONDING TO CHILD MNEMONIC 0 = delete all information about all child mnemonics from within TABD(ID,LUN)
OUTPUT ARGUMENT LIST: IRET - INTEGER: TOTAL NUMBER OF CHILD MNEMONICS STORED THUS FAR (INCLUDING IDN) FOR THE PARENT MNEMONIC GIVEN BY TABD(ID,LUN) 0 = information was cleared from TABD(ID,LUN) because input IDN value was 0 -1 = bad counter value or maximum number of child mnemonics already stored for this parent mnemonic
REMARKS: THIS ROUTINE CALLS: ERRWRT IPKM IUPM THIS ROUTINE IS CALLED BY: DXINIT SEQSDX STBFDX STSEQ Normally not called by any application programs.
Definition at line 54 of file pktdd.f.
References errwrt(), ipkm(), iupm(), modv_maxcd::maxcd, and moda_tababd::tabd.
Referenced by dxinit(), seqsdx(), and stbfdx().