NCEPLIBS-bufr: rdmems.f File Reference
rdmems.f File Reference
Read a specified data subset from a BUFR message.
Functions/Subroutines
subroutine rdmems (ISUB, IRET)
This subroutine reads a specified data subset from the BUFR message that was most recently read via a call to subroutine rdmemm() or readmm().
Detailed Description
Read a specified data subset from a BUFR message.
Definition in file rdmems.f.
Function/Subroutine Documentation
rdmems()
subroutine rdmems (ISUB, IRET)
This subroutine reads a specified data subset from the BUFR message that was most recently read via a call to subroutine rdmemm() or readmm().
Author
J. Woollen
Date
1994-01-06
Parameters
[in] ISUB – integer: Number of data subset to be read from BUFR message, counting from the beginning of the message
[out] IRET – integer: return code
0 = requested data subset was successfully read
-1 = requested subset number could not be found in the message
Whenever this subroutine returns with IRET = 0, this indicates that a new BUFR data subset (i.e. report) was successfully read into internal arrays within the BUFRLIB software, and from where it can now be easily manipulated or further parsed via calls to any of the values-reading subroutines using the Fortran logical unit number IUNIT that was returned from the most recent call to subroutine ufbmem().
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1998-07-08 J. Woollen Replaced call to Cray library routine "ABORT" with call to new internal routine bort()
1998-10-27 J. Woollen Modified to correct problems caused by in-lining code with fpp directives
1999-11-18 J. Woollen The number of BUFR files which can be opened at one time increased from 10 to 32
2000-09-19 J. Woollen Maximum message length increased from 10,000 to 20,000 bytes
2001-08-15 D. Keyser Increased MAXMEM from 8 Mb to 16 Mb
2004-08-09 J. Ator Maximum message length increased from 20,000 to 50,000 bytes
2004-11-15 D. Keyser Increased MAXMEM from 16 Mb to 50 Mb
2009-04-21 J. Ator Use errwrt()
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 42 of file rdmems.f.
References bort(), errwrt(), iupb(), moda_bitbuf::mbay, moda_bitbuf::mbyt, moda_msgmem::munit, readsb(), and status().
Referenced by ufbmms(), ufbmns(), and ufbrms().