NCEPLIBS-bufr: rdmsgw.f File Reference
rdmsgw.f File Reference
Functions/Subroutines
subroutine rdmsgw (LUNIT, MESG, IRET)
THIS SUBROUTINE READS THE NEXT BUFR MESSAGE FROM LOGICAL UNIT LUNIT AS AN ARRAY OF INTEGER WORDS.
Detailed Description
Author
ATOR
Date
2005-11-29
Definition in file rdmsgw.f.
Function/Subroutine Documentation
rdmsgw()
subroutine rdmsgw (LUNIT, dimension(*) MESG, IRET)
THIS SUBROUTINE READS THE NEXT BUFR MESSAGE FROM LOGICAL UNIT LUNIT AS AN ARRAY OF INTEGER WORDS.
PROGRAM HISTORY LOG: 2005-11-29 J. ATOR – ORIGINAL AUTHOR 2009-03-23 D. KEYSER – CALL BORT IN CASE OF MESG OVERFLOW 2012-09-15 J. WOOLLEN – CONVERT TO C LANGUAGE I/O INTERFACE; USE C ROUTINE CRDBUFR TO OBTAIN BUFR MESSAGE; REMOVE CODE WHICH CHECKS SEC0 AND MESSAGE LENGTH AS CRDBUFR DOES THAT
USAGE: CALL RDMSGW (LUNIT, MESG, IRET) INPUT ARGUMENT LIST: LUNIT - INTEGER: FORTRAN LOGICAL UNIT NUMBER FOR BUFR FILE
OUTPUT ARGUMENT LIST: MESG - *-WORD ARRAY CONTAINING BUFR MESSAGE READ FROM LUNIT IRET - INTEGER: RETURN CODE: 0 = normal return -1 = end-of-file encountered while reading from LUNIT
INPUT FILES: UNIT "LUNIT" - BUFR FILE
REMARKS: THIS ROUTINE CALLS: CRDBUFR ERRWRT STATUS THIS ROUTINE IS CALLED BY: COPYBF CPDXMM DATEBF DUMPBF MESGBC MESGBF POSAPX RDBFDX READMG UFBMEM UFBMEX Normally not called by any application programs.
Definition at line 37 of file rdmsgw.f.
References errwrt(), modv_mxmsgl::mxmsgl, and status().
Referenced by copybf(), cpdxmm(), datebf(), dumpbf(), mesgbc(), mesgbf(), posapx(), rdbfdx(), readmg(), ufbmem(), and ufbmex().