NCEPLIBS-bufr: rdmtbd.f File Reference
rdmtbd.f File Reference
Read master Table D information from local file system.
Functions/Subroutines
subroutine rdmtbd (LUNSTD, LUNLTD, MXMTBD, MXELEM, IMT, IMTV, IOGCE, ILTV, NMTBD, IMFXYN, CMMNEM, CMDSC, CMSEQ, NMELEM, IEFXYN, CEELEM)
This subroutine reads master Table D information from two separate ASCII files (one standard and one local) and then merges the output into a single set of arrays.
Detailed Description
Read master Table D information from local file system.
Definition in file rdmtbd.f.
Function/Subroutine Documentation
rdmtbd()
subroutine rdmtbd (LUNSTD, LUNLTD, MXMTBD, MXELEM, IMT, IMTV, IOGCE, ILTV, NMTBD, integer, dimension(*) IMFXYN, character, dimension(8,*) CMMNEM, character*4, dimension(*) CMDSC, character, dimension(120,*) CMSEQ, integer, dimension(*) NMELEM, integer, dimension(mxmtbd,mxelem) IEFXYN, character*120, dimension(mxmtbd,mxelem) CEELEM)
This subroutine reads master Table D information from two separate ASCII files (one standard and one local) and then merges the output into a single set of arrays.
Each of the two ASCII files must already be individually sorted in ascending order with respect to the FXY numbers.
Author
J. Ator
Date
2007-01-19
Parameters
[in] LUNSTD – integer: Fortran logical unit number for ASCII file containing standard Table D information
[in] LUNLTD – integer: Fortran logical unit number for ASCII file containing local Table D information
[in] MXMTBD – integer: Dimensioned size (in integers) of merged output arrays; used by the subroutine to ensure that it doesn't overflow these arrays
[in] MXELEM – integer: Maximum number of elements to be stored per Table D sequence within merged output arrays; used by the subroutine to ensure that it doesn't overflow these arrays
[out] IMT – integer: Master table
This value is read from both ASCII files and must be identical between them.
[out] IMTV – integer: Version number of master table
This value is read from the standard ASCII file.
[out] IOGCE – integer: Originating center
This value is read from the local ASCII file.
[out] ILTV – integer: Version number of local table
This value is read from the local ASCII file.
[out] NMTBD – integer: Number of entries in merged output arrays
[out] IMFXYN – integer(*): Merged array containing bit-wise representations of FXY numbers
[out] CMMNEM – character*8(*): Merged array containing mnemonics
[out] CMDSC – character*4(*): Merged array containing descriptor codes
[out] CMSEQ – character*120(*): Merged array containing sequence names
[out] NMELEM – integer(*): Merged array containing number of elements stored for each sequence
[out] IEFXYN – integer(*,*): Merged array containing bit-wise representations of element FXY numbers
[out] CEELEM – character*120(*,*): Merged array containing element names
Program history log:
Date Programmer Comments
2007-01-19 J. Ator Original author
2021-01-08 J. Ator Modified mstabs array declarations for GNUv10 portability
Definition at line 63 of file rdmtbd.f.
References adn30(), bort(), getntbe(), gettbh(), sntbde(), and wrdlen().
Referenced by ireadmt().