NCEPLIBS-bufr: reads3.f File Reference
reads3.f File Reference
Functions/Subroutines
subroutine reads3 (LUN)
THIS SUBROUTINE READS THE SECTION 3 DESCRIPTORS FROM THE BUFR MESSAGE IN MBAY(1,LUN).
Detailed Description
Author
ATOR
Date
2009-03-23
Definition in file reads3.f.
Function/Subroutine Documentation
reads3()
subroutine reads3 (LUN)
THIS SUBROUTINE READS THE SECTION 3 DESCRIPTORS FROM THE BUFR MESSAGE IN MBAY(1,LUN).
IT THEN USES THE BUFR MASTER TABLES TO GENERATE THE NECESSARY INFORMATION FOR THESE DESCRIPTORS WITHIN THE INTERNAL BUFR TABLE ARRAYS.
PROGRAM HISTORY LOG: 2009-03-23 J. ATOR – ORIGINAL AUTHOR 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS 2017-10-13 J. ATOR – REMOVE FUNCTIONALITY TO CHECK WHETHER NEW MASTER TABLES NEED TO BE READ (THIS FUNCTIONALITY IS NOW PART OF FUNCTION IREADMT) USAGE: CALL READS3 (LUN) INPUT ARGUMENT LIST: LUN - INTEGER: I/O STREAM INDEX INTO INTERNAL MEMORY ARRAYS
REMARKS: THIS ROUTINE CALLS: ADN30 BORT DXINIT ERRWRT IFXY IGETNTBI IGETTDI IREADMT MAKESTAB STNTBIA STSEQ UPDS3 THIS ROUTINE IS CALLED BY: READERME READMG Normally not called by any application programs.
Definition at line 30 of file reads3.f.
References adn30(), bort(), moda_dscach::cnem, dxinit(), errwrt(), moda_dscach::idcach, ifxy(), igetntbi(), igettdi(), ireadmt(), makestab(), moda_bitbuf::mbay, moda_dscach::ncnem, moda_dscach::ndc, stntbia(), stseq(), and upds3().
Referenced by readerme(), and readmg().