NCEPLIBS-bufr: rtrcptb.f File Reference
rtrcptb.f File Reference
Read the tank receipt time from Section 1 of a BUFR message.
Functions/Subroutines
subroutine rtrcptb (MBAY, IYR, IMO, IDY, IHR, IMI, IRET)
This subroutine reads the tank receipt time (if one exists) from Section 1 of a BUFR message.
Detailed Description
Read the tank receipt time from Section 1 of a BUFR message.
Definition in file rtrcptb.f.
Function/Subroutine Documentation
rtrcptb()
subroutine rtrcptb (dimension (*) MBAY, IYR, IMO, IDY, IHR, IMI, IRET)
This subroutine reads the tank receipt time (if one exists) from Section 1 of a BUFR message.
It is similar to subroutine rtrcpt(), except that it operates on a BUFR message passed in via a memory array, whereas rtrcpt() operates on the BUFR message that was read into internal arrays via the most recent call to any of the other message-reading subroutines for a specified Fortran logical unit.
Author
J. Ator
Date
2013-10-07
Parameters
[in] MBAY – integer(*): BUFR message
[out] IYR – integer: Tank receipt year
[out] IMO – integer: Tank receipt month
[out] IDY – integer: Tank receipt day
[out] IHR – integer: Tank receipt hour
[out] IMI – integer: Tank receipt minute
[out] IRET – integer: return code
0 = normal return
-1 = no tank receipt time exists within MBAY
Program history log:
Date Programmer Comments
2013-10-07 J. Ator Original author; adapted from rtrcpt()
Definition at line 31 of file rtrcptb.f.
References iupb(), and iupbs01().
Referenced by fdebufr(), and rtrcpt().