NCEPLIBS-bufr: ufbrms.f File Reference
ufbrms.f File Reference
Read one or more data values from a data subset in internal arrays.
Functions/Subroutines
subroutine ufbrms (IMSG, ISUB, USR, I1, I2, IRET, STR)
This subroutine provides a handy way to combine the functionality of subroutines rdmemm(), rdmems() and ufbint() within a single subroutine call.
Detailed Description
Read one or more data values from a data subset in internal arrays.
Definition in file ufbrms.f.
Function/Subroutine Documentation
ufbrms()
subroutine ufbrms (IMSG, ISUB, real*8, dimension(i1,i2) USR, I1, I2, IRET, character*(*) STR)
This subroutine provides a handy way to combine the functionality of subroutines rdmemm(), rdmems() and ufbint() within a single subroutine call.
Author
J. Woollen
Date
1994-01-06
Parameters
[in] IMSG – integer: Number of BUFR message to be read into scope for further processing, counting from the beginning of the internal arrays in memory
[in] ISUB – integer: Number of data subset to be read from the (IMSG)th BUFR message, counting from the beginning of the message
[out] USR – real*8(*,*): Data values
[in] I1 – integer: Actual first dimension of USR as allocated within the calling program
[in] I2 – integer: Actual second dimension of USR as allocated within the calling program
[out] IRET – integer: Number of replications of STR that were actually read from the data subset
[in] STR – character*(*): String of blank-separated Table B mnemonics in one-to-one correspondence with the number of data values that will be read from the data subset within the first dimension of USR (see DX BUFR Tables for further information about Table B mnemonics)
Program history log:
Date Programmer Comments
1994-01-06 J. Woollen Original author
1998-07-08 J. Woollen Replaced call to Cray library routine "ABORT" with call to new internal routine bort()
1999-11-18 J. Woollen Increased MAXMEM from 4 Mb to 8 Mb
2001-08-15 D. Keyser Increased MAXMEM from 8 Mb to 16 Mb
2004-11-15 D. Keyser Increased MAXMEM from 16 Mb to 50 Mb
2009-04-21 J. Ator Use errwrt()
2014-12-10 J. Ator Use modules instead of COMMON blocks
Definition at line 45 of file ufbrms.f.
References bort(), errwrt(), moda_msgmem::msgp, moda_msgmem::munit, rdmemm(), rdmems(), status(), and ufbint().