NCEPLIBS-bufr: up8.f File Reference
up8.f File Reference
Functions/Subroutines
subroutine up8 (nval, nbits, ibay, ibit)
THIS SUBROUTINE UNPACKS AND RETURNS AN 8-BYTE INTEGER CONTAINED WITHIN NBITS BITS OF IBAY, STARTING WITH BIT (IBIT+1).
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file up8.f.
Function/Subroutine Documentation
up8()
subroutine up8 (integer(8) nval, integer(4) nbits, integer(4), dimension(*) ibay, integer(4) ibit)
THIS SUBROUTINE UNPACKS AND RETURNS AN 8-BYTE INTEGER CONTAINED WITHIN NBITS BITS OF IBAY, STARTING WITH BIT (IBIT+1).
ON OUTPUT, IBIT IS UPDATED TO POINT TO THE LAST BIT THAT WAS UNPACKED. THIS IS SIMILAR TO BUFR ARCHIVE LIBRARY SUBROUTINE UPB8, EXCEPT IN UPB8 IBIT IS NOT UPDATED UPON OUTPUT (AND THE ORDER OF ARGUMENTS IS DIFFERENT).
PROGRAM HISTORY LOG: 2022-05-06 J. WOOLLEN – ORIGINAL AUTHOR
USAGE: CALL UP8 (NVAL, NBITS, IBAY, IBIT) INPUT ARGUMENT LIST: NBITS - INTEGER: NUMBER OF BITS OF IBAY WITHIN WHICH TO UNPACK NVAL IBAY - INTEGER: *-WORD PACKED BINARY ARRAY CONTAINING PACKED NVAL IBIT - INTEGER: BIT POINTER WITHIN IBAY INDICATING BIT AFTER WHICH TO START UNPACKING
OUTPUT ARGUMENT LIST: NVAL - INTEGER*8: UNPACKED INTEGER IBIT - INTEGER: BIT POINTER WITHIN IBAY INDICATING LAST BIT THAT WAS UNPACKED
REMARKS: THIS SUBROUTINE IS THE INVERSE OF BUFR ARCHIVE LIBRARY ROUTINE PKB8.
THIS ROUTINE CALLS: UPB8 THIS ROUTINE IS CALLED BY: RDCMPS WRCMPS UFBTAB
Normally not called by any application programs.
Definition at line 40 of file up8.f.
References upb8().
Referenced by rdcmps(), ufbtab(), and wrcmps().