NCEPLIBS-bufr: upb.f File Reference
upb.f File Reference
Functions/Subroutines
subroutine upb (NVAL, NBITS, IBAY, IBIT)
THIS SUBROUTINE UNPACKS AND RETURNS A BINARY INTEGER CONTAINED WITHIN NBITS BITS OF IBAY, STARTING WITH BIT (IBIT+1).
Detailed Description
Author
WOOLLEN
Date
1994-01-06
Definition in file upb.f.
Function/Subroutine Documentation
upb()
subroutine upb (NVAL, NBITS, dimension(*) IBAY, IBIT)
THIS SUBROUTINE UNPACKS AND RETURNS A BINARY INTEGER CONTAINED WITHIN NBITS BITS OF IBAY, STARTING WITH BIT (IBIT+1).
ON OUTPUT, IBIT IS UPDATED TO POINT TO THE LAST BIT THAT WAS UNPACKED. THIS IS SIMILAR TO BUFR ARCHIVE LIBRARY SUBROUTINE UPBB, EXCEPT IN UPBB IBIT IS NOT UPDATED UPON OUTPUT (AND THE ORDER OF ARGUMENTS IS DIFFERENT).
PROGRAM HISTORY LOG: 1994-01-06 J. WOOLLEN – ORIGINAL AUTHOR 2003-05-19 J. ATOR – ADDED CHECK FOR NBITS EQUAL TO ZERO 2003-11-04 J. ATOR – ADDED DOCUMENTATION 2003-11-04 J. WOOLLEN – BIG-ENDIAN/LITTLE-ENDIAN INDEPENDENT (WAS IN DECODER VERSION) 2003-11-04 S. BENDER – ADDED REMARKS/BUFRLIB ROUTINE INTERDEPENDENCIES 2003-11-04 D. KEYSER – UNIFIED/PORTABLE FOR WRF; ADDED HISTORY DOCUMENTATION 2009-03-23 J. ATOR – REWROTE TO CALL UPBB
USAGE: CALL UPB (NVAL, NBITS, IBAY, IBIT) INPUT ARGUMENT LIST: NBITS - INTEGER: NUMBER OF BITS OF IBAY WITHIN WHICH TO UNPACK NVAL IBAY - INTEGER: *-WORD PACKED BINARY ARRAY CONTAINING PACKED NVAL IBIT - INTEGER: BIT POINTER WITHIN IBAY INDICATING BIT AFTER WHICH TO START UNPACKING
OUTPUT ARGUMENT LIST: NVAL - INTEGER: UNPACKED INTEGER IBIT - INTEGER: BIT POINTER WITHIN IBAY INDICATING LAST BIT THAT WAS UNPACKED
REMARKS: THIS SUBROUTINE IS THE INVERSE OF BUFR ARCHIVE LIBRARY ROUTINE PKB.
THIS ROUTINE CALLS: UPBB THIS ROUTINE IS CALLED BY: COPYSB IUPB MVB RDCMPS RDMGSB READSB STNDRD UFBINX UFBPOS UFBTAB UFBTAM UPC WRCMPS WRITLC Normally not called by any application programs.
Definition at line 49 of file upb.f.
References upbb().
Referenced by copysb(), iupb(), mvb(), rdcmps(), rdmgsb(), readsb(), stndrd(), ufbinx(), ufbtab(), ufbtam(), upb8(), upc(), and writlc().