NCEPLIBS-bufr: ups.f File Reference
ups.f File Reference
Functions/Subroutines
real *8 function ups (IVAL, NODE)
THIS FUNCTION UNPACKS A REAL*8 USER VALUE FROM A PACKED BUFR INTEGER BY APPLYING THE PROPER SCALE AND REFERENCE VALUES.
Detailed Description
Author
J
Date
2012-03-02
Definition in file ups.f.
Function/Subroutine Documentation
ups()
real*8 function ups (integer*8 IVAL, NODE)
THIS FUNCTION UNPACKS A REAL*8 USER VALUE FROM A PACKED BUFR INTEGER BY APPLYING THE PROPER SCALE AND REFERENCE VALUES.
NORMALLY THE SCALE AND REFERENCE VALUES ARE OBTAINED FROM INDEX NODE OF THE INTERNAL JUMP/LINK TABLE ARRAYS ISC(*) AND IRF(*); HOWEVER, THE REFERENCE VALUE IN IRF(*) WILL BE OVERRIDDEN IF A 2-03 OPERATOR IS IN EFFECT FOR THIS NODE.
PROGRAM HISTORY LOG: 2012-03-02 J. ATOR – ORIGINAL AUTHOR; ADAPTED FROM INTERNAL STATEMENT FUNCTION IN OTHER SUBROUTINES 2014-12-10 J. ATOR – USE MODULES INSTEAD OF COMMON BLOCKS 2022-05-06 J. WOOLLEN – MAKE IVAL AND IMASK 8BYTE INTEGERS
USAGE: UPS (IVAL,NODE) INPUT ARGUMENT LIST: IVAL - INTEGER: PACKED BUFR INTEGER NODE - INTEGER: INDEX INTO INTERNAL JUMP/LINK TABLES
OUTPUT ARGUMENT LIST: UPS - REAL*8: USER VALUE
REMARKS: THIS ROUTINE CALLS: None THIS ROUTINE IS CALLED BY: RDCMPS RDTREE UFBGET UFBTAB UFBTAM Normally not called by any application programs.
Definition at line 32 of file ups.f.
References moda_tables::ibt, moda_nrv203::ienrv, moda_nrv203::inodnrv, moda_tables::irf, moda_tables::isc, moda_nrv203::isnrv, moda_nrv203::nnrv, moda_nrv203::nrv, moda_tables::tag, moda_nrv203::tagnrv, and ups().
Referenced by rdcmps(), rdtree(), ufbget(), ufbtab(), ufbtam(), and ups().