NCEPLIBS-bufr: adn30.f File Reference
adn30.f File Reference
Convert a WMO bit-wise representation of an FXY value to a character string of length 5 or 6.
Functions/Subroutines
character *(*) function adn30 (IDN, L30)
Convert a WMO bit-wise representation of an FXY value to a character string of length 5 or 6.
Detailed Description
Convert a WMO bit-wise representation of an FXY value to a character string of length 5 or 6.
Author
J. Woollen
Date
1994-01-06
Definition in file adn30.f.
Function/Subroutine Documentation
adn30()
character*(*) function adn30 (IDN, L30)
Convert a WMO bit-wise representation of an FXY value to a character string of length 5 or 6.
For an description of the WMO bit-wise representation of the FXY value, see ifxy().
This function is the logical inverse of function idn30().
Parameters
[in] IDN - integer: WMO bit-wise representation of FXY value.
[in] L30 - integer: Length of string to be returned; can be either 5 or 6 characters.
Returns
adn30 - character*(*): FXY character string.
Author
J. Woollen
Date
1994-01-06
Definition at line 22 of file adn30.f.
References bort().
Referenced by idn30(), igetrfel(), istdesc(), ufbqcd(), upds3(), and wrdxtb().