NCEPLIBS-bufr: bvers.f File Reference
bvers.f File Reference
Get the version number of the NCEPLIBS-bufr software.
Functions/Subroutines
subroutine bvers (CVERSTR)
Get the version number of the NCEPLIBS-bufr software.
Detailed Description
Get the version number of the NCEPLIBS-bufr software.
Author
J. Ator
Date
2009-03-23
Definition in file bvers.f.
Function/Subroutine Documentation
bvers()
subroutine bvers (character*(*) CVERSTR)
Get the version number of the NCEPLIBS-bufr software.
This subroutine returns a character string containing the version number of the NCEPLIBS-bufr software.
Parameters
[out] CVERSTR - character*(*): Version string.
Author
J. Ator
Date
2009-03-23
Definition at line 14 of file bvers.f.
References bort().
Referenced by bufr_c2f_interface::bvers_c(), and wrdlen().