NCEPLIBS-bufr: cpymem.f File Reference
cpymem.f File Reference
Copy a BUFR message.
Functions/Subroutines
recursive subroutine cpymem (LUNOT)
Copy a BUFR message from internal arrays to a file.
Detailed Description
Copy a BUFR message.
Author
J. Woollen
Date
1994-01-06
Definition in file cpymem.f.
Function/Subroutine Documentation
cpymem()
recursive subroutine cpymem (LUNOT)
Copy a BUFR message from internal arrays to a file.
This subroutine is similar to subroutine copymg(), except that it copies a BUFR message from internal arrays in memory to a specified Fortran logical unit, whereas copymg() copies a BUFR message from one Fortran logical unit to another.
One or more files of BUFR messages should have already been read into internal arrays in memory via one or more previous calls to subroutine ufbmem(), and a BUFR message should already be in scope for processing from these arrays via a previous call to subroutine rdmemm() or readmm().
Logical unit LUNOT should have already been opened for output operations via a previous call to subroutine openbf(), but there should not be any BUFR message already open for output within the internal arrays for LUNOT via a previous call to one of the message-writing subroutines.
The DX BUFR Table information associated with the internal arrays in memory and with logical unit LUNOT must contain identical definitions for the type of BUFR message to be copied from the former to the latter.
This subroutine uses subroutine msgwrt() to write to LUNOT; therefore, it can be used to transform a copy of the original BUFR message from memory with any or all of the updates described in the documentation for subroutine msgwrt().
Parameters
[in] LUNOT - integer: Fortran logical unit number for target BUFR file.
Author
J. Woollen
Date
1994-01-06
Definition at line 39 of file cpymem.f.
References bort(), moda_msgcwd::idate, modv_im8b::im8b, moda_msgcwd::inode, iok2cpy(), iupbs01(), moda_bitbuf::mbay, msgwrt(), moda_msgcwd::msub, moda_msgmem::munit, nemtba(), moda_msgcwd::nmsg, moda_msgcwd::nsub, status(), moda_tables::tag, and x84().