NCEPLIBS-bufr: drstpl.f File Reference
drstpl.f File Reference
Search for a specified mnemonic within unexpanded sequences of the internal jump/link table.
Functions/Subroutines
subroutine drstpl (INOD, LUN, INV1, INV2, INVN)
This subroutine is called by subroutine ufbrw() whenever it can't find a mnemonic it wants to write within the current subset buffer.
Detailed Description
Search for a specified mnemonic within unexpanded sequences of the internal jump/link table.
Author
Woollen
Date
1994-01-06
Definition in file drstpl.f.
Function/Subroutine Documentation
drstpl()
subroutine drstpl (INOD, LUN, INV1, INV2, INVN)
This subroutine is called by subroutine ufbrw() whenever it can't find a mnemonic it wants to write within the current subset buffer.
It looks for the mnemonic within any unexpanded "drs" (stack) or "drb" (1-bit delayed replication) sequences inside of the portion of the subset buffer bounded by the indices inv1 and inv2. If found, it expands the applicable "drs" or "drb" sequence to the point where the mnemonic in question now appears in the subset buffer, and in doing so it will also return a new value for inv2.
Parameters
[in] INOD - integer: jump/link table index of mnemonic to look for.
[in] LUN - integer: I/O stream index into internal memory arrays.
[in] INV1 - integer: starting index of the portion of the subset buffer currently being processed by ufbrw().
[in,out] INV2 - integer:
on input, ending index of the portion of the subset buffer currently being processed by ufbrw().
on output, if invn = 0 then inv2 is unchanged from its input value. Otherwise, it contains the redefined ending index of the portion of the subset buffer currently being processed by ufbrw(), since expanding a delayed replication sequence will have necessarily increased the size of this buffer.
[out] INVN - integer: location index of inod within subset buffer.
0 not found.
Author
Woollen
Date
1994-01-06
Definition at line 31 of file drstpl.f.
References invwin(), moda_tables::jmpb, newwin(), moda_tables::typ, and usrtpl().
Referenced by ufbrw().