NCEPLIBS-bufr: dumpbf.f File Reference
dumpbf.f File Reference
Read the Section 1 date-time from the first two "dummy" messages of an NCEP dump file.
Functions/Subroutines
recursive subroutine dumpbf (LUNIT, JDATE, JDUMP)
Read the Section 1 date-time from the first two "dummy" messages of an NCEP dump file.
Detailed Description
Read the Section 1 date-time from the first two "dummy" messages of an NCEP dump file.
Author
J. Woollen
Date
1996-12-11
Definition in file dumpbf.f.
Function/Subroutine Documentation
dumpbf()
recursive subroutine dumpbf (LUNIT, dimension(*) JDATE, dimension(*) JDUMP)
Read the Section 1 date-time from the first two "dummy" messages of an NCEP dump file.
This bypasses any messages at the beginning of the file which may contain embedded DX BUFR table information. Normally, the first of these two "dummy" messages contains the dump center date-time in Section 1, while the second message contains the dump initiation date-time in Section 1. Neither of these two "dummy" messages should contain any data subsets in Section 4.
Logical unit LUNIT must already be associated with a filename on the local system, typically via a Fortran "OPEN" statement.
If the subroutine fails to locate either of the two "dummy" messages within the file pointed to by LUNIT, then the corresponding JDATE or JDUMP array will be filled with all values set to (-1).
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR dump file.
[out] JDATE - integer(5): Dump center date-time stored within Section 1 of first "dummy" message:
Index 1 contains the year, in format of either YY or YYYY, depending on the most recent call to subroutine datelen().
Index 2 contains the month.
Index 3 contains the day.
Index 4 contains the hour.
Index 5 contains the minute.
[out] JDUMP – integer(5): Dump initiation date-time stored within Section 1 of second "dummy" message:
Index 1 contains the year, in format of either YY or YYYY, depending on the most recent call to subroutine datelen().
Index 2 contains the month.
Index 3 contains the day.
Index 4 contains the hour.
Index 5 contains the minute.
Author
J. Woollen
Date
1996-12-11
Definition at line 44 of file dumpbf.f.
References bort(), closbf(), errwrt(), idxmsg(), igetdate(), modv_im8b::im8b, iupbs01(), iupbs3(), moda_mgwa::mgwa, openbf(), rdmsgw(), status(), wrdlen(), x48(), and x84().