NCEPLIBS-bufr: gettagpr.f File Reference
gettagpr.f File Reference
Get the parent for a specified occurrence of a Table B or Table D mnemonic.
Functions/Subroutines
recursive subroutine gettagpr (LUNIT, TAGCH, NTAGCH, TAGPR, IRET)
This subroutine returns the Table D mnemonic corresponding to the parent sequence of a specified Table B or Table D mnemonic within a data subset definition.
Detailed Description
Get the parent for a specified occurrence of a Table B or Table D mnemonic.
Author
J. Ator
Date
2012-09-12
Definition in file gettagpr.f.
Function/Subroutine Documentation
gettagpr()
recursive subroutine gettagpr (LUNIT, character*(*) TAGCH, NTAGCH, character*(*) TAGPR, IRET)
This subroutine returns the Table D mnemonic corresponding to the parent sequence of a specified Table B or Table D mnemonic within a data subset definition.
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
[in] TAGCH – character*(*): Table B or Table D mnemonic
[in] NTAGCH – integer: Ordinal occurrence of TAGCH for which the parent Table D mnemonic is to be returned, counting from the beginning of the overall subset definition
[out] TAGPR – character*(*): Table D mnemonic corresponding to parent sequence of (NTAGCH)th occurrence of TAGCH
[out] IRET – integer: return code
0 = normal return
-1 = TAGPR could not be found, or some other error occurred
A data subset must already be in scope within the BUFRLIB internal arrays for LUNIT, either via a previous call to one of the subset-reading subroutines (when reading BUFR data subsets) or via a previous call to one of the message-writing subroutines (when writing BUFR data subsets).
Author
J. Ator
Date
2012-09-12
Definition at line 34 of file gettagpr.f.
References fstag(), modv_im8b::im8b, moda_msgcwd::inode, moda_usrint::inv, moda_tables::jmpb, status(), moda_tables::tag, x48(), and x84().