NCEPLIBS-bufr: idxmsg.f File Reference
idxmsg.f File Reference
Check whether a BUFR message contains DX BUFR tables information.
Functions/Subroutines
recursive function idxmsg (MESG)
Check whether a BUFR message contains DX BUFR tables information.
Detailed Description
Check whether a BUFR message contains DX BUFR tables information.
Author
J. Ator
Date
2009-03-23
Definition in file idxmsg.f.
Function/Subroutine Documentation
idxmsg()
recursive function idxmsg (dimension(*) MESG)
Check whether a BUFR message contains DX BUFR tables information.
This function determines whether a given BUFR message contains DX BUFR tables information that was generated by the BUFRLIB software.
Parameters
[in] MESG - integer(*): BUFR message.
Returns
Flag indicating whether MESG contains DX BUFR tables information:
0 = No
1 = Yes
Author
J. Ator
Date
2009-03-23
Definition at line 22 of file idxmsg.f.
References modv_im8b::im8b, and iupbs01().
Referenced by cpdxmm(), datebf(), dumpbf(), mesgbc(), mesgbf(), msgwrt(), posapx(), rdbfdx(), readerme(), readmg(), and ufbmem().