NCEPLIBS-bufr: ifbget.f File Reference
ifbget.f File Reference
Check whether there are any more data subsets available to be read from a BUFR message.
Functions/Subroutines
recursive function ifbget (LUNIT)
This function checks whether there are any more data subsets available to be read from within the BUFR message that is open for reading via the most recent call to any of the message-reading subroutines for a specified Fortran logical unit.
Detailed Description
Check whether there are any more data subsets available to be read from a BUFR message.
Author
J. Woollen
Date
1994-01-06
Definition in file ifbget.f.
Function/Subroutine Documentation
ifbget()
recursive function ifbget (LUNIT)
This function checks whether there are any more data subsets available to be read from within the BUFR message that is open for reading via the most recent call to any of the message-reading subroutines for a specified Fortran logical unit.
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file
Returns
ifbget - integer:
0 = there is at least one more data subset to be read from the message
-1 = there are no more data subsets to be read from the message
Author
J. Woollen
Date
1994-01-06
Definition at line 19 of file ifbget.f.
References bort(), modv_im8b::im8b, moda_msgcwd::msub, moda_msgcwd::nsub, status(), and x84().