NCEPLIBS-bufr: igetntbi.f File Reference
igetntbi.f File Reference
Get the next index for storing an entry within an internal DX BUFR table.
Functions/Subroutines
function igetntbi (LUN, CTB)
This function returns the next available index for storing an entry within a specified internal DX BUFR table.
Detailed Description
Get the next index for storing an entry within an internal DX BUFR table.
Author
J. Ator
Date
2009-03-23
Definition in file igetntbi.f.
Function/Subroutine Documentation
igetntbi()
function igetntbi (LUN, character*1 CTB)
This function returns the next available index for storing an entry within a specified internal DX BUFR table.
Parameters
[in] LUN – integer: Internal I/O stream index associated with BUFR file
[in] CTB – character: Type of internal DX BUFR table for which to return the next available index
'A' = Table A
'B' = Table B
'D' = Table D
Returns
igetntbi – integer: Next available index for storing an entry within CTB
Author
J. Ator
Date
2009-03-23
Definition at line 21 of file igetntbi.f.
References bort(), moda_tababd::ntba, moda_tababd::ntbb, and moda_tababd::ntbd.
Referenced by bufr_c2f_interface::igetntbi_c(), rdusdx(), reads3(), and stbfdx().