NCEPLIBS-bufr: igetsc.f File Reference
igetsc.f File Reference
Check for an abnormal status code associated with the processing of a file.
Functions/Subroutines
recursive function igetsc (LUNIT)
Check for an abnormal status code associated with the processing of a file.
Detailed Description
Check for an abnormal status code associated with the processing of a file.
Author
J. Ator
Date
2010-05-11
Definition in file igetsc.f.
Function/Subroutine Documentation
igetsc()
recursive function igetsc (LUNIT)
Check for an abnormal status code associated with the processing of a file.
This function returns a status code associated with any file that was previously opened via a call to subroutine openbf(), so that the application program can check whether the BUFRLIB software encountered any specific problems while processing the file.
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file.
Returns
igetsc - integer:
0 = no problems were encountered
1 = replication factor overflow in subroutine usrtpl()
Remarks
Once subroutine openbf() has been called for LUNIT, this function can then be called any number of times and at any point throughout the remainder of the life of the application program.
Author
J. Ator
Date
2010-05-11
Definition at line 26 of file igetsc.f.
References bort(), modv_im8b::im8b, moda_stcode::iscodes, status(), and x84().