NCEPLIBS-bufr: igettdi.f File Reference
igettdi.f File Reference
Get the next usable Table D index for the current master table, or reset the index.
Functions/Subroutines
function igettdi (IFLAG)
Get the next usable Table D index for the current master table, or reset the index.
Detailed Description
Get the next usable Table D index for the current master table, or reset the index.
Author
Ator
Date
2009-03-23
Definition in file igettdi.f.
Function/Subroutine Documentation
igettdi()
function igettdi (IFLAG)
Get the next usable Table D index for the current master table, or reset the index.
Depending on the value of the input flag, this function either returns the next usable scratch Table D index for the current master table or else resets the index back to its minimum value.
Parameters
[in] IFLAG - integer:
if set to 0, then the function will reset the scratch Table D index back to its minimum value
otherwise, the function will return the next usable scratch Table D index for the current master table
Returns
- integer:
-1 if function was called with IFLAG=0
otherwise, the next usable scratch Table D index for the current master table
Author
J. Ator
Date
2009-03-23
Definition at line 27 of file igettdi.f.
References bort().
Referenced by bufr_c2f_interface::igettdi_c(), and reads3().