NCEPLIBS-bufr: invmrg.f File Reference
invmrg.f File Reference
Merge parts of data subsets.
Functions/Subroutines
recursive subroutine invmrg (LUBFI, LUBFJ)
This subroutine merges parts of data subsets which have duplicate space and time coordinates but different or unique observational data.
Detailed Description
Merge parts of data subsets.
Author
J. Woollen
Date
1996-10-09
Definition in file invmrg.f.
Function/Subroutine Documentation
invmrg()
recursive subroutine invmrg (LUBFI, LUBFJ)
This subroutine merges parts of data subsets which have duplicate space and time coordinates but different or unique observational data.
Parameters
[in] LUBFI – integer: Fortran logical unit number for input BUFR file
[in] LUBFJ – integer: Fortran logical unit number for output BUFR file
Logical unit LUBFI should have already been opened for input operations via a previous call to subroutine openbf().
Logical unit LUBFJ should have already been opened for output operations via a previous call to subroutine openbf().
Remarks
This subroutine cannot merge parts of data subsets which are contained within replication sequences.
Author
J. Woollen
Date
1996-10-09
Definition at line 25 of file invmrg.f.
References bort(), ibfms(), modv_im8b::im8b, moda_usrint::inv, moda_tables::itp, moda_usrint::nval, nwords(), status(), moda_tables::typ, moda_usrint::val, and x84().