NCEPLIBS-bufr: iok2cpy.f File Reference
iok2cpy.f File Reference
Check whether a BUFR message or data subset can be copied from one BUFR file to another.
Functions/Subroutines
integer function iok2cpy (LUI, LUO)
This function determines whether a BUFR message, or a data subset from within a BUFR message, can be copied from one Fortran logical unit to another.
Detailed Description
Check whether a BUFR message or data subset can be copied from one BUFR file to another.
Author
J. Ator
Date
2009-06-26
Definition in file iok2cpy.f.
Function/Subroutine Documentation
iok2cpy()
integer function iok2cpy (LUI, LUO)
This function determines whether a BUFR message, or a data subset from within a BUFR message, can be copied from one Fortran logical unit to another.
The decision is based on whether both logical units contain identical definitions for the BUFR message type in question within their associated DX BUFR Table information. Note that it's possible for a BUFR message type to be identically defined for two different logical units even if the full set of associated DX BUFR table information isn't identical between both units.
Parameters
[in] LUI - integer: File ID for source BUFR file
[in] LUO - integer: File ID for target BUFR file
Returns
iok2cpy - integer: Flag indicating whether a BUFR message or data subset can be copied from LUI to LUO
0 = No
1 = Yes
Author
J. Ator
Date
2009-06-26
Definition at line 27 of file iok2cpy.f.
References moda_tables::ibt, icmpdx(), moda_msgcwd::inode, moda_tables::irf, moda_tables::isc, nemtbax(), moda_tables::tag, and moda_tables::typ.
Referenced by copymg(), copysb(), cpymem(), and ufbcpy().