NCEPLIBS-bufr: ipkm.f File Reference
ipkm.f File Reference
Encode an integer value within a character string.
Functions/Subroutines
recursive subroutine ipkm (CBAY, NBYT, N)
Encode an integer value within a character string.
Detailed Description
Encode an integer value within a character string.
Author
J. Woollen
Date
1994-01-06
Definition in file ipkm.f.
Function/Subroutine Documentation
ipkm()
recursive subroutine ipkm (character*8 CBAY, NBYT, N)
Encode an integer value within a character string.
This subroutine encodes an integer value within a specified number of bytes of a character string, up to a maximum of 8 bytes.
This subroutine is the logical inverse of subroutine iupm().
Parameters
[in] N - integer: Value to be encoded.
[in] NBYT - integer: Number of bytes of CBAY (up to a maximum of 8) within which to encode N.
[out] CBAY - character*(*): String of length NBYT bytes containing encoded integer N.
Author
J. Woollen
Date
1994-01-06
Definition at line 21 of file ipkm.f.
References bort(), modv_im8b::im8b, irev(), and x84().
Referenced by bfrini(), pktdd(), readlc(), wrcmps(), and wrtree().