NCEPLIBS-bufr: ireadns.f File Reference
ireadns.f File Reference
Read the next data subset from a BUFR file that was previously opened for reading.
Functions/Subroutines
recursive function ireadns (LUNIT, SUBSET, IDATE)
Read the next data subset from a BUFR file that was previously opened for reading.
Detailed Description
Read the next data subset from a BUFR file that was previously opened for reading.
Author
J. Woollen
Date
1994-01-06
Definition in file ireadns.f.
Function/Subroutine Documentation
ireadns()
recursive function ireadns (LUNIT, character*8 SUBSET, IDATE)
Read the next data subset from a BUFR file that was previously opened for reading.
This function calls BUFRLIB subroutine readns() and passes back its return code as the function value.
The use of this function allows the return code from readns() to be used as the target variable within an iterative program loop.
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file.
[out] SUBSET - character*8: Table A mnemonic for type of data subset that was read (see DX BUFR Tables for further information about Table A mnemonics).
[out] IDATE - integer: Date-time stored within Section 1 of BUFR message containing data subset that was read, in format of either YYMMDDHH or YYYYMMDDHH, depending on the most recent call to subroutine datelen().
Returns
ireadns - integer:
0 = new BUFR data subset was successfully read into internal arrays
-1 = there are no more BUFR data subsets in the file connected to logical unit LUNIT
Author
J. Woollen
Date
1994-01-06
Definition at line 31 of file ireadns.f.
References modv_im8b::im8b, readns(), x48(), and x84().
Referenced by bufr_c2f_interface::ireadns_c().