NCEPLIBS-bufr: ireadmg.f File Reference
ireadmg.f File Reference
Read the next message from a BUFR file that was previously opened for reading.
Functions/Subroutines
recursive function ireadmg (LUNIT, SUBSET, IDATE)
Calls NCEPLIBS-bufr subroutine readmg() and passes back its return code as the function value.
Detailed Description
Read the next message from a BUFR file that was previously opened for reading.
Author
J. Woollen
Date
1994-01-06
Definition in file ireadmg.f.
Function/Subroutine Documentation
ireadmg()
recursive function ireadmg (LUNIT, character*8 SUBSET, IDATE)
Calls NCEPLIBS-bufr subroutine readmg() and passes back its return code as the function value.
The use of this function allows the return code from readmg() to be used as the target variable within an iterative program loop.
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file
[out] SUBSET - character*8: Table A mnemonic for type of BUFR message that was read (see DX BUFR Tables for further information about Table A mnemonics)
[out] IDATE - integer: date-time stored within Section 1 of BUFR message that was read, in format of either YYMMDDHH or YYYYMMDDHH, depending on the most recent call to subroutine datelen()
Returns
ireadmg - integer: Return code:
0 = new BUFR message was successfully read into internal arrays
-1 = there are no more BUFR messages in the file connected to logical unit LUNIT
Author
J. Woollen
Date
1994-01-06
Definition at line 26 of file ireadmg.f.
References modv_im8b::im8b, readmg(), x48(), and x84().
Referenced by binv(), bufr_c2f_interface::ireadmg_c(), readbp(), readmp(), split_by_subset(), and ufbtab().