NCEPLIBS-bufr: isize.f File Reference
isize.f File Reference
Compute the number of characters needed to encode an integer as a string.
Functions/Subroutines
integer function isize (NUM)
This function computes and returns the number of characters needed to encode the input integer NUM as a string.
Detailed Description
Compute the number of characters needed to encode an integer as a string.
Author
Ator
Date
2009-03-23
Definition in file isize.f.
Function/Subroutine Documentation
isize()
integer function isize (NUM)
This function computes and returns the number of characters needed to encode the input integer NUM as a string.
It does not actually encode the string but rather only figures out the required size. NUM must be an integer in the range of 0 to 99999.
Parameters
[in] NUM - integer: number to be encoded
Returns
- integer: number of characters necessary to encode NUM as a string
Author
Ator
Date
2009-03-23
Definition at line 18 of file isize.f.
References bort().
Referenced by mtfnam(), ufbdmp(), and ufdump().