NCEPLIBS-bufr: mstabs.h File Reference
mstabs.h File Reference
Declare variables for internal storage of master Table B and Table D entries.
Variables
char(* cbbw_c)[4]
Master Table B bit widths; copied from Fortran cbbw array.
char(* cbelem_c)[120]
Master Table B element names; copied from Fortran cbelem array.
char(* cbmnem_c)[8]
Master Table B mnemonics; copied from Fortran cbmnem array.
char(* cbscl_c)[4]
Master Table B scale factors; copied from Fortran cbscl array.
char(* cbsref_c)[12]
Master Table B reference value; copied from Fortran cbsref array.
char(* cbunit_c)[24]
Master Table B units; copied from Fortran cbunit array.
char(* cdmnem_c)[8]
Master Table D mnemonics; copied from Fortran cdmnem array.
char(* cdseq_c)[120]
Master Table D sequence names; copied from Fortran cdseq array.
int * ibfxyn_c
Bit-wise representations of master Table B FXY numbers; copied from Fortran ibfxyn array.
int * idefxy_c
Bit-wise representations of child descriptors for master Table D sequence; copied from Fortran idefxy array.
int * idfxyn_c
Bit-wise representations of master Table D FXY numbers; copied from Fortran idfxyn array.
int * ndelem_c
Number of child descriptors for master Table D sequence; copied from Fortran ndelem array.
int nmtb_c
Number of master Table B entries; copied from Fortran nmtb variable.
int nmtd_c
Number of master Table D entries; copied from Fortran nmtd variable.
Detailed Description
Declare variables for internal storage of master Table B and Table D entries.
Since the arrays in Fortran module MODA_MSTABS are dynamically allocated and their size isn't known at compile time, then we can't directly access them from within C. Instead, we need to allocate separate array space in C and then use subroutine cpmstabs() to copy the relevant information from the Fortran module MODA_MSTABS arrays to these C arrays at run time, in order to be able to access this information from within C.
Author
J. Ator
Date
2014-12-04
Definition in file mstabs.h.
Variable Documentation
cbbw_c
char(* cbbw_c)[4] extern
Master Table B bit widths; copied from Fortran cbbw array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
cbelem_c
char(* cbelem_c)[120] extern
Master Table B element names; copied from Fortran cbelem array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
cbmnem_c
char(* cbmnem_c)[8] extern
Master Table B mnemonics; copied from Fortran cbmnem array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
cbscl_c
char(* cbscl_c)[4] extern
Master Table B scale factors; copied from Fortran cbscl array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
cbsref_c
char(* cbsref_c)[12] extern
Master Table B reference value; copied from Fortran cbsref array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
cbunit_c
char(* cbunit_c)[24] extern
Master Table B units; copied from Fortran cbunit array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
cdmnem_c
char(* cdmnem_c)[8] extern
Master Table D mnemonics; copied from Fortran cdmnem array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
cdseq_c
char(* cdseq_c)[120] extern
Master Table D sequence names; copied from Fortran cdseq array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
ibfxyn_c
int* ibfxyn_c extern
Bit-wise representations of master Table B FXY numbers; copied from Fortran ibfxyn array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and nummtb().
idefxy_c
int* idefxy_c extern
Bit-wise representations of child descriptors for master Table D sequence; copied from Fortran idefxy array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
idfxyn_c
int* idfxyn_c extern
Bit-wise representations of master Table D FXY numbers; copied from Fortran idfxyn array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and nummtb().
ndelem_c
int* ndelem_c extern
Number of child descriptors for master Table D sequence; copied from Fortran ndelem array.
Referenced by arallocc(), ardllocc(), cpmstabs(), and stseq().
nmtb_c
int nmtb_c extern
Number of master Table B entries; copied from Fortran nmtb variable.
Referenced by cpmstabs(), and nummtb().
nmtd_c
int nmtd_c extern
Number of master Table D entries; copied from Fortran nmtd variable.
Referenced by cpmstabs(), and nummtb().