NCEPLIBS-bufr: moda_msgmem Module Reference
moda_msgmem Module Reference
This module contains array and variable declarations used to store the contents of one or more BUFR files within internal memory.
Variables
integer, dimension(:), allocatable icdxts
Number of consecutive messages within mdx which constitute each DX BUFR table, beginning with the corresponding ifdxts.
integer, dimension(:), allocatable ifdxts
Pointers to the beginning of each DX BUFR table within mdx.
integer, dimension(:), allocatable ipdxm
Pointers to the beginning of each message within mdx.
integer, dimension(:), allocatable ipmsgs
Pointers to first message within msgs for which each DX BUFR table applies.
integer ldxm
Number of array elements filled within mdx (up to a maximum of MXDXW).
integer ldxts
Number of DX BUFR table that is currently in scope, depending on which BUFR message within msgs is currently in scope from the most recent call to subroutine rdmemm() or readmm().
integer, dimension(:), allocatable mdx
DX BUFR table messages read from one or more BUFR files, for use in decoding the messages in msgs.
integer mlast
Number of array elements filled within msgs (up to a maximum of MAXMEM).
integer, dimension(:), allocatable msgp
Pointers to the beginning of each message within msgs (up to a maximum of MAXMSG, and where array element 0 contains the actual number of messages stored within msgs).
integer, dimension(:), allocatable msgs
BUFR messages read from one or more BUFR files.
integer munit
Fortran logical unit number for use in accessing contents of BUFR files within internal memory.
integer mxdxm
Maximum number of DX BUFR table messages that can be stored within mdx.
integer mxdxw
Maximum number of entries that can be stored within mdx.
integer ndxm
Number of DX BUFR table messages stored within mdx (up to a maximum of MXDXM).
integer ndxts
Number of DX BUFR tables represented by the messages within mdx (up to a maximum of MXDXTS).
Detailed Description
This module contains array and variable declarations used to store the contents of one or more BUFR files within internal memory.
Data values within this module are stored by subroutines ufbmem() and cpdxmm().
Author
J. Ator
Date
2014-12-10
Variable Documentation
icdxts
integer, dimension(:), allocatable moda_msgmem::icdxts
Number of consecutive messages within mdx which constitute each DX BUFR table, beginning with the corresponding ifdxts.
Definition at line 389 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpdxmm(), and rdmemm().
ifdxts
integer, dimension(:), allocatable moda_msgmem::ifdxts
Pointers to the beginning of each DX BUFR table within mdx.
Definition at line 386 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpdxmm(), and rdmemm().
ipdxm
integer, dimension(:), allocatable moda_msgmem::ipdxm
Pointers to the beginning of each message within mdx.
Definition at line 384 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpdxmm(), and rdmemm().
ipmsgs
integer, dimension(:), allocatable moda_msgmem::ipmsgs
Pointers to first message within msgs for which each DX BUFR table applies.
Definition at line 391 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpdxmm(), rdmemm(), and ufbmex().
ldxm
integer moda_msgmem::ldxm
Number of array elements filled within mdx (up to a maximum of MXDXW).
Definition at line 359 of file modules_arrs.F90.
Referenced by cpdxmm(), rdmemm(), ufbmem(), and ufbmex().
ldxts
integer moda_msgmem::ldxts
Number of DX BUFR table that is currently in scope, depending on which BUFR message within msgs is currently in scope from the most recent call to subroutine rdmemm() or readmm().
Definition at line 366 of file modules_arrs.F90.
Referenced by rdmemm(), ufbmem(), ufbmex(), and ufbtam().
mdx
integer, dimension(:), allocatable moda_msgmem::mdx
DX BUFR table messages read from one or more BUFR files, for use in decoding the messages in msgs.
Definition at line 382 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpdxmm(), and rdmemm().
mlast
integer moda_msgmem::mlast
Number of array elements filled within msgs (up to a maximum of MAXMEM).
Definition at line 357 of file modules_arrs.F90.
Referenced by rdmemm(), ufbmem(), and ufbmex().
msgp
integer, dimension(:), allocatable moda_msgmem::msgp
Pointers to the beginning of each message within msgs (up to a maximum of MAXMSG, and where array element 0 contains the actual number of messages stored within msgs).
Definition at line 377 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), cpdxmm(), rdmemm(), ufbmem(), ufbmex(), ufbmms(), ufbrms(), and ufbtam().
msgs
integer, dimension(:), allocatable moda_msgmem::msgs
BUFR messages read from one or more BUFR files.
Definition at line 379 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), rdmemm(), ufbmem(), and ufbmex().
munit
integer moda_msgmem::munit
Fortran logical unit number for use in accessing contents of BUFR files within internal memory.
Definition at line 355 of file modules_arrs.F90.
Referenced by cpymem(), rdmemm(), rdmems(), ufbmem(), ufbmex(), ufbmms(), ufbmns(), ufbrms(), and ufbtam().
mxdxm
integer moda_msgmem::mxdxm
Maximum number of DX BUFR table messages that can be stored within mdx.
Definition at line 371 of file modules_arrs.F90.
Referenced by arallocf(), and cpdxmm().
mxdxw
integer moda_msgmem::mxdxw
Maximum number of entries that can be stored within mdx.
Definition at line 373 of file modules_arrs.F90.
Referenced by arallocf(), and cpdxmm().
ndxm
integer moda_msgmem::ndxm
Number of DX BUFR table messages stored within mdx (up to a maximum of MXDXM).
Definition at line 362 of file modules_arrs.F90.
Referenced by cpdxmm(), rdmemm(), ufbmem(), and ufbmex().
ndxts
integer moda_msgmem::ndxts
Number of DX BUFR tables represented by the messages within mdx (up to a maximum of MXDXTS).
Definition at line 369 of file modules_arrs.F90.
Referenced by cpdxmm(), rdmemm(), ufbmem(), and ufbmex().