NCEPLIBS-bufr: moda_usrint Module Reference
moda_usrint Module Reference
This module contains declarations for arrays used to store data values and associated metadata for the current BUFR data subset in scope for each I/O stream index.
Variables
integer, dimension(:,:), allocatable, target inv
Inventory pointer which links each data value to its corresponding node in the internal jump/link table.
integer, dimension(:,:), allocatable nrfelm
Referenced data value, for data values which refer to a previous data value in the BUFR data subset via an internal bitmap.
integer, dimension(:), allocatable nval
Number of data values in BUFR data subset.
real *8, dimension(:,:), allocatable, target val
Data values.
Detailed Description
This module contains declarations for arrays used to store data values and associated metadata for the current BUFR data subset in scope for each I/O stream index.
This module is used by numerous subroutines throughout the library which read or write BUFR data subsets.
Author
J. Woollen
Date
1994-01-06
Variable Documentation
inv
integer, dimension(:,:), allocatable, target moda_usrint::inv
Inventory pointer which links each data value to its corresponding node in the internal jump/link table.
Definition at line 797 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), drfini(), fstag(), bufr_c2f_interface::get_inv_c(), gettagpr(), gettagre(), getvalnb(), igetrfel(), invcon(), invmrg(), invtag(), invwin(), makestab(), nemspecs(), nevn(), newwin(), nvnwin(), nxtwin(), rcstpl(), rdcmps(), rdtree(), readlc(), setvalnb(), strbtm(), trybump(), ufbcpy(), ufbcup(), ufbdmp(), ufbevn(), ufbget(), ufbin3(), ufbint(), ufbovr(), ufbrep(), ufbrw(), ufbseq(), ufbstp(), ufbtab(), ufbtam(), ufdump(), usrtpl(), wrcmps(), writlc(), and wrtree().
nrfelm
integer, dimension(:,:), allocatable moda_usrint::nrfelm
Referenced data value, for data values which refer to a previous data value in the BUFR data subset via an internal bitmap.
Definition at line 800 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), gettagre(), rcstpl(), rdcmps(), ufbcpy(), and ufdump().
nval
integer, dimension(:), allocatable moda_usrint::nval
Number of data values in BUFR data subset.
Definition at line 795 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bfrini(), conwin(), drfini(), fstag(), bufr_c2f_interface::get_nval_c(), getwin(), igetrfel(), invcon(), invmrg(), makestab(), newwin(), nxtwin(), rcstpl(), rdcmps(), rdtree(), readlc(), trybump(), ufbcpy(), ufbcup(), ufbdmp(), ufbget(), ufbrp(), ufbseq(), ufbsp(), ufbtab(), ufbtam(), ufdump(), usrtpl(), wrcmps(), writlc(), and wrtree().
val
real*8, dimension(:,:), allocatable, target moda_usrint::val
Data values.
Definition at line 802 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bufr_c2f_interface::get_val_c(), getvalnb(), getwin(), invcon(), invmrg(), nevn(), newwin(), nwords(), nxtwin(), rcstpl(), rdcmps(), rdtree(), setvalnb(), strbtm(), trybump(), ufbcpy(), ufbcup(), ufbdmp(), ufbevn(), ufbrp(), ufbrw(), ufbseq(), ufbsp(), ufdump(), usrtpl(), and wrtree().