NCEPLIBS-bufr: moda_s01cm Module Reference
moda_s01cm Module Reference
This module contains array and variable declarations used to store custom values for certain mnemonics within Sections 0 and 1 of all future output BUFR messages written to all Fortran logical units.
Variables
character *8, dimension(:), allocatable cmnem
Section 0 and 1 mnemonics corresponding to ivmnem.
integer, dimension(:), allocatable ivmnem
Custom values for use within Sections 0 and 1 of all future output BUFR messages written to all Fortran logical units.
integer ns01v = 0
Number of custom values stored.
Detailed Description
This module contains array and variable declarations used to store custom values for certain mnemonics within Sections 0 and 1 of all future output BUFR messages written to all Fortran logical units.
These values are specified via one or more calls to subroutine pkvs01(). Otherwise, default values for these mnemonics are used as defined within subroutines msgini(), cmsgini(), or dxmini().
Author
J. Ator
Date
2015-03-03
Variable Documentation
cmnem
character*8, dimension(:), allocatable moda_s01cm::cmnem
Section 0 and 1 mnemonics corresponding to ivmnem.
Definition at line 560 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), msgwrt(), pkvs01(), and wrcmps().
ivmnem
integer, dimension(:), allocatable moda_s01cm::ivmnem
Custom values for use within Sections 0 and 1 of all future output BUFR messages written to all Fortran logical units.
Definition at line 558 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), msgwrt(), pkvs01(), and wrcmps().
ns01v
integer moda_s01cm::ns01v = 0
Number of custom values stored.
Definition at line 562 of file modules_arrs.F90.
Referenced by exitbufr(), msgwrt(), pkvs01(), and wrcmps().