NCEPLIBS-bufr: moda_stbfr Module Reference
moda_stbfr Module Reference
This module contains array declarations used to store file and message status indicators for all logical units that have been connected to the library via previous calls to subroutine openbf().
Variables
integer, dimension(:), allocatable iolun
File status indicators.
integer, dimension(:), allocatable iomsg
Message status indicator corresponding to iolun, denoting whether a BUFR message is currently open within the internal arrays for the corresponding logical unit:
Detailed Description
This module contains array declarations used to store file and message status indicators for all logical units that have been connected to the library via previous calls to subroutine openbf().
Author
J. Woollen
Date
1994-01-06
Variable Documentation
iolun
integer, dimension(:), allocatable moda_stbfr::iolun
File status indicators.
Every connected I/O stream index has a non-zero value in this array:
if the value is positive, then the logical unit number of this same value is connected for output (i.e. writing/encoding) BUFR
if the value is negative, then the logical unit number of the absolute value of this same value is connected for input (i.e. reading/decoding) BUFR
Definition at line 602 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bfrini(), exitbufr(), makestab(), status(), and wtstat().
iomsg
integer, dimension(:), allocatable moda_stbfr::iomsg
Message status indicator corresponding to iolun, denoting whether a BUFR message is currently open within the internal arrays for the corresponding logical unit:
0 no
1 yes
Definition at line 607 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bfrini(), makestab(), status(), and wtstat().