NCEPLIBS-bufr: moda_bufrsr Module Reference
moda_bufrsr Module Reference
This module contains arrays and variables needed to store the current position within a BUFR file.
Variables
integer, dimension(:), allocatable jbay
BUFR message.
integer jbit
Bit pointer within BUFR message.
integer jbyt
Length (in bytes) of BUFR message.
integer jdat
Section 1 date-time of BUFR message.
integer jill
File status indicator of BUFR file.
integer jimm
Message status indicator of BUFR file.
integer jmsg
Sequential number of BUFR message, counting from the beginning of the file.
integer jnod
Positional index of Table A mnemonic within internal Table A.
integer, dimension(:), allocatable jsr
Indicator of stack status when entering subroutine rewnbf().
integer jsub
Sequential number of BUFR data subset, counting from the beginning of the current BUFR message.
integer junn
Internal I/O stream index of BUFR file.
integer ksub
Bit-wise (integer) representation of FXY value associated with Table A mnemonic for BUFR message.
Detailed Description
This module contains arrays and variables needed to store the current position within a BUFR file.
This allows a rewind back to the first message within the file, while retaining the capability to return to the original file position at a later point within the application program.
The current position can be stored for only one BUFR file at a time.
Author
J. Ator
Date
2014-12-10
Variable Documentation
jbay
integer, dimension(:), allocatable moda_bufrsr::jbay
BUFR message.
Definition at line 124 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), and rewnbf().
jbit
integer moda_bufrsr::jbit
Bit pointer within BUFR message.
Definition at line 105 of file modules_arrs.F90.
Referenced by rewnbf().
jbyt
integer moda_bufrsr::jbyt
Length (in bytes) of BUFR message.
Definition at line 107 of file modules_arrs.F90.
Referenced by rewnbf().
jdat
integer moda_bufrsr::jdat
Section 1 date-time of BUFR message.
Definition at line 120 of file modules_arrs.F90.
Referenced by rewnbf().
jill
integer moda_bufrsr::jill
File status indicator of BUFR file.
Definition at line 101 of file modules_arrs.F90.
Referenced by rewnbf().
jimm
integer moda_bufrsr::jimm
Message status indicator of BUFR file.
Definition at line 103 of file modules_arrs.F90.
Referenced by rewnbf().
jmsg
integer moda_bufrsr::jmsg
Sequential number of BUFR message, counting from the beginning of the file.
Definition at line 110 of file modules_arrs.F90.
Referenced by rewnbf().
jnod
integer moda_bufrsr::jnod
Positional index of Table A mnemonic within internal Table A.
Definition at line 118 of file modules_arrs.F90.
Referenced by rewnbf().
jsr
integer, dimension(:), allocatable moda_bufrsr::jsr
Indicator of stack status when entering subroutine rewnbf().
Definition at line 122 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), bfrini(), and rewnbf().
jsub
integer moda_bufrsr::jsub
Sequential number of BUFR data subset, counting from the beginning of the current BUFR message.
Definition at line 113 of file modules_arrs.F90.
Referenced by rewnbf().
junn
integer moda_bufrsr::junn
Internal I/O stream index of BUFR file.
Definition at line 99 of file modules_arrs.F90.
Referenced by rewnbf().
ksub
integer moda_bufrsr::ksub
Bit-wise (integer) representation of FXY value associated with Table A mnemonic for BUFR message.
Definition at line 116 of file modules_arrs.F90.
Referenced by rewnbf().