NCEPLIBS-bufr: moda_nmikrp Module Reference
moda_nmikrp Module Reference
This module contains declarations for arrays used by various subroutines to hold information about Table D sequences.
Variables
integer, dimension(:,:), allocatable irp
Replication indicators corresponding to nem:
integer, dimension(:,:), allocatable krp
Replication counts corresponding to nem:
character *8, dimension(:,:), allocatable nem
Child mnemonics within Table D sequences.
Detailed Description
This module contains declarations for arrays used by various subroutines to hold information about Table D sequences.
These values are set via an internal call to subroutine nemtbd().
Author
J. Woollen
Date
1994-01-06
Variable Documentation
irp
integer, dimension(:,:), allocatable moda_nmikrp::irp
Replication indicators corresponding to nem:
5, if corresponding nem is a Table D mnemonic using 1-bit delayed replication
4, if corresponding nem is a Table D mnemonic using 8-bit delayed (stack) replication
3, if corresponding nem is a Table D mnemonic using 8-bit delayed replication
2, if corresponding nem is a Table D mnemonic using 16-bit delayed replication
1, if corresponding nem is a Table D mnemonic using regular (non-delayed) replication
0, otherwise
Definition at line 446 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), chekstab(), dxdump(), getabdb(), and tabsub().
krp
integer, dimension(:,:), allocatable moda_nmikrp::krp
Replication counts corresponding to nem:
Number of replications, if corresponding nem is a Table D mnemonic using regular (non-delayed) replication
0, otherwise
Definition at line 451 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), chekstab(), dxdump(), getabdb(), and tabsub().
nem
character*8, dimension(:,:), allocatable moda_nmikrp::nem
Child mnemonics within Table D sequences.
Definition at line 438 of file modules_arrs.F90.
Referenced by arallocf(), ardllocf(), chekstab(), dxdump(), getabdb(), and tabsub().