NCEPLIBS-bufr: nmsub.f File Reference
nmsub.f File Reference
Get the number of data subsets from a BUFR message.
Functions/Subroutines
recursive function nmsub (LUNIT)
This function returns the total number of data subsets available within the BUFR message that was most recently opened for reading via a call to one of the other message-reading subroutines for a specified Fortran logical unit.
Detailed Description
Get the number of data subsets from a BUFR message.
Author
J. Woollen
Date
1994-01-06
Definition in file nmsub.f.
Function/Subroutine Documentation
nmsub()
recursive function nmsub (LUNIT)
This function returns the total number of data subsets available within the BUFR message that was most recently opened for reading via a call to one of the other message-reading subroutines for a specified Fortran logical unit.
The data subsets themselves do not need to have already been read via previous calls to any of the subset-reading subroutines.
Parameters
[in] LUNIT – integer: Fortran logical unit number for BUFR file
Returns
nmsub – integer: Number of data subsets
Author
J. Woollen
Date
1994-01-06
Definition at line 21 of file nmsub.f.
References bort(), modv_im8b::im8b, moda_msgcwd::msub, status(), and x84().
Referenced by binv(), split_by_subset(), ufbmns(), ufbtab(), and ufbtam().