NCEPLIBS-bufr: openbt.f File Reference
openbt.f File Reference
Specify DX BUFR table file of last resort.
Functions/Subroutines
recursive subroutine openbt (LUNDX, MTYP)
This subroutine is called as a last resort from within subroutine cktaba(), in the event the latter subroutine is unable to locate a DX BUFR table for use in reading/decoding a given BUFR message.
Detailed Description
Specify DX BUFR table file of last resort.
Author
J. Woollen
Date
1998-07-08
Definition in file openbt.f.
Function/Subroutine Documentation
openbt()
recursive subroutine openbt (LUNDX, MTYP)
This subroutine is called as a last resort from within subroutine cktaba(), in the event the latter subroutine is unable to locate a DX BUFR table for use in reading/decoding a given BUFR message.
Within the BUFRLIB distribution package, this subroutine is a default placeholder which always returns LUNDX = 0 and is only included to allow application programs to compile without generating a link error for an unresolved external reference. However, users are free to define their own inline version of this subroutine with the same name and calling sequence and include it within the compilation of their application program in order to override the default placeholder version of this subroutine. In such cases, subroutine cktaba() will then use the inline version of this subroutine as a last resort when attempting to locate the required DX BUFR table file.
Parameters
[in] MTYP – integer: Data category of BUFR message for which subroutine cktaba() was unable to locate a DX BUFR table file
[out] LUNDX – integer: Fortran logical unit number for file containing DX BUFR table information to be used in decoding message
0 = No such file is available
Remarks
See DX BUFR Tables for more information about the format and contents of DX BUFR table files.
Author
J. Woollen
Date
1998-07-08
Definition at line 35 of file openbt.f.
References errwrt(), modv_im8b::im8b, x48(), and x84().
Referenced by cktaba().