NCEPLIBS-bufr: posapx.f File Reference
posapx.f File Reference
Position an output BUFR file for appending.
Functions/Subroutines
subroutine posapx (LUNXX)
Reads to the end of the file pointed to by abs(LUNXX) and positions it for appending.
Detailed Description
Position an output BUFR file for appending.
Author
Woollen
Date
1994-01-06
Definition in file posapx.f.
Function/Subroutine Documentation
posapx()
subroutine posapx (LUNXX)
Reads to the end of the file pointed to by abs(LUNXX) and positions it for appending.
The file must have already been opened for output operations. If LUNXX < 0, then the file is not backspaced before being positioned for append.
Parameters
[in] LUNXX - integer: absolute value is fortran logical unit number for BUFR file
Author
Woollen
Date
1994-01-06
Definition at line 17 of file posapx.f.
References bort(), idxmsg(), moda_mgwa::mgwa, rdbfdx(), rdmsgw(), and status().
Referenced by openbf().