NCEPLIBS-bufr: rcstpl.f File Reference
rcstpl.f File Reference
Store the subset template into internal arrays.
Functions/Subroutines
subroutine rcstpl (LUN, IRET)
This subroutine initializes space in internal subset array space (inv and val) in modules moda_usrint and moda_usrbit, according to the subset definition from subroutine maksetab().
Detailed Description
Store the subset template into internal arrays.
Author
Woollen
Date
1994-01-06
Definition in file rcstpl.f.
Function/Subroutine Documentation
rcstpl()
subroutine rcstpl (LUN, IRET)
This subroutine initializes space in internal subset array space (inv and val) in modules moda_usrint and moda_usrbit, according to the subset definition from subroutine maksetab().
This is in preparation for the actual unpacking of the subset in rdtree().
Parameters
[in] LUN - integer: I/O stream index into internal memory arrays.
[out] IRET - integer: return code:.
0 Normal return.
-1 An error occurred, possibly due to a corrupt subset in the input message.
Author
Woollen
Date
1994-01-06
Definition at line 17 of file rcstpl.f.
References modv_bmiss::bmiss, bort(), errwrt(), moda_tables::ibt, igetrfel(), moda_msgcwd::inode, moda_usrint::inv, moda_tables::iseq, moda_tables::itp, moda_usrtmp::iutmp, moda_tables::jseq, modv_maxjl::maxjl, modv_maxss::maxss, moda_bitbuf::mbay, moda_usrbit::mbit, moda_usrbit::nbit, moda_usrint::nrfelm, moda_usrint::nval, strbtm(), moda_tables::tag, upbb(), moda_usrint::val, moda_tables::vali, and moda_usrtmp::vutmp.
Referenced by rdtree().