NCEPLIBS-bufr: readmm.f File Reference
readmm.f File Reference
Read a specified BUFR message from internal arrays.
Functions/Subroutines
recursive subroutine readmm (IMSG, SUBSET, JDATE, IRET)
This subroutine reads a specified BUFR message from internal arrays in memory, so that it is now in scope for processing via a subsequent call to subroutine rdmems().
Detailed Description
Read a specified BUFR message from internal arrays.
Author
J. Woollen
Date
1999-11-18
Definition in file readmm.f.
Function/Subroutine Documentation
readmm()
recursive subroutine readmm (IMSG, character*8 SUBSET, JDATE, IRET)
This subroutine reads a specified BUFR message from internal arrays in memory, so that it is now in scope for processing via a subsequent call to subroutine rdmems().
BUFR messages should already be stored within internal arrays in memory via one or more previous calls to subroutine ufbmem().
This subroutine is similar to subroutine rdmemm(), except that this subroutine increments the value of IMSG prior to returning to the calling program, which in turn allows it to be easily called within an iterative program loop.
Parameters
[in,out] IMSG – integer: Message pointer within internal arrays
On input, IMSG is the number of the BUFR message to be read into scope for further processing, counting from the beginning of the internal arrays in memory
On output, IMSG is incremented by one from its input value
[out] SUBSET – character*8: Table A mnemonic for type of BUFR message that was read into scope (see DX BUFR Tables for further information about Table A mnemonics)
[out] JDATE – integer: Date-time stored within Section 1 of BUFR message that was read into scope, in format of either YYMMDDHH or YYYYMMDDHH, depending on the most recent call to subroutine datelen()
[out] IRET – integer: return code
0 = requested message was successfully read into scope
-1 = requested message number could not be found in internal arrays
Author
J. Woollen
Date
1999-11-18
Definition at line 42 of file readmm.f.
References modv_im8b::im8b, rdmemm(), x48(), and x84().
Referenced by ireadmm().