NCEPLIBS-bufr: seqsdx.f File Reference
seqsdx.f File Reference
Decode the sequence information from a Table D mnemonic definition.
Functions/Subroutines
subroutine seqsdx (CARD, LUN)
Decode the sequence information from a Table D mnemonic definition.
Detailed Description
Decode the sequence information from a Table D mnemonic definition.
Author
Woollen
Date
1994-01-06
Definition in file seqsdx.f.
Function/Subroutine Documentation
seqsdx()
subroutine seqsdx (character*80 CARD, LUN)
Decode the sequence information from a Table D mnemonic definition.
This subroutine decodes the Table D sequence information from a mnemonic definition card that was previously read from a user-supplied DX BUFR table in character format by rdusdx(). These are then added to the already-existing entry for that mnemonic (built in rdusdx()) within the internal BUFR Table D array tabd(*,lun) in module moda_tababd.
Parameters
[in] CARD - character*80: mnemonic definition card that was read from a user-supplied DX BUFR table.
[in] LUN - integer: File ID.
Author
Woollen
Date
1994-01-06
Definition at line 20 of file seqsdx.f.
References bort2(), nemock(), nemtab(), numtab(), parstr(), pktdd(), rsvfvm(), and strnum().
Referenced by rdusdx().