NCEPLIBS-bufr: stntbia.f File Reference
stntbia.f File Reference
Store a new entry within the internal BUFR Table A.
Functions/Subroutines
subroutine stntbia (N, LUN, NUMB, NEMO, CELSQ)
This subroutine stores a new entry within internal BUFR Table A.
Detailed Description
Store a new entry within the internal BUFR Table A.
Author
Ator
Date
2009-03-23
Definition in file stntbia.f.
Function/Subroutine Documentation
stntbia()
subroutine stntbia (N, LUN, character*(*) NUMB, character*(*) NEMO, character*(*) CELSQ)
This subroutine stores a new entry within internal BUFR Table A.
Parameters
[in] N - integer: storage index into internal Table A.
[in] LUN - integer: I/O stream index into internal Table A.
[in] NUMB - character*6: FXY number for new Table A entry (in format FXXYYY).
[in] NEMO - character*8: mnemonic corresponding to NUMB.
[in] CELSQ - character*55: sequence description corresponding to NUMB.
Author
Ator
Date
2009-03-23
Definition at line 14 of file stntbia.f.
References bort(), moda_tababd::idna, moda_tababd::ntba, and moda_tababd::taba.
Referenced by rdusdx(), reads3(), and stbfdx().