NCEPLIBS-bufr: trybump.f File Reference
trybump.f File Reference
Try to expand a delayed replication sequence.
Functions/Subroutines
subroutine trybump (LUN, USR, I1, I2, IO, IRET)
This subroutine checks the first node associated with a character string (parsed into arrays in common block /usrstr/) in order to determine if it represents a delayed replication sequence.
Detailed Description
Try to expand a delayed replication sequence.
Author
Woollen
Date
1994-01-06
Definition in file trybump.f.
Function/Subroutine Documentation
trybump()
subroutine trybump (LUN, real*8, dimension(i1,i2) USR, I1, I2, IO, IRET)
This subroutine checks the first node associated with a character string (parsed into arrays in common block /usrstr/) in order to determine if it represents a delayed replication sequence.
If so, then the delayed replication sequence is initialized and expanded (i.e. "bumped") to the value of input argument I2. A call is then made to subroutine ufbrw() in order to write user data into the newly expanded replication sequence.
trybump() is usually called from ufbint() after ufbint() receives a non-zero return code from ufbrw(). The cause of a bad return from ufbrw() is usually a delayed replication sequence which isn't expanded enough to hold the array of data the user is trying to write. So trybump() is one last chance to resolve that situation.
Note
Argument IO is always passed in with a value of 1 at the present time. In the future the subroutine may be expanded to allow it to operate on input files.
Parameters
[in] LUN - integer: file ID of open BUFR file
[in] USR - real*8: (i1,i2) starting address of data values to be written to data subset.
[in] I1 - integer: length of first dimension of USR.
[in] I2 - integer: number of "levels" of data values to be written to data subset.
[in] IO - integer: status indicator for BUFR file
0 Input file (possible future use)
1 Output file
[out] IRET - integer: number of "levels" of data values written to data subset.
Author
Woollen
Date
1994-01-06
Definition at line 37 of file trybump.f.
References moda_usrint::inv, invwin(), lstjpb(), moda_usrint::nval, ufbrw(), usrtpl(), and moda_usrint::val.
Referenced by ufbint(), and ufbovr().