NCEPLIBS-bufr: ufbcpy.f File Reference
ufbcpy.f File Reference
Copy a BUFR data subset.
Functions/Subroutines
recursive subroutine ufbcpy (LUBIN, LUBOT)
Copy a BUFR data subset.
Detailed Description
Copy a BUFR data subset.
Author
J. Woollen
Date
1994-01-06
Definition in file ufbcpy.f.
Function/Subroutine Documentation
ufbcpy()
recursive subroutine ufbcpy (LUBIN, LUBOT)
Copy a BUFR data subset.
This subroutine copies a BUFR data subset from one Fortran logical unit to another.
It is similar to subroutine copysb(), except that here a BUFR data subset should have already been read into internal arrays for logical unit LUBIN via a previous call to one of the subset-reading subroutines, whereas copysb() only requires that a BUFR message should have already been read into internal arrays via a previous call to one of the message-reading subroutines.
For logical unit LUBOT, a BUFR message should already be open for output within internal arrays via a previous call to one of the message-writing subroutines.
The DX BUFR Table information associated with each of the logical units LUBIN and LUBOT must contain identical definitions for the data subset to be copied.
Parameters
[in] LUBIN - integer: Fortran logical unit number for source BUFR file.
[in] LUBOT - integer: Fortran logical unit number for target BUFR file.
Author
J. Woollen
Date
1994-01-06
Definition at line 33 of file ufbcpy.f.
References bort(), modv_im8b::im8b, moda_msgcwd::inode, moda_usrint::inv, iok2cpy(), moda_ufbcpl::luncpy, moda_usrint::nrfelm, moda_usrint::nval, status(), moda_tables::tag, moda_usrint::val, and x84().
Referenced by copysb().