NCEPLIBS-bufr: ufbget.f File Reference
ufbget.f File Reference
Read one or more data values from a data subset.
Functions/Subroutines
recursive subroutine ufbget (LUNIT, TAB, I1, IRET, STR)
Read one or more data values from a data subset.
Detailed Description
Read one or more data values from a data subset.
Author
Woollen
Date
1994-01-06
Definition in file ufbget.f.
Function/Subroutine Documentation
ufbget()
recursive subroutine ufbget (LUNIT, real*8, dimension(i1) TAB, I1, IRET, character*(*) STR)
Read one or more data values from a data subset.
This subroutine unpacks and returns the values for one-dimensional descriptors in the input string without advancing the subset pointer.
Parameters
[in] LUNIT - integer: fortran logical unit number for BUFR file.
[out] TAB - real*8(*): data values.
[in] I1 - integer: size of TAB as allocated within the calling program.
[out] IRET - integer: return code:
0 normal return.
-1 there are no more subsets in the BUFR message.
[in] STR - character*(*): string of blank-separated Table B mnemonics in one-to-one correspondence with the number of data values that will be read from the data subset into TAB.
Author
Woollen
Date
1994-01-06
Definition at line 22 of file ufbget.f.
References modv_bmiss::bmiss, bort(), moda_tables::ibt, modv_im8b::im8b, moda_usrint::inv, invwin(), moda_tables::itp, moda_bitbuf::mbay, moda_usrbit::mbit, moda_bitbuf::mbyt, moda_msgcwd::msub, moda_usrbit::nbit, moda_msgcwd::nsub, moda_usrint::nval, status(), string(), upb8(), upc(), ups(), usrtpl(), x48(), and x84().