NCEPLIBS-bufr: upb8.f File Reference
upb8.f File Reference
Decode an 8-byte integer value from an integer array.
Functions/Subroutines
subroutine upb8 (nval, nbits, ibit, ibay)
This subroutine decodes an 8-byte integer value from within a specified number of bits of an integer array, starting at the bit immediately after a specified bit within the array.
Detailed Description
Decode an 8-byte integer value from an integer array.
Author
J. Woollen
Date
2022-05-06
Definition in file upb8.f.
Function/Subroutine Documentation
upb8()
subroutine upb8 (integer(8) nval, integer(4) nbits, integer(4) ibit, integer(4), dimension(*) ibay)
This subroutine decodes an 8-byte integer value from within a specified number of bits of an integer array, starting at the bit immediately after a specified bit within the array.
It is similar to subroutine up8(), except that here IBIT is only an input argument, and the overall order of the arguments is different.
This subroutine will not work properly if NBITS is less than 0 or greater than 64, as determined via an internal call to subroutine wrdlen().
Parameters
[in] IBAY - integer(*): Array containing encoded value.
[in] IBIT - integer: Bit within IBAY after which to begin decoding NVAL.
[in] NBITS - integer: Number of bits to be decoded.
[out] NVAL - integer*8: Decoded value.
Author
J. Woollen
Date
2022-05-06
Definition at line 25 of file upb8.f.
References bort(), and upb().
Referenced by rdtree(), ufbget(), ufbtab(), ufbtam(), and up8().