NCEPLIBS-bufr: x48.F File Reference
x48.F File Reference
Encode one or more 4-byte integer values as 8-byte integer values.
Functions/Subroutines
subroutine x48 (IIN4, IOUT8, NVAL)
Encode one or more 4-byte integer values as 8-byte integer values.
Detailed Description
Encode one or more 4-byte integer values as 8-byte integer values.
Author
J. Woollen
Date
2022-10-12
Definition in file x48.F.
Function/Subroutine Documentation
x48()
subroutine x48 (integer, dimension(*) IIN4, integer, dimension(*) IOUT8, NVAL)
Encode one or more 4-byte integer values as 8-byte integer values.
Note
IIN4 and IOUT8 may be the same array, as long as the underlying memory contains sufficient space for the equivalent number of 8-byte integer values.
Parameters
[in] IIN4 - integer(*): Value(s) encoded as 4-byte integers
[out] IOUT8 - integer(*): Value(s) from IIN4 now re-encoded as 8-byte integers
[in] NVAL - integer: Number of values in IIN4 to be re-encoded
Author
J. Woollen
Date
2022-10-12
Definition at line 18 of file x48.F.
References mvb(), and wrdlen().
Referenced by copysb(), datebf(), dumpbf(), fortran_close(), fortran_open(), getabdb(), getcfmng(), getlens(), gets1loc(), gettagpr(), gettagre(), igetdate(), ireadmg(), ireadmm(), ireadns(), mesgbc(), mesgbf(), nemdefs(), nemspecs(), openbt(), rdmemm(), rdmems(), readerme(), readmg(), readmm(), readns(), readsb(), rtrcpt(), rtrcptb(), setvalnb(), status(), strnum(), ufbcnt(), ufbevn(), ufbget(), ufbin3(), ufbint(), ufbinx(), ufbmem(), ufbmex(), ufbmms(), ufbmns(), ufbovr(), ufbpos(), ufbqcd(), ufbrep(), ufbrms(), ufbseq(), ufbstp(), ufbtab(), ufbtam(), upds3(), upftbv(), and writsa().