//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.18 at 11:14:51 AM EDT 
//


package C12.jabx;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="No" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CodeFigure_OriginatingCentre" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Name_OriginatingCentre" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CodeFigure_SubCentre" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Name_SubCentre" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Status" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "no",
    "codeFigureOriginatingCentre",
    "nameOriginatingCentre",
    "codeFigureSubCentre",
    "nameSubCentre",
    "status"
})
@XmlRootElement(name = "Exporting_CommonCodeTableC12_E")
public class ExportingCommonCodeTableC12E {

    @XmlElement(name = "No")
    protected Integer no;
    @XmlElement(name = "CodeFigure_OriginatingCentre")
    protected String codeFigureOriginatingCentre;
    @XmlElement(name = "Name_OriginatingCentre")
    protected String nameOriginatingCentre;
    @XmlElement(name = "CodeFigure_SubCentre")
    protected String codeFigureSubCentre;
    @XmlElement(name = "Name_SubCentre")
    protected String nameSubCentre;
    @XmlElement(name = "Status")
    protected String status;

    /**
     * Gets the value of the no property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNo() {
        return no;
    }

    /**
     * Sets the value of the no property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNo(Integer value) {
        this.no = value;
    }

    /**
     * Gets the value of the codeFigureOriginatingCentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeFigureOriginatingCentre() {
        return codeFigureOriginatingCentre;
    }

    /**
     * Sets the value of the codeFigureOriginatingCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeFigureOriginatingCentre(String value) {
        this.codeFigureOriginatingCentre = value;
    }

    /**
     * Gets the value of the nameOriginatingCentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOriginatingCentre() {
        return nameOriginatingCentre;
    }

    /**
     * Sets the value of the nameOriginatingCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOriginatingCentre(String value) {
        this.nameOriginatingCentre = value;
    }

    /**
     * Gets the value of the codeFigureSubCentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeFigureSubCentre() {
        return codeFigureSubCentre;
    }

    /**
     * Sets the value of the codeFigureSubCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeFigureSubCentre(String value) {
        this.codeFigureSubCentre = value;
    }

    /**
     * Gets the value of the nameSubCentre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSubCentre() {
        return nameSubCentre;
    }

    /**
     * Sets the value of the nameSubCentre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSubCentre(String value) {
        this.nameSubCentre = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

}
